#!/usr/bin/env python

import os
import sys
import numpy as np
import matplotlib.pyplot as plt

def expected_rsc01():
    # these data were generated by Mathematica
    data = [
        [0.996808823, 0],
        [0.989844967, 0.141863271],
        [0.976194821, 0.284448102],
        [0.953409148, 0.428342817],
        [0.920049652, 0.574319928],
        [0.87624791, 0.723271831],
        [0.823630904, 0.876122478],
        [0.764738453, 1.033745067],
        [0.702321448, 1.196905344],
        [0.638830444, 1.366234168],
        [0.57618155, 1.542222489],
        [0.515734438, 1.725228947],
        [0.458380406, 1.915491935],
        [0.404663814, 2.11314096],
        [0.35489631, 2.318204555],
        [0.309248761, 2.530613669],
        [0.267818662, 2.750200428],
        [0.230675114, 2.976692948],
        [0.197883279, 3.20970778],
        [0.169508198, 3.448742886],
        [0.145596157, 3.693175817],
        [0.126132849, 3.942273462],
        [0.11098406, 4.195219984],
        [0.099837318, 4.451166256],
        [0.092175519, 4.709296094],
        [0.087311826, 4.968894341],
        [0.084488131, 5.22939629],
        [0.08299976, 5.490403553],
        [0.082290809, 5.751666319],
        [0.081986378, 6.013045608],
        [0.081868622, 6.274472787]]
    return zip(*data)

def rsc01():
    f = open("../../tests/rogers_stallybrass_clements/gold/rsc01_swater_0191.csv")
    data = [map(float, line.strip().split(",")) for line in f.readlines()[1:] if line.strip()]
    s = [d[0] for d in data]
    x = [d[2] for d in data]
    return (s, x)

def rsc02():
    f = open("../../tests/rogers_stallybrass_clements/gold/rsc02_swater_0016.csv")
    data = [map(float, line.strip().split(",")) for line in f.readlines()[1:] if line.strip()]
    s = [d[0] for d in data]
    x = [d[2] for d in data]
    return (s, x)

plt.figure()
plt.plot(expected_rsc01()[0], expected_rsc01()[1], 'k-', linewidth = 2.0, label = 'Analytic (RSC)')
plt.plot(rsc01()[0], rsc01()[1], 'rs', markersize = 6.0, label = 'MOOSE (high-res)')
plt.plot(rsc02()[0], rsc02()[1], 'g^', markersize = 5.0, label = 'MOOSE (low-res)')
plt.legend(loc = 'lower right')
plt.xlabel("Saturation")
plt.ylabel("Depth (m)")
plt.title("Water saturation at t=5s for infiltration into two-phase system")
plt.gca().invert_yaxis()
plt.savefig("rsc.pdf")

sys.exit(0)
