Content:
    user_workshop:
        root_dir: !include tutorials/ictp/doc/config.yml Content user_workshop root_dir
        content:
            - ictp/**

Executioner: !include tutorials/ictp/doc/config.yml Executioner
Renderer: !include tutorials/ictp/doc/config.yml Renderer
Extensions: !include tutorials/ictp/doc/config.yml Extensions
