#pragma once

#include "THMControl.h"

/**
 * Control to set a boolean value of a component parameter
 */
class SetComponentBoolValueControl : public THMControl
{
public:
  SetComponentBoolValueControl(const InputParameters & parameters);

  virtual void execute();

protected:
  /// The name of the component that is controlled
  const std::string & _component_name;
  /// The parameter name in the component that is controlled
  const std::string & _param_name;
  /// Control parameter name used internally by MOOSE (the name is generated by THM)
  MooseObjectParameterName _ctrl_param_name;
  /// The value that is written into the component
  const bool & _value;

public:
  static InputParameters validParams();
};
