#ifndef SETREALVALUECONTROL_H
#define SETREALVALUECONTROL_H

#include "RELAP7Control.h"

class SetRealValueControl;
class Function;

template <>
InputParameters validParams<SetRealValueControl>();

/**
 * This block reads an input computed by the control logic system and sets a value in a specified
 * component
 */
class SetRealValueControl : public RELAP7Control
{
public:
  SetRealValueControl(const InputParameters & parameters);

  virtual void execute();

protected:
  /// The name of the component that is controlled
  const std::string & _component_name;
  /// The parameter name in the component that is controlled
  const std::string & _param_name;
  /// Control parameter name used internally by MOOSE (the name is generated by RELAP-7)
  MooseObjectParameterName _ctrl_param_name;
  /// The value that is written into the component
  const Real & _value;
};

#endif // SETREALVALUECONTROL_H
