#pragma once
#include "curl_curl_kernel.h"
#include "diffusion_kernel.h"
#include "mixed_vector_gradient_kernel.h"
#include "vector_fe_domain_lf_kernel.h"
#include "vector_fe_mass_kernel.h"
#include "vector_fe_weak_divergence_kernel.h"
#include "weak_curl_curl_kernel.h"
#include "weak_curl_kernel.h"
