#!/usr/bin/env python
import sys, os, inspect

# Set the current working directory to the directory where this script is located
os.chdir(os.path.abspath(os.path.dirname(sys.argv[0])))

#### Set the name of the application here and moose directory relative to the application
app_name = 'moose_test'

MOOSE_DIR = os.path.abspath(os.path.join('..'))
#### See if MOOSE_DIR is already in the environment instead
if os.environ.has_key("MOOSE_DIR"):
  MOOSE_DIR = os.environ['MOOSE_DIR']

sys.path.append(os.path.join(MOOSE_DIR, 'python'))
import path_tool

path_tool.activate_module('TestHarness')

# Import the TestHarness and Helper functions from the MOOSE toolkit
import tools

# create an instance of the test harness passing in the main arg vector
# and the name of the application
tools.runTests(sys.argv, app_name, MOOSE_DIR)
