moose_python:
  - python 3.12
  - python 3.11
  - python 3.10
  - python 3.9

### If you change these versions, change also conda/mpi/*, conda/seacas/*
moose_cmake:
  - cmake 3

moose_cc:
  - gcc 12.3.0 h915e2ae_13                                  # [linux]
  - clang 18.1.8 default_h576c50e_9                         # [not arm64 and osx]
  - clang 18.1.8 default_h474c9e2_9                         # [arm64]

### If you change these versions, change also conda/mpi/*, conda/seacas/*
moose_cxx:
  - gxx 12.3.0 h915e2ae_13                                  # [linux]
  - clangxx 18.1.8 default_heb2e8d1_9                       # [not arm64 and osx]
  - clangxx 18.1.8 default_h1ffe849_9                       # [arm64]

### Cmake requires these be installed in order to "find" compilers
moose_ccompiler:
  - gcc_linux-64                                            # [linux]
  - clang_osx-64                                            # [not arm64 and osx]
  - clang_osx-arm64                                         # [arm64]

moose_cxxcompiler:
  - gxx_linux-64                                            # [linux]
  - clangxx_osx-64                                          # [not arm64 and osx]
  - clangxx_osx-arm64                                       # [arm64]

#### Darwin SDK SYSROOT
CONDA_BUILD_SYSROOT:                                        # [osx]
  - /opt/MacOSX13.3.sdk                                     # [osx]

macos_min_version:                                          # [osx]
  - 13.3                                                    # [osx]

macos_machine:                                              # [osx]
  - x86_64-apple-darwin13.4.0                               # [not arm64 and osx]
  - arm64-apple-darwin22.6.0                                # [arm64]

MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 13.3                                                    # [osx]
