#!/usr/bin/env python3
import sys, os

MOOSE_DIR = os.environ.get('MOOSE_DIR', os.path.abspath(os.path.join(os.path.dirname(os.path.realpath(__file__)), '..')))
sys.path.append(os.path.join(MOOSE_DIR, 'python'))
from TestHarness import TestHarness

TestHarness.buildAndRun(sys.argv, None, MOOSE_DIR)
