{% set build = 0 %}
{% set version = "2020.12.17" %}
{% set strbuild = "build_" + build|string %}

{% set sha256 = "f8236c163aebbf8894381b7f71c42f3f3beeff6d8aee69b8a829cd76f7d5bd7a" %}

package:
  name: moose-compilers
  version: {{ version }}

source:
  path: .

build:
  number: {{ build }}  # [linux,osx]
  string: {{ strbuild }}
  skip: true # [win]

requirements:
  run:
    - gcc_linux-64 {{ gcc }}                 # [linux]
    - gxx_linux-64 {{ gxx }}                 # [linux]
    - gfortran_linux-64 {{ fortran }}        # [linux]
    - gcc_impl_linux-64 {{ gccimpl }}        # [linux]
    - clang {{ clang }}                      # [osx]
    - clang_osx-64 {{ clangosx }}            # [osx]
    - clangxx {{ clangxx }}                  # [osx]
    - clangxx_osx-64 {{ clangxxosx }}        # [osx]
    - compiler-rt {{ compilerrt }}           # [osx]
    - compiler-rt_osx-64 {{ compilerrtosx }} # [osx]
    - libllvm11 {{ libllvm }}                # [osx]
    - clang-tools                            # [osx]
    - llvm-openmp {{ llvmopenmp }}           # [osx]
    - gfortran_osx-64 {{ osxfortran }}       # [osx]
    - libclang {{ libclang }}                # [osx]
    - libcxx {{ libcxx }}                    # [osx]
    - make                                   # [unix]

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: 'This superficial module (moose-compilers) acts as a top-level module designed to provide all dependencies required in order to build and support MOOSE based developement.'

extra:
  recipe-maintainers:
    - milljm
