# MAKE SURE THAT seacas_version and seacas_git_rev match if performing a version update!
{% set build = "2" %}
{% set seacas_version = "2024.08.15" %}
{% set seacas_git_rev = "v2024-08-15" %}
{% set strbuild = "build_" + build|string %}

package:
  name: moose-seacas
  version: {{ seacas_version }}

source:
  - git_url: https://github.com/sandialabs/seacas
  - git_rev: {{ seacas_git_rev }}
  - path: ../functions/retry_build.sh

build:
  number: {{ build }}
  string: {{ strbuild }}
  script_env:
    - MOOSE_JOBS

requirements:
  build:
    - {{ moose_cc }}
    - {{ moose_cxx }}
    - {{ moose_gfortran }}
    - {{ moose_ccompiler }}
    - {{ moose_cxxcompiler }}
    - xorg-libx11 1.8.9
    - cmake
    - make
    - automake
    - wget
  run:
    - {{ moose_gfortran }}
    - {{ moose_ccompiler }}
    - {{ moose_cxxcompiler }}
    - xorg-libx11
    - python 3

test:
  commands:
    - exodiff --version
    - algebra
    - explore
    - grepos
    - gjoin -v
    - python $PREFIX/seacas/lib/tests/test_exodus3.py
    - blot --help || test $? -eq 1

about:
  home: https://github.com/sandialabs/seacas
  license: BSD 3-clause
  license_file: LICENSE
  summary: >
    The Sandia Engineering Analysis Code Access System (SEACAS) is a suite of
    preprocessing, postprocessing, translation, and utility applications supporting
    finite element analysis software using the Exodus database file format.

extra:
  recipe-maintainers:
    - cticenhour
    - milljm
    - loganharbour
