# MAKE SURE THAT seacas_version and seacas_git_rev match if performing a version update!
{% set build = "0" %}
{% set seacas_version = "2025.09.16" %}
{% set seacas_git_rev = "v2025-05-22" %}
{% set strbuild = "build_" + build|string %}

package:
  name: moose-seacas
  version: {{ seacas_version }}

source:
  - git_url: https://github.com/sandialabs/seacas
  - git_rev: {{ seacas_git_rev }}
  - git_depth: 1
  - path: ../functions/retry_build.sh
  - patches:
      - sequoia-15.4.patch

build:
  number: {{ build }}
  string: {{ strbuild }}
  script_env:
    - MOOSE_JOBS
    - REQUESTS_CA_BUNDLE
    - SSL_CERT_FILE
    - CURL_CA_BUNDLE
    - NODE_EXTRA_CA_CERTS
requirements:
  build:
    - {{ moose_cc }}
    - {{ moose_cxx }}
    - {{ moose_gfortran }}
    - {{ moose_ccompiler }}
    - {{ moose_cxxcompiler }}
    - xorg-libx11 1.8.9
    - {{ moose_cmake }}
    - make
    - automake
  run:
    - {{ moose_gfortran }}
    - {{ moose_ccompiler }}
    - {{ moose_cxxcompiler }}
    - xorg-libx11
    - python 3

test:
  commands:
    - exodiff --version
    - algebra
    - explore
    - grepos
    - gjoin -v
    - python $PREFIX/seacas/lib/tests/test_exodus3.py
    - blot --help || test $? -eq 1

about:
  home: https://github.com/sandialabs/seacas
  license: BSD 3-clause
  license_file: LICENSE
  summary: >
    The Sandia Engineering Analysis Code Access System (SEACAS) is a suite of
    preprocessing, postprocessing, translation, and utility applications supporting
    finite element analysis software using the Exodus database file format.

extra:
  recipe-maintainers:
    - cticenhour
    - milljm
    - loganharbour
