# MAKE SURE THAT seacas_version and seacas_git_rev match if performing a version update!
{% set build = "0" %}
{% set seacas_version = "2023.02.03" %}
{% set seacas_git_rev = "v2023-02-03" %}
{% set strbuild = "build_" + build|string %}

package:
  name: moose-seacas
  version: {{ seacas_version }}

source:
  git_url: https://github.com/sandialabs/seacas
  git_rev: {{ seacas_git_rev }}
  patches:
    - use-curl-instead-of-wget.patch

build:
  number: {{ build }}
  string: {{ strbuild }}
  script_env:
    - MOOSE_JOBS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - xorg-libx11
    - cmake
    - make
    - automake
  run:
    - xorg-libx11
    - python 3

test:
  commands:
    - exodiff --version
    - algebra
    - explore
    - grepos
    - gjoin -v
    - python $PREFIX/seacas/lib/tests/test_exodus3.py
    - blot --help || test $? -eq 1

about:
  home: https://github.com/sandialabs/seacas
  license: BSD 3-clause
  license_file: LICENSE
  summary: >
    The Sandia Engineering Analysis Code Access System (SEACAS) is a suite of
    preprocessing, postprocessing, translation, and utility applications supporting
    finite element analysis software using the Exodus database file format.

extra:
  recipe-maintainers:
    - cticenhour
    - milljm
    - loganharbour
