mpi:
  - mpich
  - openmpi

moose_petsc:
  - moose-petsc 3.24.5 mpich_1
  - moose-petsc 3.24.5 openmpi_1

moose_libmesh_vtk:
  - moose-libmesh-vtk 9.6.1 mpich_0
  - moose-libmesh-vtk 9.6.1 openmpi_0

zip_keys:
  - mpi
  - moose_petsc
  - moose_libmesh_vtk
