# Making a Change to this package?
# REMEMBER TO UPDATE the .yaml files for the following packages:
#   moose-dev/*
#
# As well as any directions pertaining to modifying those files.
# ALSO: Follow the directions in scripts/tests/versioner_hashes.yaml
{% set build = 0 %}
{% set version = "2026.07.13_80b5e97" %}

package:
  name: moose-libmesh
  version: {{ version }}

source:
  - path: ../../libmesh
  - path: ../../scripts/configure_libmesh.sh
  - path: ../functions/retry_build.sh

build:
  number: {{ build }}
  string: {{ mpi }}_{{ build }}
  skip: true                                            # [win]
  script_env:
    - MOOSE_JOBS
    - REQUESTS_CA_BUNDLE
    - SSL_CERT_FILE
    - CURL_CA_BUNDLE
    - NODE_EXTRA_CA_CERTS
  run_exports:
    # things that depend on this moose-libmesh must use the
    # exact moose-petsc and moose-libmesh-vtk that this was
    # built with
    - moose-petsc 3.25.3 {{ mpi }}_0
    - moose-libmesh-vtk 9.6.2 {{ mpi }}_1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib('c') }}
    - cmake
    - m4
    - make
    - pkg-config
  host:
    - {{ mpi }} {{ mpi_version }}
    - moose-petsc 3.25.3 {{ mpi }}_0
    - moose-libmesh-vtk 9.6.2 {{ mpi }}_1
    - _openmp_mutex # [linux]
    - hdf5 {{ hdf5 }}
    - hdf5 {{ hdf5 }} mpi_{{ mpi }}_*
    {% if mpi == "mpich" %}
    # see libfabric entry in conda/conda_build_config.yaml
    - libfabric {{ libfabric }} # [linux]
    {% endif %}
    - libtirpc
    - llvm-openmp # [osx]
    - zlib
  run:
    - moose-petsc 3.25.3 {{ mpi }}_0
    - moose-libmesh-vtk 9.6.2 {{ mpi }}_1

test:
  commands:
    - test $LIBMESH_DIR == $PREFIX
    - ${PREFIX}/bin/output_libmesh_version-opt

about:
  home: http://libmesh.github.io/
  license: LGPL
  summary: >
    The libMesh library provides a framework for the numerical simulation of partial differential
    equations using arbitrary unstructured discretizations on serial and parallel platforms

extra:
  recipe-maintainers:
    - cticenhour
    - loganharbour
