package:
  name: moose-libmesh
  version: __VERSIONER_LIBMESH_VERSION__

source:
  - path: ../../libmesh
  - path: ../../scripts/configure_libmesh.sh
  - path: ../functions/retry_build.sh

build:
  number: __VERSIONER_LIBMESH_BUILD_NUMBER__
  string: {{ mpi }}___VERSIONER_LIBMESH_BUILD_NUMBER__
  skip: true                                            # [win]
  script_env:
    - MOOSE_JOBS
    - REQUESTS_CA_BUNDLE
    - SSL_CERT_FILE

requirements:
  build:
    - {{ moose_petsc }}
    - {{ moose_libmesh_vtk }}
    - pkg-config
    - libpng
    - zlib
  run:
    - {{ mpi }}
    - {{ moose_petsc }}
    - {{ moose_libmesh_vtk }}
    - pkg-config
    - packaging

test:
  commands:
    - test -f $PREFIX/libmesh/lib/libmesh_opt.dylib     # [osx]
    - test -f $PREFIX/libmesh/lib/libmesh_opt.so        # [linux]
    - test -f $PREFIX/libmesh/lib/libmetaphysicl.dylib  # [osx]
    - test -f $PREFIX/libmesh/lib/libmetaphysicl.so     # [linux]
    - test -f $PREFIX/libmesh/lib/libtimpi_opt.dylib    # [osx]
    - test -f $PREFIX/libmesh/lib/libtimpi_opt.so       # [linux]

about:
  home: http://libmesh.github.io/
  license: LGPL
  summary: >
    The libMesh library provides a framework for the numerical simulation of partial differential
    equations using arbitrary unstructured discretizations on serial and parallel platforms

extra:
  recipe-maintainers:
    - milljm
    - cticenhour
