# Making a Change to this package?
# REMEMBER TO UPDATE the .yaml files for the following packages:
#   moose-dev/*
#
# As well as any directions pertaining to modifying those files.
# ALSO: Follow the directions in scripts/tests/versioner_hashes.yaml
{% set build = 0 %}
{% set version = "2026.04.07_3ca87a2" %}

package:
  name: moose-libmesh
  version: {{ version }}

source:
  - path: ../../libmesh
  - path: ../../scripts/configure_libmesh.sh
  - path: ../functions/retry_build.sh

build:
  number: {{ build }}
  string: {{ mpi }}_{{ build }}
  skip: true                                            # [win]
  script_env:
    - MOOSE_JOBS
    - REQUESTS_CA_BUNDLE
    - SSL_CERT_FILE
    - CURL_CA_BUNDLE
    - NODE_EXTRA_CA_CERTS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib('c') }}
    - cmake
    - make
    - pkg-config
  host:
    - moose-petsc 3.24.5 {{ mpi }}_1
    - moose-libmesh-vtk 9.6.1 {{ mpi }}_0
    - _openmp_mutex
    - libtirpc
    - zlib

test:
  requires:
    - {{ compiler('cxx') }}
    - make
  commands:
    - test $LIBMESH_DIR == ${PREFIX}/moose-libmesh
    - ${LIBMESH_DIR}/bin/output_libmesh_version-opt
    - cp -r ${LIBMESH_DIR}/examples/fem_system/ex1 . && cd ex1 && make && sh run.sh && cd .. && rm -rf ex1

about:
  home: http://libmesh.github.io/
  license: LGPL
  summary: >
    The libMesh library provides a framework for the numerical simulation of partial differential
    equations using arbitrary unstructured discretizations on serial and parallel platforms

extra:
  recipe-maintainers:
    - cticenhour
    - loganharbour
