# Do not use jinja templating (A physical change to this file is required to trigger a build)
{% set build = 1 %}
{% set strbuild = "build_" + build|string %}
{% set version = "2022.05.12" %}

package:
  name: moose-libmesh
  version: {{ version }}

source:
  - path: ../../libmesh
  - path: ../../scripts/configure_libmesh.sh

build:
  number: {{ build }}
  string: {{ strbuild }}
  skip: true                                            # [win]
  script_env:
    - MOOSE_JOBS

requirements:
  build:
    - libtool                                           # [arm64]
    - autoconf                                          # [arm64]
    - automake 1.16.1                                   # [arm64]
    - make                                              # [arm64]
    - m4                                                # [arm64]
    - pkg-config
    - {{ moose_libmesh_vtk }}
    - {{ moose_petsc }}

  run:
    - pkg-config
    - {{ moose_libmesh_vtk }}
    - {{ moose_petsc }}
    - {{ moose_libpng }}

test:
  commands:
    - test -f $PREFIX/libmesh/lib/libmesh_opt.dylib     # [osx]
    - test -f $PREFIX/libmesh/lib/libmesh_opt.so        # [linux]
    - test -f $PREFIX/libmesh/lib/libmetaphysicl.dylib  # [osx]
    - test -f $PREFIX/libmesh/lib/libmetaphysicl.so     # [linux]
    - test -f $PREFIX/libmesh/lib/libtimpi_opt.dylib    # [osx]
    - test -f $PREFIX/libmesh/lib/libtimpi_opt.so       # [linux]

about:
  home: http://libmesh.github.io/
  license: LGPL
  summary: 'The libMesh library provides a framework for the numerical simulation of partial differential equations using arbitrary unstructured discretizations on serial and parallel platforms'

extra:
  recipe-maintainers:
    - milljm
    - cticenhour
