name: Set up WSL
description: Use Vampire/setup-wsl to set up WSL

runs:
  using: composite
  steps:
    - name: Set up WSL
      uses: Vampire/setup-wsl@d1da7f2c0322a5ee4f24975344f67fc0f5baf364
      with:
        distribution: Ubuntu-24.04
        update: 'true'
    - uses: idaholab/moose/setup-utils@actions
      name: Setup utils
      with:
        shell: wsl-bash {0}
    - name: Clean WSL packages
      shell: wsl-bash {0}
      run: |
        echo "::group::Clean WSL packages"
        source $MOOSE_UTILS_PATH
        print_and_run apt-get autoremove -y
        print_and_run apt-get clean
        print_and_run rm -rf /var/lib/apt/lists/*
        echo "::endgroup::"
