//* This file is part of the MOOSE framework
//* https://mooseframework.inl.gov
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#include "CutMeshByLevelSetGeneratorBase.h"
#include "MooseMeshElementConversionUtils.h"
#include "MooseMeshUtils.h"

#include "libmesh/elem.h"
#include "libmesh/boundary_info.h"
#include "libmesh/mesh_base.h"
#include "libmesh/parallel.h"
#include "libmesh/parallel_algebra.h"
#include "libmesh/cell_tet4.h"
#include "libmesh/cell_c0polyhedron.h"
#include "libmesh/face_c0polygon.h"

// C++ includes
#include <cmath>

InputParameters
CutMeshByLevelSetGeneratorBase::validParams()
{
  InputParameters params = MeshGenerator::validParams();
  params += FunctionParserUtils<false>::validParams();

  params.addRequiredParam<MeshGeneratorName>("input", "The input mesh that needs to be trimmed.");
  params.addParam<MooseEnum>(
      "cut_interface",
      MooseEnum(getCutInterfaceElementOptions(), "TETRAHEDRA"),
      "Which type of element to use at the interface between elements and the cut");

  params.addParam<bool>(
      "generate_transition_layer",
      false,
      "Whether to generate a transition layer for the cut mesh. "
      "If false, the entire input mesh will be converted to TET4 elements to facilitate the "
      "cutting; if true, only the elements near the cut face will be converted with a transition "
      "layer to maintain compatibility with the original mesh. This only used for cut_interface = "
      "'tetrahedra'");

  params.addParam<boundary_id_type>("cut_face_id",
                                    "The boundary id of the face generated by the cut. An "
                                    "id will be automatically assigned if not provided.");
  params.addParam<BoundaryName>(
      "cut_face_name", BoundaryName(), "The boundary name of the face generated by the cut.");
  params.addParam<SubdomainName>("converted_tet_element_subdomain_name_suffix",
                                 "to_tet",
                                 "The suffix to be added to the original subdomain name for the "
                                 "subdomains containing the elements converted to TET4. This is "
                                 "only applicable when transition layer is generated.");
  params.addParam<SubdomainName>(
      "converted_pyramid_element_subdomain_name_suffix",
      "to_pyramid",
      "The suffix to be added to the original subdomain name for the subdomains containing the "
      "elements converted to PYRAMID5. This is only applicable when transition layer is "
      "generated.");
  params.addParam<SubdomainName>(
      "converted_poly_element_subdomain_name_suffix",
      "to_polyhedra",
      "The suffix to be added to the original subdomain name for the subdomains containing the "
      "elements converted to C0POLYHEDRON.");

  params.addClassDescription(
      "This CutMeshByLevelSetGeneratorBase object is designed to be the base class of mesh "
      "generator that cuts a 3D mesh based on an analytic level set function. The level set "
      "function could be provided explicitly or indirectly.");

  return params;
}

CutMeshByLevelSetGeneratorBase::CutMeshByLevelSetGeneratorBase(const InputParameters & parameters)
  : MeshGenerator(parameters),
    FunctionParserUtils<false>(parameters),
    _input_name(getParam<MeshGeneratorName>("input")),
    _cut_interface(getParam<MooseEnum>("cut_interface").getEnum<CutInterfaceElement>()),
    _generate_transition_layer(getParam<bool>("generate_transition_layer")),
    _cut_face_name(getParam<BoundaryName>("cut_face_name")),
    _converted_tet_element_subdomain_name_suffix(
        getParam<SubdomainName>("converted_tet_element_subdomain_name_suffix")),
    _converted_pyramid_element_subdomain_name_suffix(
        getParam<SubdomainName>("converted_pyramid_element_subdomain_name_suffix")),
    _converted_poly_element_subdomain_name_suffix(
        getParam<SubdomainName>("converted_poly_element_subdomain_name_suffix")),
    _input(getMeshByName(_input_name))
{
  _cut_face_id = isParamValid("cut_face_id") ? getParam<boundary_id_type>("cut_face_id") : -1;

  if (_cut_interface == CutInterfaceElement::TETRAHEDRA &&
      isParamSetByUser("converted_poly_element_subdomain_name_suffix"))
    paramError("converted_poly_element_subdomain_name_suffix",
               "No polyhedra element generated when using tetrahedra at the cutting interface");
  else if (_cut_interface == CutInterfaceElement::POLYHEDRA)
  {
    if (isParamSetByUser("converted_tet_element_subdomain_name_suffix"))
      paramError("converted_tet_element_subdomain_name_suffix",
                 "No tetrahedra element generated when using polyhedra at the cutting interface");
    if (isParamSetByUser("converted_pyramid_element_subdomain_name_suffix"))
      paramError("converted_pyramid_element_subdomain_name_suffix",
                 "No pyramid element generated when using polyhedra at the cutting interface");
  }
}

std::unique_ptr<MeshBase>
CutMeshByLevelSetGeneratorBase::generate()
{
  // We're querying elem dim caches from our input mesh
  if (!_input->preparation().has_cached_elem_data)
    _input->cache_elem_data();

  auto replicated_mesh_ptr = dynamic_cast<ReplicatedMesh *>(_input.get());
  if (!replicated_mesh_ptr)
    paramError("input", "Input is not a replicated mesh, which is required");
  if (*(replicated_mesh_ptr->elem_dimensions().begin()) != 3 ||
      *(replicated_mesh_ptr->elem_dimensions().rbegin()) != 3)
    paramError(
        "input",
        "Only 3D meshes are supported. Use XYMeshLineCutter for 2D meshes if applicable. Mixed "
        "dimensional meshes are not supported at the moment.");
  ReplicatedMesh & mesh = *replicated_mesh_ptr;

  if (!_cut_face_name.empty())
  {
    if (MooseMeshUtils::hasBoundaryNameOrID(mesh, _cut_face_name))
    {
      const boundary_id_type exist_cut_face_id =
          MooseMeshUtils::getBoundaryID(_cut_face_name, mesh);
      if (_cut_face_id != -1 && _cut_face_id != exist_cut_face_id)
        paramError("cut_face_id",
                   "The cut face boundary name and id are both provided, but they are inconsistent "
                   "with an existing boundary name which has a different id.");
      else
        _cut_face_id = exist_cut_face_id;
    }
    else
    {
      if (_cut_face_id == -1)
        _cut_face_id = MooseMeshUtils::getNextFreeBoundaryID(mesh);
      mesh.get_boundary_info().sideset_name(_cut_face_id) = _cut_face_name;
    }
  }
  else if (_cut_face_id == -1)
  {
    _cut_face_id = MooseMeshUtils::getNextFreeBoundaryID(mesh);
  }

  if (_cut_interface == CutInterfaceElement::TETRAHEDRA)
    generateCutWithTetrahedra();
  else
    generateCutWithPolyhedra();

  // Delete the elements marked for removal
  for (auto elem_it = mesh.active_subdomain_elements_begin(_block_id_to_remove);
       elem_it != mesh.active_subdomain_elements_end(_block_id_to_remove);
       elem_it++)
    mesh.delete_elem(*elem_it);

  mesh.contract();
  mesh.unset_is_prepared();

  return std::move(_input);
}

void
CutMeshByLevelSetGeneratorBase::generateCutWithTetrahedra()
{
  auto replicated_mesh_ptr = dynamic_cast<ReplicatedMesh *>(_input.get());
  ReplicatedMesh & mesh = *replicated_mesh_ptr;

  // Subdomain ID for new utility blocks must be new
  // Find sid shifts
  const auto sid_shift_base = MooseMeshUtils::getNextFreeSubdomainID(mesh);
  _block_id_to_remove = sid_shift_base * 3;

  // For the boolean value in the pair, true means the element is crossed by the cutting plane
  // false means the element is on the remaining side
  std::vector<std::pair<dof_id_type, bool>> cross_and_remained_elems_pre_convert;

  // collect the subdomain ids of the original mesh
  std::set<subdomain_id_type> original_subdomain_ids;
  for (auto elem_it = mesh.active_elements_begin(); elem_it != mesh.active_elements_end();
       elem_it++)
  {
    original_subdomain_ids.emplace((*elem_it)->subdomain_id());
    const unsigned int & n_vertices = (*elem_it)->n_vertices();
    unsigned short elem_vertices_counter(0);
    for (unsigned int i = 0; i < n_vertices; i++)
    {
      // We define elem_vertices_counter in this way so that those elements with one face on the
      // plane are also processed to have the cut face boundary assigned.
      if (pointLevelSetRelation((*(*elem_it)->node_ptr(i))) !=
          PointLevelSetRelationIndex::level_set_in_side)
        elem_vertices_counter++;
    }
    if (elem_vertices_counter == n_vertices)
      (*elem_it)->subdomain_id() = _block_id_to_remove;
    else
    {
      // Check if any elements to be processed are not first order
      if ((*elem_it)->default_order() != Order::FIRST)
        mooseError("Only first order elements are supported for cutting.");
      // If we are generating a transition layer, we only need to record the crossed elements
      if (_generate_transition_layer && elem_vertices_counter > 0)
      {
        cross_and_remained_elems_pre_convert.push_back(std::make_pair((*elem_it)->id(), true));
        // Since we are converting these elements to TET4, and we would keep the original type of
        // some elements in these blocks
        if ((*elem_it)->type() != TET4)
          (*elem_it)->subdomain_id() += sid_shift_base;
      }
      else if (!_generate_transition_layer)
        cross_and_remained_elems_pre_convert.push_back(
            std::make_pair((*elem_it)->id(), elem_vertices_counter > 0));
    }
  }

  // Then we need to identify and make the transition layer
  std::vector<dof_id_type> transition_elems_list;
  std::vector<std::vector<unsigned int>> transition_elems_sides_list;
  if (_generate_transition_layer)
  {
    if (!mesh.is_prepared())
      mesh.find_neighbors();
    // First, we need to identify the retained elements that share the boundary with the crossed
    // elements.
    for (const auto & elem_info : cross_and_remained_elems_pre_convert)
    {
      for (const auto & i_side : make_range(mesh.elem_ptr(elem_info.first)->n_sides()))
      {
        // No need to work on a TRI3 side
        if (mesh.elem_ptr(elem_info.first)->side_ptr(i_side)->type() == QUAD4)
        {
          if (mesh.elem_ptr(elem_info.first)->neighbor_ptr(i_side) != nullptr &&
              mesh.elem_ptr(elem_info.first)->neighbor_ptr(i_side)->subdomain_id() !=
                  _block_id_to_remove &&
              std::find(cross_and_remained_elems_pre_convert.begin(),
                        cross_and_remained_elems_pre_convert.end(),
                        std::make_pair(mesh.elem_ptr(elem_info.first)->neighbor_ptr(i_side)->id(),
                                       true)) == cross_and_remained_elems_pre_convert.end())
          {
            const auto & neighbor_elem_id =
                mesh.elem_ptr(elem_info.first)->neighbor_ptr(i_side)->id();
            const auto & neighbor_elem_side_index =
                mesh.elem_ptr(elem_info.first)
                    ->neighbor_ptr(i_side)
                    ->which_neighbor_am_i(mesh.elem_ptr(elem_info.first));
            const auto & id_found = std::find(
                transition_elems_list.begin(), transition_elems_list.end(), neighbor_elem_id);
            if (id_found == transition_elems_list.end())
            {
              transition_elems_list.push_back(neighbor_elem_id);
              transition_elems_sides_list.push_back(
                  std::vector<unsigned int>({neighbor_elem_side_index}));
            }
            else
            {
              // If the element is already in the list, we just add the side index
              const auto index = std::distance(transition_elems_list.begin(), id_found);
              transition_elems_sides_list[index].push_back(neighbor_elem_side_index);
            }
          }
        }
      }
    }
  }

  std::vector<dof_id_type> converted_elems_ids_to_cut;
  // Then convert these non-TET4 elements into TET4 elements
  MooseMeshElementConversionUtils::convert3DMeshToAllTet4(mesh,
                                                          cross_and_remained_elems_pre_convert,
                                                          converted_elems_ids_to_cut,
                                                          _block_id_to_remove,
                                                          false);

  // Make the transition layer if applicable
  auto & sideset_map = mesh.get_boundary_info().get_sideset_map();
  for (const auto & i_elem : index_range(transition_elems_list))
  {
    const auto & elem_id = transition_elems_list[i_elem];
    const auto & side_indices = transition_elems_sides_list[i_elem];
    // Find the involved sidesets of the element so that we can retain them
    std::vector<std::vector<boundary_id_type>> elem_side_info(mesh.elem_ptr(elem_id)->n_sides());
    auto side_range = sideset_map.equal_range(mesh.elem_ptr(elem_id));
    for (auto i = side_range.first; i != side_range.second; ++i)
      elem_side_info[i->second.first].push_back(i->second.second);

    MooseMeshElementConversionUtils::convertElem(
        mesh, elem_id, side_indices, elem_side_info, sid_shift_base);
  }

  std::vector<const Node *> new_on_plane_nodes;
  // We build the sideset information now, as we only need the information of the elements before
  // cutting
  BoundaryInfo & boundary_info = mesh.get_boundary_info();
  const auto bdry_side_list = boundary_info.build_side_list();
  // Cut the TET4 Elements
  for (const auto & converted_elems_id_to_cut : converted_elems_ids_to_cut)
  {
    tet4ElemCutter(mesh, bdry_side_list, converted_elems_id_to_cut, new_on_plane_nodes);
  }

  // If a transition layer is generated, we need to add some subdomain names
  if (_generate_transition_layer)
  {
    try
    {
      MooseMeshElementConversionUtils::assignConvertedElementsSubdomainNameSuffix(
          mesh,
          original_subdomain_ids,
          sid_shift_base,
          _converted_tet_element_subdomain_name_suffix,
          _converted_pyramid_element_subdomain_name_suffix);
    }
    catch (const std::exception & e)
    {
      if (((std::string)e.what()).compare(26, 4, "TET4") == 0)
        paramError("converted_tet_element_subdomain_name_suffix", e.what());
      else // if (((std::string)e.what()).compare(26, 7, "PYRAMID5") == 0)
        paramError("converted_pyramid_element_subdomain_name_suffix", e.what());
    }
  }

  // mark the original elements replaced by transition elements for deletion
  for (const auto & elem_id : transition_elems_list)
    mesh.elem_ptr(elem_id)->subdomain_id() = _block_id_to_remove;
}

void
CutMeshByLevelSetGeneratorBase::generateCutWithPolyhedra()
{
  auto replicated_mesh_ptr = dynamic_cast<ReplicatedMesh *>(_input.get());
  ReplicatedMesh & mesh = *replicated_mesh_ptr;

  // Subdomain IDs for new utility blocks must be new.
  // - Polyhedron-converted elements get their subdomain id shifted by sid_shift_base so the
  //   shifted subdomain can be renamed via _converted_poly_element_subdomain_name_suffix.
  // - Original elements that are fully outside (or whose retained side is just a face on the
  //   cut) are moved to _block_id_to_remove for later deletion.
  const auto sid_shift_base = MooseMeshUtils::getNextFreeSubdomainID(mesh);
  _block_id_to_remove = sid_shift_base * 2;

  // First pass: classify each active element
  std::set<subdomain_id_type> original_subdomain_ids;
  std::vector<dof_id_type> elems_to_cut;
  BoundaryInfo & boundary_info = mesh.get_boundary_info();
  for (auto elem_it = mesh.active_elements_begin(); elem_it != mesh.active_elements_end();
       elem_it++)
  {
    Elem * elem = *elem_it;
    original_subdomain_ids.emplace(elem->subdomain_id());

    const unsigned int n_vertices = elem->n_vertices();
    unsigned int n_in = 0;
    unsigned int n_out = 0;
    for (unsigned int i = 0; i < n_vertices; i++)
    {
      const auto rel = pointLevelSetRelation(*(elem->node_ptr(i)));
      if (rel == PointLevelSetRelationIndex::level_set_in_side)
        n_in++;
      else if (rel == PointLevelSetRelationIndex::level_set_out_side)
        n_out++;
    }

    if (n_in == 0)
    {
      // The element has no volume strictly on the retained side -> remove it. If it happens
      // to share a face flush with the cut, the neighbor on the retained side will handle
      // assigning _cut_face_id on its matching face.
      elem->subdomain_id() = _block_id_to_remove;
    }
    else if (n_out == 0)
    {
      // Element is entirely retained as-is. Any face whose nodes are all on the level set is
      // by definition the cut face for this element -> assign _cut_face_id to it.
      for (const auto s : make_range(elem->n_sides()))
      {
        auto side = elem->side_ptr(s);
        bool all_on = true;
        for (const auto n : make_range(side->n_nodes()))
          if (pointLevelSetRelation(*(side->node_ptr(n))) !=
              PointLevelSetRelationIndex::on_level_set)
          {
            all_on = false;
            break;
          }
        if (all_on)
          boundary_info.add_side(elem, s, _cut_face_id);
      }
    }
    else
    {
      // Mixed: this element will be cut into a polyhedron
      if (elem->default_order() != Order::FIRST)
        mooseError("Only first order elements are supported for cutting.");
      elems_to_cut.push_back(elem->id());
    }
  }

  // Second pass: build a polyhedron for each cut element. Nodes created on the cutting surface
  // are deduplicated across elements so shared edges produce a single node.
  std::vector<const Node *> new_on_plane_nodes;
  const auto bdry_side_list = boundary_info.build_side_list();
  for (const auto & elem_id : elems_to_cut)
    polyhedronElemCutter(mesh, bdry_side_list, elem_id, sid_shift_base, new_on_plane_nodes);

  // Rename shifted subdomains so polyhedron-converted blocks are identifiable
  for (const auto & subdomain_id : original_subdomain_ids)
  {
    const subdomain_id_type new_sid = subdomain_id + sid_shift_base;
    if (!MooseMeshUtils::hasSubdomainID(mesh, new_sid))
      continue;
    const SubdomainName new_name =
        (mesh.subdomain_name(subdomain_id).empty() ? std::to_string(subdomain_id)
                                                   : mesh.subdomain_name(subdomain_id)) +
        '_' + _converted_poly_element_subdomain_name_suffix;
    if (MooseMeshUtils::hasSubdomainName(mesh, new_name))
      paramError("converted_poly_element_subdomain_name_suffix",
                 "This suffix for converted C0POLYHEDRON elements results in a subdomain name, " +
                     new_name +
                     ", that already exists in the mesh. Please choose a different "
                     "suffix.");
    mesh.subdomain_name(new_sid) = new_name;
  }
}

void
CutMeshByLevelSetGeneratorBase::polyhedronElemCutter(
    ReplicatedMesh & mesh,
    const std::vector<libMesh::BoundaryInfo::BCTuple> & bdry_side_list,
    const dof_id_type elem_id,
    const subdomain_id_type sid_shift_base,
    std::vector<const Node *> & new_on_plane_nodes)
{
  Elem * orig_elem = mesh.elem_ptr(elem_id);
  const unsigned int n_orig_sides = orig_elem->n_sides();

  // Collect boundary ids on each side of the original element so we can re-attach them to
  // the matching sides of the new polyhedron.
  std::vector<std::vector<boundary_id_type>> elem_side_list;
  MooseMeshElementConversionUtils::elementBoundaryInfoCollector(
      bdry_side_list, elem_id, n_orig_sides, elem_side_list);

  // Polygon sides of the new polyhedron, plus an index back into elem_side_list. The index -1
  // marks the new face that lies on the cut surface (it inherits _cut_face_id).
  std::vector<std::shared_ptr<libMesh::Polygon>> new_polygons;
  std::vector<int> new_polygon_to_orig_side;

  // Each face that is genuinely cut contributes a directed cut edge to the new cut face. We
  // collect them here and chain them into a closed polygon below.
  std::vector<std::pair<const Node *, const Node *>> cut_edges;

  for (const auto face_i : make_range(n_orig_sides))
  {
    auto side_ptr = orig_elem->side_ptr(face_i);
    const unsigned int n_face_nodes = side_ptr->n_nodes();

    // Classify each face node with respect to the level set
    std::vector<PointLevelSetRelationIndex> rels(n_face_nodes);
    unsigned int n_in = 0, n_out = 0, n_on = 0;
    for (const auto n : make_range(n_face_nodes))
    {
      rels[n] = pointLevelSetRelation(*(side_ptr->node_ptr(n)));
      if (rels[n] == PointLevelSetRelationIndex::level_set_in_side)
        n_in++;
      else if (rels[n] == PointLevelSetRelationIndex::level_set_out_side)
        n_out++;
      else
        n_on++;
    }

    // Face is entirely outside (no retained or on-cut node): drop it.
    if (n_in == 0 && n_on == 0)
      continue;

    // Face is entirely on the level set: it becomes (part of) the new cut face. This only
    // happens when an element is cut while having an entire face exactly on the level set.
    if (n_in == 0 && n_out == 0)
    {
      auto polygon = std::make_shared<libMesh::C0Polygon>(n_face_nodes);
      for (const auto i : make_range(n_face_nodes))
        polygon->set_node(i, const_cast<Node *>(side_ptr->node_ptr(i)));
      new_polygons.push_back(polygon);
      new_polygon_to_orig_side.push_back(-1);
      continue;
    }

    // Face is entirely retained (no out nodes): copy it as-is.
    if (n_out == 0)
    {
      auto polygon = std::make_shared<libMesh::C0Polygon>(n_face_nodes);
      for (const auto i : make_range(n_face_nodes))
        polygon->set_node(i, const_cast<Node *>(side_ptr->node_ptr(i)));
      new_polygons.push_back(polygon);
      new_polygon_to_orig_side.push_back(static_cast<int>(face_i));
      continue;
    }

    // Mixed face: clip it against the "retained" half-space using a Sutherland-Hodgman-style
    // walk. While walking we also record the entry/exit cut vertices so we can later
    // assemble them into the cut face.
    std::vector<const Node *> new_face_nodes;
    const Node * cut_entry = nullptr; // crossing out of the retained side
    const Node * cut_exit = nullptr;  // crossing back into the retained side

    unsigned int prev_idx = n_face_nodes - 1;
    bool prev_retained = (rels[prev_idx] != PointLevelSetRelationIndex::level_set_out_side);

    for (const auto curr_idx : make_range(n_face_nodes))
    {
      const Node * curr_node = side_ptr->node_ptr(curr_idx);
      const bool curr_retained = (rels[curr_idx] != PointLevelSetRelationIndex::level_set_out_side);

      if (prev_retained && curr_retained)
      {
        new_face_nodes.push_back(curr_node);
      }
      else if (prev_retained && !curr_retained)
      {
        const Node * prev_node = side_ptr->node_ptr(prev_idx);
        if (rels[prev_idx] == PointLevelSetRelationIndex::on_level_set)
        {
          // prev_node is already on the level set - it was added in the previous iteration
          // and is itself the cut entry point.
          cut_entry = prev_node;
        }
        else
        {
          const Point cross_pt = pointPairLevelSetInterception(*prev_node, *curr_node);
          const Node * cross_node = nonDuplicateNodeCreator(mesh, new_on_plane_nodes, cross_pt);
          new_face_nodes.push_back(cross_node);
          cut_entry = cross_node;
        }
      }
      else if (!prev_retained && curr_retained)
      {
        const Node * prev_node = side_ptr->node_ptr(prev_idx);
        if (rels[curr_idx] == PointLevelSetRelationIndex::on_level_set)
        {
          new_face_nodes.push_back(curr_node);
          cut_exit = curr_node;
        }
        else
        {
          const Point cross_pt = pointPairLevelSetInterception(*prev_node, *curr_node);
          const Node * cross_node = nonDuplicateNodeCreator(mesh, new_on_plane_nodes, cross_pt);
          new_face_nodes.push_back(cross_node);
          new_face_nodes.push_back(curr_node);
          cut_exit = cross_node;
        }
      }
      // else: both outside, drop this edge

      prev_idx = curr_idx;
      prev_retained = curr_retained;
    }

    // Three or more retained vertices yield a valid clipped face. The size-2 case (a single
    // edge shared with the cut, e.g. the face touches the cut along one of its edges) does
    // not contribute a 2D face to the retained polyhedron but still contributes a cut edge.
    if (new_face_nodes.size() >= 3)
    {
      auto polygon = std::make_shared<libMesh::C0Polygon>(new_face_nodes.size());
      for (const auto i : index_range(new_face_nodes))
        polygon->set_node(i, const_cast<Node *>(new_face_nodes[i]));
      new_polygons.push_back(polygon);
      new_polygon_to_orig_side.push_back(static_cast<int>(face_i));
    }

    if (cut_entry && cut_exit && cut_entry != cut_exit)
      cut_edges.push_back(std::make_pair(cut_entry, cut_exit));
  }

  // Chain the per-face cut edges into a single closed polygon for the new cut face. Each face
  // contributes one directed edge but neighbouring faces may walk in opposite directions, so
  // we accept either orientation at each step.
  if (!cut_edges.empty())
  {
    if (cut_edges.size() < 3)
      mooseError("Cut face for element ",
                 elem_id,
                 " has fewer than 3 vertices; the cut geometry is degenerate.");

    std::vector<const Node *> cut_face_nodes;
    std::vector<bool> used(cut_edges.size(), false);
    cut_face_nodes.push_back(cut_edges[0].first);
    cut_face_nodes.push_back(cut_edges[0].second);
    used[0] = true;

    while (cut_face_nodes.size() < cut_edges.size())
    {
      const Node * tail = cut_face_nodes.back();
      bool found_next = false;
      for (const auto j : index_range(cut_edges))
      {
        if (used[j])
          continue;
        if (cut_edges[j].first == tail)
        {
          cut_face_nodes.push_back(cut_edges[j].second);
          used[j] = true;
          found_next = true;
          break;
        }
        if (cut_edges[j].second == tail)
        {
          cut_face_nodes.push_back(cut_edges[j].first);
          used[j] = true;
          found_next = true;
          break;
        }
      }
      if (!found_next)
        mooseError("Unable to chain cut face edges into a closed polygon for element ", elem_id);
    }

    // The cut polygon is planar when the level set is locally planar inside the element, but
    // for curved level sets (e.g. spheres, cylinders away from their axis) the chained
    // vertices generally are not coplanar. libMesh's C0Polyhedron requires every face to be
    // planar (in debug it asserts this and refuses to build the element), so detect the
    // non-planar case and triangulate the cut face into a fan of planar triangles around a
    // Steiner point projected onto the level set.
    bool cut_face_planar = (cut_face_nodes.size() <= 3);
    if (cut_face_nodes.size() > 3)
    {
      const Point p0 = static_cast<Point>(*cut_face_nodes[0]);
      const Point p1 = static_cast<Point>(*cut_face_nodes[1]);
      const Point p_last = static_cast<Point>(*cut_face_nodes.back());
      const Point n_i = (p1 - p0).cross(p0 - p_last).unit();
      cut_face_planar = true;
      for (std::size_t k = 2; k + 1 < cut_face_nodes.size(); ++k)
      {
        const Point d_n = static_cast<Point>(*cut_face_nodes[k]) - p0;
        if (std::abs(d_n * n_i) > libMesh::TOLERANCE * d_n.norm())
        {
          cut_face_planar = false;
          break;
        }
      }
    }

    if (cut_face_planar)
    {
      Moose::out << "elem " << elem_id << " PLANAR size=" << cut_face_nodes.size() << std::endl;
      auto cut_polygon = std::make_shared<libMesh::C0Polygon>(cut_face_nodes.size());
      for (const auto i : index_range(cut_face_nodes))
        cut_polygon->set_node(i, const_cast<Node *>(cut_face_nodes[i]));
      new_polygons.push_back(cut_polygon);
      new_polygon_to_orig_side.push_back(-1);
    }
    else
    {
      Moose::out << "elem " << elem_id << " NONPLANAR size=" << cut_face_nodes.size() << std::endl;
      // Steiner point: the linear average of the chained cut vertices, then projected onto
      // the level set by bisecting toward a vertex of the original element that sits on the
      // opposite side of the level set.
      Point center_lin(0, 0, 0);
      for (const auto * n : cut_face_nodes)
        center_lin += static_cast<Point>(*n);
      center_lin /= static_cast<Real>(cut_face_nodes.size());

      Point center_on_ls = center_lin;
      const Real center_val = levelSetEvaluator(center_lin);
      if (!MooseUtils::absoluteFuzzyEqual(center_val, 0.0))
      {
        const Node * ref = nullptr;
        const auto target = (center_val < 0) ? PointLevelSetRelationIndex::level_set_out_side
                                             : PointLevelSetRelationIndex::level_set_in_side;
        for (const auto i : make_range(orig_elem->n_nodes()))
          if (pointLevelSetRelation(*(orig_elem->node_ptr(i))) == target)
          {
            ref = orig_elem->node_ptr(i);
            break;
          }
        if (!ref)
          mooseError("Cannot project the cut face center onto the level set for element ", elem_id);
        center_on_ls = pointPairLevelSetInterception(center_lin, *ref);
      }

      const Node * steiner = nonDuplicateNodeCreator(mesh, new_on_plane_nodes, center_on_ls);
      for (const auto i : index_range(cut_face_nodes))
      {
        const auto j = (i + 1) % cut_face_nodes.size();
        auto tri = std::make_shared<libMesh::C0Polygon>(3);
        tri->set_node(0, const_cast<Node *>(steiner));
        tri->set_node(1, const_cast<Node *>(cut_face_nodes[i]));
        tri->set_node(2, const_cast<Node *>(cut_face_nodes[j]));
        new_polygons.push_back(tri);
        new_polygon_to_orig_side.push_back(-1);
      }
    }
  }

  if (new_polygons.size() < 4)
    mooseError("Polyhedron from cutting element ",
               elem_id,
               " has fewer than 4 faces; the cut geometry is degenerate.");

  // Build the polyhedron. The C0Polyhedron constructor may need a mid-element node if it
  // can't tetrahedralize from the boundary alone; if so, we have to add that node to the mesh.
  // The constructor will throw libMesh::NotImplemented (in debug) when the retained region is
  // fundamentally non-convex (e.g. a cell whose retained side carries a spherical dimple),
  // since libMesh's polyhedron representation requires convex polyhedra. Translate that into a
  // MOOSE-level error that points the user at the actual cause.
  std::unique_ptr<Node> mid_elem_node;
  std::unique_ptr<libMesh::C0Polyhedron> polyhedron;
  try
  {
    polyhedron = std::make_unique<libMesh::C0Polyhedron>(new_polygons, mid_elem_node);
  }
  catch (const libMesh::NotImplemented &)
  {
    mooseError(
        "Element ",
        elem_id,
        " produces a non-convex polyhedron after cutting. C0POLYHEDRON elements must be convex, "
        "so this cut cannot be represented with cut_interface = polyhedra. This typically "
        "happens when the retained side of the level set has concave geometry within an element "
        "(e.g. retaining the outside of a sphere). Either retain the convex side of the level "
        "set, refine the mesh enough that each cell's retained geometry is convex, or switch to "
        "cut_interface = tetrahedra.");
  }
  polyhedron->subdomain_id() = orig_elem->subdomain_id() + sid_shift_base;
  Elem * new_elem = mesh.add_elem(std::move(polyhedron));
  if (mid_elem_node)
    mesh.add_node(std::move(mid_elem_node));

  // Re-attach boundary ids: each new polygon either matches an original side (inheriting its
  // boundary ids) or is the new cut face (gets _cut_face_id).
  BoundaryInfo & boundary_info = mesh.get_boundary_info();
  for (const auto new_side_i : index_range(new_polygons))
  {
    const int orig_side = new_polygon_to_orig_side[new_side_i];
    if (orig_side < 0)
      boundary_info.add_side(new_elem, new_side_i, _cut_face_id);
    else
      for (const auto & bdry_id : elem_side_list[orig_side])
        boundary_info.add_side(new_elem, new_side_i, bdry_id);
  }

  // Mark the original element for deletion in the cleanup pass
  orig_elem->subdomain_id() = _block_id_to_remove;
}

CutMeshByLevelSetGeneratorBase::PointLevelSetRelationIndex
CutMeshByLevelSetGeneratorBase::pointLevelSetRelation(const Point & point)
{
  const Real level_set_value = levelSetEvaluator(point);
  if (MooseUtils::absoluteFuzzyLessThan(level_set_value, 0.0))
    return PointLevelSetRelationIndex::level_set_in_side;
  else if (MooseUtils::absoluteFuzzyGreaterThan(level_set_value, 0.0))
    return PointLevelSetRelationIndex::level_set_out_side;
  else
    return PointLevelSetRelationIndex::on_level_set;
}

Point
CutMeshByLevelSetGeneratorBase::pointPairLevelSetInterception(const Point & point1,
                                                              const Point & point2)
{
  Real dist1 = levelSetEvaluator(point1);
  Real dist2 = levelSetEvaluator(point2);

  if (MooseUtils::absoluteFuzzyEqual(dist1, 0.0) || MooseUtils::absoluteFuzzyEqual(dist2, 0.0))
    mooseError("At least one of the two points are on the plane.");
  if (MooseUtils::absoluteFuzzyGreaterThan(dist1 * dist2, 0.0))
    mooseError("The two points are on the same side of the plane.");

  Point p1(point1);
  Point p2(point2);
  Real dist = abs(dist1) + abs(dist2);
  Point mid_point;

  // Bisection method to find midpoint
  while (MooseUtils::absoluteFuzzyGreaterThan(dist, 0.0))
  {
    mid_point = 0.5 * (p1 + p2);
    const Real dist_mid = levelSetEvaluator(mid_point);
    // We do not need Fuzzy here as it will be covered by the while loop
    if (dist_mid == 0.0)
      dist = 0.0;
    else if (dist_mid * dist1 < 0.0)
    {
      p2 = mid_point;
      dist2 = levelSetEvaluator(p2);
      dist = abs(dist1) + abs(dist2);
    }
    else
    {
      p1 = mid_point;
      dist1 = levelSetEvaluator(p1);
      dist = abs(dist1) + abs(dist2);
    }
  }
  return mid_point;
}

const Node *
CutMeshByLevelSetGeneratorBase::nonDuplicateNodeCreator(
    ReplicatedMesh & mesh,
    std::vector<const Node *> & new_on_plane_nodes,
    const Point & new_point) const
{
  for (const auto & new_on_plane_node : new_on_plane_nodes)
  {
    if (MooseUtils::absoluteFuzzyEqual((*new_on_plane_node - new_point).norm(), 0.0))
      return new_on_plane_node;
  }
  new_on_plane_nodes.push_back(mesh.add_point(new_point));
  return new_on_plane_nodes.back();
}

void
CutMeshByLevelSetGeneratorBase::tet4ElemCutter(
    ReplicatedMesh & mesh,
    const std::vector<libMesh::BoundaryInfo::BCTuple> & bdry_side_list,
    const dof_id_type elem_id,
    std::vector<const Node *> & new_on_plane_nodes)
{
  // Retrieve boundary information for the mesh
  BoundaryInfo & boundary_info = mesh.get_boundary_info();
  // Create a list of sidesets involving the element to be split
  // It might be complex to assign the boundary id to the new elements
  // In TET4, none of the four faces have the same normal vector
  // So we are using the normal vector to identify the faces that
  // need to be assigned the same boundary id
  std::vector<Point> elem_side_normal_list;
  elem_side_normal_list.resize(4);
  for (const auto i : make_range(4))
  {
    auto elem_side = mesh.elem_ptr(elem_id)->side_ptr(i);
    elem_side_normal_list[i] = (*elem_side->node_ptr(1) - *elem_side->node_ptr(0))
                                   .cross(*elem_side->node_ptr(2) - *elem_side->node_ptr(1))
                                   .unit();
  }

  std::vector<std::vector<boundary_id_type>> elem_side_list;
  MooseMeshElementConversionUtils::elementBoundaryInfoCollector(
      bdry_side_list, elem_id, 4, elem_side_list);

  std::vector<PointLevelSetRelationIndex> node_plane_relation(4);
  std::vector<const Node *> tet4_nodes(4);
  std::vector<const Node *> tet4_nodes_on_plane;
  std::vector<const Node *> tet4_nodes_outside_plane;
  std::vector<const Node *> tet4_nodes_inside_plane;
  // Sort tetrahedral nodes based on their positioning wrt the plane
  for (unsigned int i = 0; i < 4; i++)
  {
    tet4_nodes[i] = mesh.elem_ptr(elem_id)->node_ptr(i);
    node_plane_relation[i] = pointLevelSetRelation(*tet4_nodes[i]);
    if (node_plane_relation[i] == PointLevelSetRelationIndex::on_level_set)
      tet4_nodes_on_plane.push_back(tet4_nodes[i]);
    else if (node_plane_relation[i] == PointLevelSetRelationIndex::level_set_out_side)
      tet4_nodes_outside_plane.push_back(tet4_nodes[i]);
    else
      tet4_nodes_inside_plane.push_back(tet4_nodes[i]);
  }
  std::vector<Elem *> elems_tet4;
  bool new_elements_created(false);
  // No cutting needed if no nodes are outside the plane
  if (tet4_nodes_outside_plane.size() == 0)
  {
    if (tet4_nodes_on_plane.size() == 3)
    {
      // Record the element for future cross section boundary assignment
      elems_tet4.push_back(mesh.elem_ptr(elem_id));
    }
  }
  // Remove the element if all the nodes are outside the plane
  else if (tet4_nodes_inside_plane.size() == 0)
  {
    mesh.elem_ptr(elem_id)->subdomain_id() = _block_id_to_remove;
    if (tet4_nodes_on_plane.size() == 3)
    {
      // I think the neighboring element will be handled,
      // So we do not need to assign the cross section boundary here
    }
  }
  // As we have nodes on both sides, six different scenarios are possible
  else
  {
    new_elements_created = true;
    if (tet4_nodes_inside_plane.size() == 1 && tet4_nodes_outside_plane.size() == 3)
    {
      std::vector<const Node *> new_plane_nodes;
      // A smaller TET4 element is created, this solution is unique
      for (const auto & tet4_node_outside_plane : tet4_nodes_outside_plane)
      {
        new_plane_nodes.push_back(nonDuplicateNodeCreator(
            mesh,
            new_on_plane_nodes,
            pointPairLevelSetInterception(*tet4_node_outside_plane, *tet4_nodes_inside_plane[0])));
      }
      auto new_elem_tet4 = std::make_unique<Tet4>();
      new_elem_tet4->set_node(0, const_cast<Node *>(tet4_nodes_inside_plane[0]));
      new_elem_tet4->set_node(1, const_cast<Node *>(new_plane_nodes[0]));
      new_elem_tet4->set_node(2, const_cast<Node *>(new_plane_nodes[1]));
      new_elem_tet4->set_node(3, const_cast<Node *>(new_plane_nodes[2]));
      new_elem_tet4->subdomain_id() = mesh.elem_ptr(elem_id)->subdomain_id();
      elems_tet4.push_back(mesh.add_elem(std::move(new_elem_tet4)));
    }
    else if (tet4_nodes_inside_plane.size() == 2 && tet4_nodes_outside_plane.size() == 2)
    {
      std::vector<const Node *> new_plane_nodes;
      // 3 smaller TET3 elements are created
      for (const auto & tet4_node_outside_plane : tet4_nodes_outside_plane)
      {
        for (const auto & tet4_node_inside_plane : tet4_nodes_inside_plane)
        {
          new_plane_nodes.push_back(nonDuplicateNodeCreator(
              mesh,
              new_on_plane_nodes,
              pointPairLevelSetInterception(*tet4_node_outside_plane, *tet4_node_inside_plane)));
        }
      }
      std::vector<const Node *> new_elems_nodes = {tet4_nodes_inside_plane[1],
                                                   new_plane_nodes[3],
                                                   new_plane_nodes[1],
                                                   tet4_nodes_inside_plane[0],
                                                   new_plane_nodes[2],
                                                   new_plane_nodes[0]};
      std::vector<std::vector<unsigned int>> rotated_tet_face_indices;
      std::vector<std::vector<const Node *>> optimized_node_list;
      MooseMeshElementConversionUtils::prismNodesToTetNodesDeterminer(
          new_elems_nodes, rotated_tet_face_indices, optimized_node_list);

      for (unsigned int i = 0; i < optimized_node_list.size(); i++)
      {
        auto new_elem_tet4 = std::make_unique<Tet4>();
        new_elem_tet4->set_node(0, const_cast<Node *>(optimized_node_list[i][0]));
        new_elem_tet4->set_node(1, const_cast<Node *>(optimized_node_list[i][1]));
        new_elem_tet4->set_node(2, const_cast<Node *>(optimized_node_list[i][2]));
        new_elem_tet4->set_node(3, const_cast<Node *>(optimized_node_list[i][3]));
        new_elem_tet4->subdomain_id() = mesh.elem_ptr(elem_id)->subdomain_id();
        elems_tet4.push_back(mesh.add_elem(std::move(new_elem_tet4)));
      }
    }
    else if (tet4_nodes_inside_plane.size() == 3 && tet4_nodes_outside_plane.size() == 1)
    {
      std::vector<const Node *> new_plane_nodes;
      // 3 smaller Tet4 elements are created
      for (const auto & tet4_node_inside_plane : tet4_nodes_inside_plane)
      {
        new_plane_nodes.push_back(nonDuplicateNodeCreator(
            mesh,
            new_on_plane_nodes,
            pointPairLevelSetInterception(*tet4_node_inside_plane, *tet4_nodes_outside_plane[0])));
      }
      std::vector<const Node *> new_elems_nodes = {tet4_nodes_inside_plane[0],
                                                   tet4_nodes_inside_plane[1],
                                                   tet4_nodes_inside_plane[2],
                                                   new_plane_nodes[0],
                                                   new_plane_nodes[1],
                                                   new_plane_nodes[2]};
      std::vector<std::vector<unsigned int>> rotated_tet_face_indices;
      std::vector<std::vector<const Node *>> optimized_node_list;
      MooseMeshElementConversionUtils::prismNodesToTetNodesDeterminer(
          new_elems_nodes, rotated_tet_face_indices, optimized_node_list);

      for (unsigned int i = 0; i < optimized_node_list.size(); i++)
      {
        auto new_elem_tet4 = std::make_unique<Tet4>();
        new_elem_tet4->set_node(0, const_cast<Node *>(optimized_node_list[i][0]));
        new_elem_tet4->set_node(1, const_cast<Node *>(optimized_node_list[i][1]));
        new_elem_tet4->set_node(2, const_cast<Node *>(optimized_node_list[i][2]));
        new_elem_tet4->set_node(3, const_cast<Node *>(optimized_node_list[i][3]));
        new_elem_tet4->subdomain_id() = mesh.elem_ptr(elem_id)->subdomain_id();
        elems_tet4.push_back(mesh.add_elem(std::move(new_elem_tet4)));
      }
    }
    else if (tet4_nodes_inside_plane.size() == 1 && tet4_nodes_outside_plane.size() == 1)
    {
      auto new_plane_node = nonDuplicateNodeCreator(
          mesh,
          new_on_plane_nodes,
          pointPairLevelSetInterception(*tet4_nodes_inside_plane[0], *tet4_nodes_outside_plane[0]));
      // A smaller Tet4 is created, this solution is unique
      auto new_elem_tet4 = std::make_unique<Tet4>();
      new_elem_tet4->set_node(0, const_cast<Node *>(new_plane_node));
      new_elem_tet4->set_node(1, const_cast<Node *>(tet4_nodes_on_plane[0]));
      new_elem_tet4->set_node(2, const_cast<Node *>(tet4_nodes_on_plane[1]));
      new_elem_tet4->set_node(3, const_cast<Node *>(tet4_nodes_inside_plane[0]));
      new_elem_tet4->subdomain_id() = mesh.elem_ptr(elem_id)->subdomain_id();
      elems_tet4.push_back(mesh.add_elem(std::move(new_elem_tet4)));
    }
    else if (tet4_nodes_inside_plane.size() == 1 && tet4_nodes_outside_plane.size() == 2)
    {
      std::vector<const Node *> new_plane_nodes;
      // A smaller Tet4 element is created, this solution is unique
      for (const auto & tet4_node_outside_plane : tet4_nodes_outside_plane)
      {
        new_plane_nodes.push_back(nonDuplicateNodeCreator(
            mesh,
            new_on_plane_nodes,
            pointPairLevelSetInterception(*tet4_node_outside_plane, *tet4_nodes_inside_plane[0])));
      }
      auto new_elem_tet4 = std::make_unique<Tet4>();
      new_elem_tet4->set_node(0, const_cast<Node *>(new_plane_nodes[0]));
      new_elem_tet4->set_node(1, const_cast<Node *>(new_plane_nodes[1]));
      new_elem_tet4->set_node(2, const_cast<Node *>(tet4_nodes_on_plane[0]));
      new_elem_tet4->set_node(3, const_cast<Node *>(tet4_nodes_inside_plane[0]));
      new_elem_tet4->subdomain_id() = mesh.elem_ptr(elem_id)->subdomain_id();
      elems_tet4.push_back(mesh.add_elem(std::move(new_elem_tet4)));
    }
    else if (tet4_nodes_inside_plane.size() == 2 && tet4_nodes_outside_plane.size() == 1)
    {
      std::vector<const Node *> new_plane_nodes;
      // 2 smaller TET4 elements are created
      for (const auto & tet4_node_inside_plane : tet4_nodes_inside_plane)
      {
        new_plane_nodes.push_back(nonDuplicateNodeCreator(
            mesh,
            new_on_plane_nodes,
            pointPairLevelSetInterception(*tet4_node_inside_plane, *tet4_nodes_outside_plane[0])));
      }
      std::vector<const Node *> new_elems_nodes = {tet4_nodes_inside_plane[0],
                                                   tet4_nodes_inside_plane[1],
                                                   new_plane_nodes[1],
                                                   new_plane_nodes[0],
                                                   tet4_nodes_on_plane[0]};
      std::vector<std::vector<unsigned int>> rotated_tet_face_indices;
      std::vector<std::vector<const Node *>> optimized_node_list;
      MooseMeshElementConversionUtils::pyramidNodesToTetNodesDeterminer(
          new_elems_nodes, rotated_tet_face_indices, optimized_node_list);

      for (unsigned int i = 0; i < optimized_node_list.size(); i++)
      {
        auto new_elem_tet4 = std::make_unique<Tet4>();
        new_elem_tet4->set_node(0, const_cast<Node *>(optimized_node_list[i][0]));
        new_elem_tet4->set_node(1, const_cast<Node *>(optimized_node_list[i][1]));
        new_elem_tet4->set_node(2, const_cast<Node *>(optimized_node_list[i][2]));
        new_elem_tet4->set_node(3, const_cast<Node *>(optimized_node_list[i][3]));
        new_elem_tet4->subdomain_id() = mesh.elem_ptr(elem_id)->subdomain_id();
        elems_tet4.push_back(mesh.add_elem(std::move(new_elem_tet4)));
      }
    }
    else
      mooseError("Unexpected scenario.");

    mesh.elem_ptr(elem_id)->subdomain_id() = _block_id_to_remove;
  }

  for (auto & elem_tet4 : elems_tet4)
  {
    if (new_elements_created)
    {
      if (elem_tet4->volume() < 0.0)
      {
        Node * temp = elem_tet4->node_ptr(0);
        elem_tet4->set_node(0, elem_tet4->node_ptr(1));
        elem_tet4->set_node(1, temp);
      }
    }
    // Find the boundary id of the new element
    for (unsigned int i = 0; i < 4; i++)
    {
      const Point & side_pt_0 = *elem_tet4->side_ptr(i)->node_ptr(0);
      const Point & side_pt_1 = *elem_tet4->side_ptr(i)->node_ptr(1);
      const Point & side_pt_2 = *elem_tet4->side_ptr(i)->node_ptr(2);

      const Point side_normal = (side_pt_1 - side_pt_0).cross(side_pt_2 - side_pt_1).unit();
      for (unsigned int j = 0; j < 4; j++)
      {
        if (new_elements_created)
        {
          if (MooseUtils::absoluteFuzzyEqual(side_normal * elem_side_normal_list[j], 1.0))
          {
            for (const auto & side_info : elem_side_list[j])
            {
              boundary_info.add_side(elem_tet4, i, side_info);
            }
          }
        }
      }
      if (MooseUtils::absoluteFuzzyEqual(levelSetEvaluator(side_pt_0), 0.0) &&
          MooseUtils::absoluteFuzzyEqual(levelSetEvaluator(side_pt_1), 0.0) &&
          MooseUtils::absoluteFuzzyEqual(levelSetEvaluator(side_pt_2), 0.0))
      {

        boundary_info.add_side(elem_tet4, i, _cut_face_id);
      }
    }
  }
}

Real
CutMeshByLevelSetGeneratorBase::levelSetEvaluator(const Point & point)
{
  _func_params[0] = point(0);
  _func_params[1] = point(1);
  _func_params[2] = point(2);
  return evaluate(_func_level_set);
}
