# Do not alter <VERSION>, <SKIP_DOCS>. These are template tokens altered
# on the fly by civet recipes. The only modifiable item in moose/ is the
# conda_build_config.yaml file (moose_dev)
{% set VERSION = "<VERSION>" %}
{% set SKIP_DOCS = "<SKIP_DOCS>" %}

package:
  name: moose
  version: {{ VERSION }}

source:
  - path: ../../../moose
  - path: ../functions/retry_build.sh

build:
  number: 0
  string: {{ mpi }}
  pin_depends: strict
  script_env:
    - MOOSE_JOBS
    - MOOSE_OPTIONS
    - SKIP_DOCS={{ SKIP_DOCS }}
    - REQUESTS_CA_BUNDLE
    - SSL_CERT_FILE
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib('c') }}
    # for libmesh libtool
    - moose-libmesh 2026.04.13_0185b8b {{ mpi }}_1
    # build utilities
    - make
    - packaging
    - patchelf # [linux]
    # python; for doc build + premake
    - python 3.14.*
    - moose-tools 2026.04.21
  host:
    - {{ mpi }} {{ mpi_version }}
    - hdf5 {{ hdf5 }}
    - hdf5 {{ hdf5 }} mpi_{{ mpi }}_*
    {% if mpi == "mpich" %}
    # see libfabric entry in conda/conda_build_config.yaml
    - libfabric {{ libfabric }} # [linux]
    {% endif %}
    - libpng
    - moose-libmesh 2026.04.13_0185b8b {{ mpi }}_1
    - moose-wasp 2025.09.19_02960f1 build_6
    - zlib
  run:
    - {{ mpi }} {{ mpi_version }}
    - moose-libmesh 2026.04.13_0185b8b {{ mpi }}_1
    - moose-wasp 2025.09.19_02960f1 build_6
    # c++ compiler for jit
    - gxx_linux-64 {{ cxx_compiler_version }}.*               # [linux]
    - clangxx_osx-64 {{ cxx_compiler_version }}.*             # [osx and x86_64]
    - clangxx_osx-arm64 {{ cxx_compiler_version }}.*          # [osx and arm64]
    # for testharness/python utilities
    - moose-tools 2026.04.21
    # for running app --copy-inputs
    - rsync
  run_constrained:
    - {{ moose_python_constrained }}

about:
  home: https://mooseframework.inl.gov/
  license: LGPL 2.1
  summary: >
   The Multiphysics Object-Oriented Simulation Environment (MOOSE) is a finite-element,
   multiphysics framework primarily developed by Idaho National Laboratory. This superficial module
   (moose) if a future placeholder for binary releases of MOOSE.

extra:
  recipe-maintainers:
    - cticenhour
    - loganharbour
