title: "<Use a descriptive title here> "
body:
  - type: checkboxes
    attributes:
      label: Check these boxes if you have followed the posting rules.
      options:
        - label: I have consulted the [Posting Guidelines](https://github.com/idaholab/moose/discussions/18270).
          required: true
        - label: I have searched the [Discussions Forum](https://github.com/idaholab/moose/discussions) and [MOOSE Framework Troubleshooting](https://mooseframework.inl.gov/help/troubleshooting.html) and have not found what I was looking for
          required: true
        - label: Q&A Getting Started is the most appropriate category for my question (trouble installing, beginner user, ...)
          required: true
  - type: markdown
    attributes:
      value: |
        New to GitHub? Please make use of [GitHub's Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) whenever possible.

        Show us that you care about your own posts. If what you see is a crazy circus show of wildly changing fonts; its time to click the three `...` at the top right of your post, and then "edit", and learn markdown.
  - type: textarea
    id: question
    attributes:
      label: Issue or question about MOOSE
      description: |
        Please give as much context as you think we could need. You can reference other discussions,
        issues, or web articles, web sites, etc.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: (Optional) code in question / simulation log / errors
      description: copy and paste code, simulation log, or errors here.
      render: shell
  - type: textarea
    id: diagnostic
    attributes:
      label: Encountering Errors? Please include diagnostic output
      description: copy and paste output generated by executing `~/projects/moose/scripts/diagnostics.sh`
      placeholder: ~/projects/moose/scripts/diagnostics.sh
      render: pre
