name: Setup utils
description: Setup action utilities

inputs:
  shell:
    description: "The shell to use; default: bash"
    required: false
    default: bash
  source_conda:
    description: Source the conda environment if it exists
    required: false
    type: boolean
    default: true

runs:
  using: composite
  steps:
    - name: Setup utilities
      shell: ${{ inputs.shell }}
      run: |
        echo "::group::Setup utilities"

        UTILS_PATH="${RUNNER_TEMP:-/tmp}/moose_action_utils.sh"
        echo "Writing utils to $UTILS_PATH"

        cat > "$UTILS_PATH" << 'EOF'
        function prefix_pwd()
        {
          local p="${PWD}/"
          local work_dir="/home/runner/work/"
          local new_pwd=${p/#$work_dir/WORK/}
          local docker_work_dir=/__w/
          new_pwd=${p/#$docker_work_dir/WORK_DOCKER/}
          local wsl_work_dir="/mnt/d/a/"
          new_pwd=${p/#$wsl_work_dir/WORK_WSL/}
          echo "${new_pwd}"
        }

        function print_command()
        {
          echo -e "\033[33m$(prefix_pwd)\033[0m: \033[34m$*\033[0m"
        }

        function print_and_run()
        {
          print_command "$@"
          "$@"
          return $?
        }

        # Source conda if it exists
        if [ -n "${MOOSE_CONDA_ENV:-?}" ]; then
          if [ "${{ inputs.source_conda }} == "true" ]; then
            echo "Sourcing Conda environment ${MOOSE_CONDA_ENV} from ${MOOSE_MINIFORGE_DIR}"
            print_and_run source "${MOOSE_MINIFORGE_DIR}/etc/profile.d/conda.sh"
            set +u
            print_and_run conda activate "$MOOSE_CONDA_ENV"
          else
            echo "Not souring Conda environment"
          fi
        fi
        EOF

        if [ -n "${WSL_DISTRO_NAME:-}" ]; then
          UTILS_PATH_WSL="$(wslpath -w "$UTILS_PATH")"
          UTILS_PATH="$UTILS_PATH_WSL"
        fi

        echo "BASH_ENV=${UTILS_PATH}" >> "$GITHUB_ENV"

        echo "::endgroup::"
