//* This file is part of the MOOSE framework
//* https://www.mooseframework.org
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#include "GlobalDisplacementAux.h"
#include "GlobalStrainUserObjectInterface.h"

// MOOSE includes
#include "Assembly.h"
#include "SystemBase.h"
#include "RankTwoTensor.h"

registerMooseObject("TensorMechanicsApp", GlobalDisplacementAux);

InputParameters
GlobalDisplacementAux::validParams()
{
  InputParameters params = AuxKernel::validParams();
  params.addClassDescription(
      "AuxKernel to visualize the displacements generated by the global strain tensor");
  params.addCoupledVar("scalar_global_strain",
                       "Scalar variable providing global strain components");
  params.addCoupledVar("displacements", "The name of the displacement variables");
  params.addRequiredParam<unsigned int>("component",
                                        "The displacement component to consider for this kernel");
  params.addParam<bool>(
      "output_global_displacement", false, "Option to output global displacement only");
  params.addRequiredParam<UserObjectName>("global_strain_uo",
                                          "The name of the GlobalStrainUserObject");
  params.addParam<Point>("reference_point",
                         Point(0, 0, 0),
                         "The coordinate of the center/fixed point of the simulation");

  // Default this object to get executed before the displaced mesh update.
  // This way the AuxVars set by this object can be used as mesh displacements.
  params.set<ExecFlagEnum>("execute_on") = EXEC_PRE_DISPLACE;

  return params;
}

GlobalDisplacementAux::GlobalDisplacementAux(const InputParameters & parameters)
  : AuxKernel(parameters),
    _scalar_global_strain(coupledScalarValue("scalar_global_strain")),
    _component(getParam<unsigned int>("component")),
    _output_global_disp(getParam<bool>("output_global_displacement")),
    _pst(dynamic_cast<const GlobalStrainUserObjectInterface &>(
        getUserObjectBase("global_strain_uo"))),
    _periodic_dir(_pst.getPeriodicDirections()),
    _ref_point(parameters.get<Point>("reference_point")),
    _dim(_mesh.dimension()),
    _ndisp(coupledComponents("displacements")),
    _disp(coupledValues("displacements"))
{
  if (!isNodal())
    paramError("variable", "GlobalDisplacementAux must be used on a nodal auxiliary variable");

  if (_component >= _dim)
    paramError("component",
               "The component ",
               _component,
               " does not exist for ",
               _dim,
               " dimensional problems");
}

Real
GlobalDisplacementAux::computeValue()
{
  RankTwoTensor strain;
  strain.fillFromScalarVariable(_scalar_global_strain);

  for (unsigned int dir = 0; dir < _dim; ++dir)
    if (!_periodic_dir(dir))
      for (unsigned int var = 0; var < _ndisp; ++var)
        strain(dir, var) = 0.0;

  const RealVectorValue & global_disp = strain * ((*_current_node) - _ref_point);

  if (_output_global_disp)
    return global_disp(_component);
  else
    return global_disp(_component) + (*_disp[_component])[_qp];
}
