Content:
    - framework/doc/content
    - modules/stork/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer
Extensions:
    MooseDocs.extensions.navigation:
        name: stork
        repo: https://github.com/idaholab/moose
        home: /modules/stork
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/stork
        remove: !include ${MOOSE_DIR}/framework/doc/remove.yml
        includes:
            - framework/include
            - modules/stork/include
    MooseDocs.extensions.common:
        shortcuts: !include ${MOOSE_DIR}/framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
    MooseDocs.extensions.sqa:
        active: False
