//* This file is part of the MOOSE framework
//* https://mooseframework.inl.gov
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#pragma once

#include "MeshGenerator.h"

/**
 * Mesh generator for a square/rectangular duct around a square-lattice subassembly.
 */
class SCMQuadDuctMeshGenerator : public MeshGenerator
{
public:
  SCMQuadDuctMeshGenerator(const InputParameters & parameters);
  static InputParameters validParams();
  std::unique_ptr<MeshBase> generate() override;

protected:
  /// @brief Maps a duct cross-section point and axial layer to a linear point index
  /// @param points_per_layer Number of points in each duct cross-section layer
  /// @param layer Axial (z-direction) layer index
  /// @param point Index of the point within the cross-section
  /// @return Index into the flattened points vector used by ductPoints
  size_t
  ductPointIndex(unsigned int points_per_layer, unsigned int layer, unsigned int point) const;

  /// @brief Computes the x-y corner coordinates of a rectangular duct cross-section
  /// @param corners Output vector containing the duct corner points
  /// @param half_x Half-width of the duct in the x-direction
  /// @param half_y Half-width of the duct in the y-direction
  /// @param center Center point of the duct cross-section
  void
  ductCorners(std::vector<Point> & corners, Real half_x, Real half_y, const Point & center) const;

  /// @brief Generates the points along the rectangular duct cross-section boundary
  /// @param cross_sec Output vector of cross-section boundary points
  /// @param nx Number of boundary divisions in the x-direction
  /// @param ny Number of boundary divisions in the y-direction
  /// @param pitch Spacing between adjacent boundary points
  /// @param side_gap Gap between the duct wall and surrounding geometry
  void ductCrossSec(std::vector<Point> & cross_sec,
                    unsigned int nx,
                    unsigned int ny,
                    Real pitch,
                    Real side_gap) const;

  /// @brief Computes all 3D point locations used to construct the duct mesh
  /// @param points Output vector of 3D point locations
  /// @param cross_sec Cross-section boundary points
  /// @param z_layers Axial (z-direction) layer coordinates
  void ductPoints(std::vector<Point> & points,
                  const std::vector<Point> & cross_sec,
                  const std::vector<Real> & z_layers) const;

  /// @brief Determines element connectivity for the duct mesh
  /// @param elem_point_indices Output element connectivity defined by point indices
  /// @param n_layers Number of axial layers in the duct mesh
  /// @param points_per_layer Number of points per cross-section layer
  void ductElems(std::vector<std::vector<size_t>> & elem_point_indices,
                 unsigned int n_layers,
                 unsigned int points_per_layer) const;

  /// @brief Builds duct mesh nodes and elements and inserts them into the mesh
  /// @param mesh Mesh object to which duct elements and nodes are added
  /// @param duct_nodes Output vector of created duct nodes
  /// @param points Point coordinates generated by ductPoints
  /// @param elem_point_indices Element connectivity generated by ductElems
  /// @param block Subdomain ID assigned to the duct elements
  void buildDuct(std::unique_ptr<MeshBase> & mesh,
                 std::vector<Node *> & duct_nodes,
                 const std::vector<Point> & points,
                 const std::vector<std::vector<size_t>> & elem_point_indices,
                 SubdomainID block) const;

  /// Mesh that comes from another generator
  std::unique_ptr<MeshBase> & _input;
  /// number of axial cells
  const unsigned int _n_cells;
  /// axial location of nodes
  std::vector<Real> _z_grid;
  const Real _unheated_length_entry;
  const Real _heated_length;
  const Real _unheated_length_exit;
  /// block index
  const unsigned int _block_id;
  /// lattice geometry
  const Real _pitch;
  const unsigned int _nx;
  const unsigned int _ny;
  const Real _side_gap;
};
