//* This file is part of the MOOSE framework
//* https://mooseframework.inl.gov
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#pragma once

#include "MeshGenerator.h"

/**
 * Mesh generator for a square/rectangular duct around a square-lattice subassembly.
 */
class SCMQuadDuctMeshGenerator : public MeshGenerator
{
public:
  SCMQuadDuctMeshGenerator(const InputParameters & parameters);

  std::unique_ptr<MeshBase> generate() override;

protected:
  /**
   * Returns an index into the vector of point/node positions used/generated by
   * ductPoints.  This is used for mapping a xsec point index and a z-axis layer
   * index to its corresponding point vector index.
   */
  size_t
  ductPointIndex(unsigned int points_per_layer, unsigned int layer, unsigned int point) const;

  /**
   * calculate the x-y coordinates of the corner points for the duct cross section.
   */
  void
  ductCorners(std::vector<Point> & corners, Real half_x, Real half_y, const Point & center) const;

  /**
   * calculates the points around the duct cross section boundary (perpendicular to z axis) using
   * assembly parameters.
   */
  void ductXsec(
      std::vector<Point> & xsec, unsigned int nx, unsigned int ny, Real pitch, Real side_gap) const;

  /**
   * Calculates all the point/node positions that will be used to form elements
   * making the duct.
   */
  void ductPoints(std::vector<Point> & points,
                  const std::vector<Point> & xsec,
                  const std::vector<Real> & z_layers) const;
  /**
   * Calculates the groups of points/nodes that comprise each element in the
   * duct mesh.  The groups are identified by indices into the points vector
   * returned by ductPoints.  n_layers is the number of z-axis layers the duct
   * has (i.e. the number of z x-secs lining up with nodes.  And
   * points_per_layer is the number of nodes/points in each of those x-secs.
   */
  void ductElems(std::vector<std::vector<size_t>> & elem_point_indices,
                 unsigned int n_layers,
                 unsigned int points_per_layer) const;

  /**
   * buildDuct generates and adds mesh node and element objects to the given
   * mesh corresponding to the given points (from ductPoints) and
   * elem_point_indices that identify node point groups forming elements (from ductElems)
   */
  void buildDuct(std::unique_ptr<MeshBase> & mesh,
                 std::vector<Node *> & duct_nodes,
                 const std::vector<Point> & points,
                 const std::vector<std::vector<size_t>> & elem_point_indices,
                 SubdomainID block) const;

  /// Mesh that comes from another generator
  std::unique_ptr<MeshBase> & _input;
  /// number of axial cells
  const unsigned int _n_cells;
  /// axial location of nodes
  std::vector<Real> _z_grid;
  const Real _unheated_length_entry;
  const Real _heated_length;
  const Real _unheated_length_exit;
  /// block index
  const unsigned int _block_id;
  /// lattice geometry
  const Real _pitch;
  const unsigned int _nx;
  const unsigned int _ny;
  const Real _side_gap;

public:
  static InputParameters validParams();
};
