//* This file is part of the MOOSE framework
//* https://mooseframework.inl.gov
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#pragma once

#include "MeshGenerator.h"

/**
 * Mesh generator for hexagonal duct
 */
class SCMTriDuctMeshGenerator : public MeshGenerator
{
public:
  SCMTriDuctMeshGenerator(const InputParameters & parameters);
  static InputParameters validParams();
  std::unique_ptr<MeshBase> generate() override;

protected:
  /// @brief Maps a duct cross-section point and axial layer to a linear point index
  /// @param points_per_layer Number of points in each duct cross-section layer
  /// @param layer Axial (z-direction) layer index
  /// @param point Index of the point within the cross-section
  /// @return Index into the flattened points vector used by ductPoints
  size_t
  ductPointIndex(unsigned int points_per_layer, unsigned int layer, unsigned int point) const;

  /// @brief Computes the x-y corner coordinates of the duct cross-section
  /// @param corners Output vector containing the duct corner points
  /// @param flat_to_flat Flat-to-flat distance of the duct
  /// @param center Center point of the duct cross-section
  void ductCorners(std::vector<Point> & corners, Real flat_to_flat, const Point & center) const;

  /// @brief Generates the points along the duct cross-section sides
  /// @param cross_sec Output vector of cross-section boundary points
  /// @param corners Corner points defining the duct geometry
  /// @param nrings Number of rings of the assembly. (Rings of pins around central pin)
  /// @param pitch Spacing between adjacent pins/subchannel centroids
  void ductCrossSec(std::vector<Point> & cross_sec,
                    const std::vector<Point> & corners,
                    unsigned int nrings,
                    Real pitch) const;

  /// @brief Computes all 3D point locations used to construct the duct mesh
  /// @param points Output vector of 3D point locations
  /// @param cross_sec Cross-section boundary points
  /// @param z_layers Axial (z-direction) layer coordinates
  void ductPoints(std::vector<Point> & points,
                  const std::vector<Point> & cross_sec,
                  const std::vector<Real> & z_layers) const;

  /// @brief Determines element connectivity for the duct mesh
  /// @param elem_point_indices Output element connectivity defined by point indices
  /// @param n_layers Number of axial layers in the duct mesh
  /// @param points_per_layer Number of points per cross-section layer
  void ductElems(std::vector<std::vector<size_t>> & elem_point_indices,
                 unsigned int n_layers,
                 unsigned int points_per_layer) const;

  /// @brief Builds duct mesh nodes and elements and inserts them into the mesh
  /// @param mesh Mesh object to which duct elements and nodes are added
  /// @param duct_nodes Output vector of created duct nodes
  /// @param points Point coordinates generated by ductPoints
  /// @param elem_point_indices Element connectivity generated by ductElems
  /// @param block Subdomain ID assigned to the duct elements
  void buildDuct(std::unique_ptr<MeshBase> & mesh,
                 std::vector<Node *> & duct_nodes,
                 const std::vector<Point> & points,
                 const std::vector<std::vector<size_t>> & elem_point_indices,
                 SubdomainID block) const;

  /// Mesh that comes from another generator
  std::unique_ptr<MeshBase> & _input;
  /// number of axial cells
  const unsigned int _n_cells;
  /// axial location of nodes
  std::vector<Real> _z_grid;
  /// unheated length of the fuel Pin at the entry of the assembly
  const Real _unheated_length_entry;
  /// heated length of the fuel Pin
  const Real _heated_length;
  /// unheated length of the fuel Pin at the exit of the assembly
  const Real _unheated_length_exit;
  /// block index
  const unsigned int _block_id;
  /// Distance between the neighbor fuel pins, pitch
  const Real _pitch;
  /// number of rings of fuel pins
  const unsigned int _n_rings;
  /// the distance between flat surfaces of the duct facing each other
  const Real _flat_to_flat;
};
