//* This file is part of the MOOSE framework
//* https://www.mooseframework.org
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#include "PatternedHexPeripheralModifier.h"

#include "MooseMeshUtils.h"

registerMooseObject("ReactorApp", PatternedHexPeripheralModifier);

InputParameters
PatternedHexPeripheralModifier::validParams()
{
  InputParameters params = PatternedPolygonPeripheralModifierBase::validParams();
  return params;
}

PatternedHexPeripheralModifier::PatternedHexPeripheralModifier(const InputParameters & parameters)
  : PatternedPolygonPeripheralModifierBase(parameters)
{
  _num_sides = HEXAGON_NUM_SIDES;
  declareMeshProperty<bool>("hexagon_peripheral_trimmability", false);
  declareMeshProperty<bool>("hexagon_center_trimmability", false);
}

std::unique_ptr<MeshBase>
PatternedHexPeripheralModifier::generate()
{
  if (hasMeshProperty<bool>("hexagon_center_trimmability", _input_name))
    setMeshProperty("hexagon_center_trimmability",
                    getMeshProperty<bool>("hexagon_center_trimmability", _input_name));

  // Check if the input mesh is compatible
  if (!hasMeshProperty<bool>("peripheral_modifier_compatible", _input_name) ||
      !getMeshProperty<bool>("peripheral_modifier_compatible", _input_name))
    paramError("input",
               "The input mesh is generated by a mesh generator that is not compatible with "
               "PatternedHexPeripheralModifier.");
  // Whether the input mesh is hexagonal
  if (!hasMeshProperty<bool>("hexagon_center_trimmability", _input_name))
    paramError("input", "The input mesh is not declared as center-trimmable in its metadata.");

  return PatternedPolygonPeripheralModifierBase::generate();
}
