//* This file is part of the MOOSE framework
//* https://mooseframework.inl.gov
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#pragma once

#include "MortarSegmentInfo.h"

#include "libmesh/point.h"
#include "libmesh/int_range.h"

#include <array>
#include <optional>
#include <string>
#include <vector>

using libMesh::Point;
using libMesh::Real;

#ifdef MOOSE_UNIT_TEST
class MortarSegmentHelperTest;
#endif

/**
 * This class supports defining mortar segment mesh elements in 3D by projecting secondary and
 * primary elements onto a linearized plane, computing the overlapping polygon formed by their
 * projections, and triangulating the resulting nodes.
 */

class MortarSegmentHelper
{
public:
  MortarSegmentHelper(std::vector<Point> secondary_nodes,
                      const Point & center,
                      const Point & normal,
                      const MortarSegmentTriangulationMode triangulation_mode,
                      const bool triangulate_triangles);

  MortarSegmentHelper(std::vector<Point> secondary_nodes,
                      std::vector<Point> secondary_reference_points,
                      const Point & center,
                      const Point & normal,
                      const MortarSegmentTriangulationMode triangulation_mode,
                      const bool triangulate_triangles);

  /**
   * Computes the intersection between line segments defined by point pairs (p1,p2) and (q1,q2)
   * Also computes s, the ratio of distance between (p1,p2) that the intersection falls,
   * quantity s is useful in avoiding adding nearly degenerate nodes
   */
  Point getIntersection(
      const Point & p1, const Point & p2, const Point & q1, const Point & q2, Real & s) const;

  /**
   * Check that a point is inside the secondary polygon (for verification only)
   */
  bool isInsideSecondary(const Point & pt) const;

  /**
   * Checks whether polygons are disjoint for an easy out
   */
  bool isDisjoint(const std::vector<Point> & poly) const;

  /**
   * Project a primary polygon into the helper plane while preserving the clipping orientation.
   */
  std::vector<Point> projectPrimaryPoly(const std::vector<Point> & primary_nodes) const;

  /**
   * Clip secondary element (defined in instantiation) against given primary polygon
   * result is a set of 2D nodes defining clipped polygon
   */
  std::vector<Point> clipPoly(const std::vector<Point> & primary_nodes) const;

  /**
   * Triangulate a polygon according to the configured mortar-segment triangulation mode.
   * @param poly_nodes List of 2D nodes defining polygon. May be augmented with extra interior
   *                   nodes (e.g. centroid) by triangulation modes that require them; callers
   *                   should append the result to their nodes list before applying the offset
   *                   to \p tri_map.
   * @param tri_map Output triangle list expressed in indices local to \p poly_nodes (i.e. starting
   *                at 0). Callers are responsible for shifting these indices into the global node
   *                numbering.
   */
  void triangulatePoly(std::vector<Point> & poly_nodes,
                       std::vector<std::vector<unsigned int>> & tri_map) const;

  /**
   * Get mortar segments generated by a secondary and primary element pair
   * @param primary_nodes List of primary element 3D nodes
   * @return nodes List of 3D mortar segment nodes
   * @return tri_map List of integer arrays defining which nodes belong to each mortar segment
   */
  void getMortarSegments(const std::vector<Point> & primary_nodes,
                         std::vector<Point> & nodes,
                         std::vector<std::vector<unsigned int>> & elem_to_nodes);

  /**
   * Append mortar segments and aligned parent-reference coordinates. Segments below
   * \p minimum_segment_area are removed before mapping; retained vertices must map uniquely.
   */
  void getMortarSegments(const std::vector<Point> & primary_nodes,
                         const std::vector<Point> & primary_reference_points,
                         std::vector<Point> & nodes,
                         std::vector<std::vector<unsigned int>> & elem_to_nodes,
                         std::vector<std::array<Point, 3>> & elem_to_secondary_reference_points,
                         std::vector<std::array<Point, 3>> & elem_to_primary_reference_points,
                         Real minimum_segment_area = 0.);

  /**
   * Compute area of polygon
   */
  Real area(const std::vector<Point> & nodes) const;

  /**
   * Get center point of secondary element
   */
  const Point & center() const { return _center; }

  /**
   * Get area fraction remaining after clipping against primary elements
   */
  Real remainder() const { return _remaining_area_fraction; }

  /**
   * Get 3D position of node of linearized secondary element
   */
  Point point(unsigned int i) const
  {
    return (_secondary_poly[i](0) * _u) + (_secondary_poly[i](1) * _v) + _center;
  }

private:
  struct ReferenceMappingData
  {
    const std::vector<Point> & primary_reference_points;
    std::vector<std::array<Point, 3>> & elem_to_secondary_reference_points;
    std::vector<std::array<Point, 3>> & elem_to_primary_reference_points;
    Real minimum_segment_area;
  };

  void getMortarSegmentsImpl(const std::vector<Point> & primary_nodes,
                             std::vector<Point> & nodes,
                             std::vector<std::vector<unsigned int>> & elem_to_nodes,
                             ReferenceMappingData * reference_mapping);

  std::vector<Point> clipProjectedPoly(const std::vector<Point> & primary_poly) const;

  /// Recover a parent-reference point, returning no value for invalid or out-of-tolerance maps.
  std::optional<Point> referencePoint(const Point & point,
                                      const std::vector<Point> & poly,
                                      const std::vector<Point> & reference_points,
                                      std::string * failure_reason = nullptr) const;

#ifdef MOOSE_UNIT_TEST
  friend class MortarSegmentHelperTest;
#endif

  /**
   * Geometric center of secondary element
   */
  Point _center;

  /**
   * Normal at geometric center of secondary element
   */
  Point _normal;

  /**
   * Vectors orthogonal to normal that span the plane projection will be performed on.
   * These vectors are used to project the polygon clipping problem on a 2D plane,
   * they are defined so the nodes of the projected polygon are listed with positive orientation
   */
  Point _u, _v;

  /**
   * Area of projected secondary element
   */
  Real _secondary_area;

  /**
   * Fraction of area remaining after overlapping primary polygons clipped
   */
  Real _remaining_area_fraction;

  bool _debug;

  /**
   * Tolerance for intersection and clipping
   */
  Real _tolerance = 1e-8;

  /**
   * Triangulation mode used for clipped polygons.
   */
  const MortarSegmentTriangulationMode _triangulation_mode;

  /**
   * Whether already-triangular polygons should still be centroid-subdivided.
   */
  const bool _triangulate_triangles;

  /**
   * Tolerance times secondary area for dimensional consistency
   */
  Real _area_tol;

  /**
   * Tolerance times secondary area for dimensional consistency
   */
  Real _length_tol;

  /**
   * List of projected points on the linearized secondary element
   */
  std::vector<Point> _secondary_poly;

  /// Parent reference points corresponding to _secondary_poly.
  std::vector<Point> _secondary_reference_points;
};
