# Making a Change to this package?
# REMEMBER TO UPDATE the .yaml files for the following packages:
#   moose-dev/*
#
# As well as any directions pertaining to modifying those files.
{% set version = "2026.02.16" %}

package:
  name: moose-tools
  version: {{ version }}

source:
  path: ../tools

build:
  number: 0
  script_env:
    - REQUESTS_CA_BUNDLE
    - SSL_CERT_FILE
    - CURL_CA_BUNDLE
    - NODE_EXTRA_CA_CERTS
requirements:
  build:
    - {{ moose_python }}
    - setuptools
  # This should (nearly) mirror requirements.txt, but won't exactly
  # because we will have a few more packages (listed first) and there
  # isn't a one-to-one mapping from pypi packages to conda packages
  run:
    # Packages that do not exist in requirements.txt
    - python
    - git-lfs

    - jinja2
    - matplotlib-base # instead of matplotlib from pypi
    - numpy
    - pandas
    - plotly
    - pylint
    - pyyaml
    - scikit-image
    - sympy

    # Python utilities
    - packaging
    - setuptools

    # Cardinal
    - uncertainties
    # CI/CD
    - gitpython
    - paramiko
    - psycopg2 # instead of psycopg-binary from pypi
    - pycobertura
    # Formatting and linting
    - black 26.1.0
    - clang-format 19.1.7
    - ruff 0.15.7
    # Testing
    - coverage 7.13.2
    - mock
    - pytest
    - pytest-cov

    # python/moosecontrol
    - requests
    # python/MooseDocs.commands
    - beautifulsoup4
    - livereload
    - lxml
    # python/MooseDocs.extensions
    - pybtex
    - pylatexenc
    # python/TestHarness.testers
    - deepdiff
    - xmltodict<0.14
    # python/TestHarness.resultssummary
    - tabulate
    # python/TestHarness.resultsstore
    - pymongo
    # python/TestHarness.schedulers
    - psutil
test:
  commands:
    - black --version
    - clang-format --version
    - git-lfs --version
    - pg_config --help
    - ruff --version

about:
  home: https://mooseframework.inl.gov/
  license: LGPL 2.1
  summary: >
    This superficial module (moose-tools) acts as a top-level module designed to provide all
    dependencies required in order to run the TestHarness, clang-format, and create MOOSE
    Documentation.

extra:
  recipe-maintainers:
    - cticenhour
    - loganharbour
