{% set build = 0 %}
{% set version = "2021.07.13" %}

package:
  name: moose-tools
  version: {{ version }}

source:
  path: ../tools

build:
  number: {{ build }}

requirements:
  build:
    - python {{ python }}

  run:
    - gcc_linux-64       {{ gcc }}            # [linux]
    - gxx_linux-64       {{ gxx }}            # [linux]
    - gfortran_linux-64  {{ fortran }}        # [linux]
    - gcc_impl_linux-64  {{ gccimpl }}        # [linux]
    - clang              {{ clang }}          # [osx]
    - clang_osx-64       {{ clangosx }}       # [osx]
    - clangxx            {{ clangxx }}        # [osx]
    - clangxx_osx-64     {{ clangxxosx }}     # [osx]
    - compiler-rt        {{ compilerrt }}     # [osx]
    - compiler-rt_osx-64 {{ compilerrtosx }}  # [osx]
    - libllvm11          {{ libllvm }}        # [osx]
    - clang-tools                             # [osx]
    - llvm-openmp        {{ llvmopenmp }}     # [osx]
    - gfortran_osx-64    {{ osxfortran }}     # [osx]
    - libclang           {{ libclang }}       # [osx]
    - libcxx             {{ libcxx }}         # [osx]
    - libblas            {{ libblas }}        # [osx]
    - libcblas           {{ libcblas }}       # [osx]
    - liblapack          {{ liblapack }}      # [osx]
    - libopenblas        {{ libopenblas }}    # [osx]
    - vtk                {{ vtk}}
    - numpy              {{ numpy }}
    - pyqt               {{ pyqt }}
    - matplotlib         {{ matplotlib }}
    - pandas             {{ pandas }}
    - livereload         {{ livereload }}
    - yaml               {{ yaml }}
    - pyyaml             {{ pyyaml }}
    - beautifulsoup4     {{ beautifulsoup4 }}
    - pybtex             {{ pybtex }}
    - mock               {{ mock }}
    - lxml               {{ lxml }}
    - scikit-image       {{ scikit_image }}
    - pylatexenc         {{ pylatexenc }}
    - jinja2             {{ jinja2 }}
    - mako               {{ mako }}
    - python

test:
  imports:
    - numpy
    - PyQt5
    - matplotlib
    - pandas
    - livereload
    - yaml
    - bs4
    - pybtex
    - mock
    - lxml
    - skimage
    - vtk
    - pylatexenc
    - jinja2

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: 'This superficial module (moose-tools) acts as a top-level module designed to provide all dependencies required in order to run Peacock and MOOSE Documentation.'

extra:
  recipe-maintainers:
    - milljm
