#pragma once
// Auto-generated by modules/modules.mk. Do not edit.
// Records the set of enabled MOOSE modules so that changing it (for example by
// adding a module to an application Makefile) recompiles the module registration
// in ModulesApp.h/.C without requiring a clean rebuild.
// Enabled modules:
