# Making a Change to this package?
# REMEMBER TO UPDATE the .yaml files for the following packages:
#   petsc/*
#   libmesh-vtk/*
#   peacock/*
#
# As well as any directions pertaining to modifying those files.
# ALSO: Follow the directions in scripts/tests/versioner_hashes.yaml
{% set build = 11 %}
{% set version = "4.0.2" %}

# permanent
{% set strbuild = "build_" + build|string %}

package:
  name: moose-mpich
  version: {{ version }}

source:
  - path: .

build:
  number: {{ build }}
  string: {{ strbuild }}
  skip: True                    # [win]
  pin_depends: strict
  run_exports:
    - {{ pin_subpackage('moose-mpich', max_pin='x.x') }}

requirements:
  build:
    - mpich {{ version }}
    - mpich-mpicc {{ version }}
    - mpich-mpicxx {{ version }}
    - mpich-mpifort {{ version }}
    - {{ moose_hdf5 }}
    - {{ moose_krb5 }}
    - {{ moose_icu }}
    - {{ moose_libclang }}
    - {{ moose_libclang13 }}
    - {{ moose_clangcc }}       # [osx]
    - {{ moose_clangxx }}       # [osx]
  run:
    - mpich {{ version }}
    - mpich-mpicc {{ version }}
    - mpich-mpicxx {{ version }}
    - mpich-mpifort {{ version }}
    - {{ moose_libgfortran }}
    - {{ moose_libgfortran5 }}
    - {{ moose_hdf5 }}
    - {{ moose_krb5 }}
    - {{ moose_icu }}
    - {{ moose_ld64 }}          # [osx]
    - {{ moose_libclang }}      # [osx]
    - {{ moose_libclang13 }}    # [osx]
    - {{ moose_clangcc }}       # [osx]
    - {{ moose_clangxx }}       # [osx]
    - {{ moose_libxt }}         # [linux]
    - {{ moose_libsm }}         # [linux]
    - {{ moose_libx11 }}        # [linux]
    - {{ moose_libice }}        # [linux]
    - {{ moose_libxext }}       # [linux]
    - {{ moose_mesa_libgl }}    # [linux]
    - {{ moose_xorg_x11 }}      # [linux]
    - {{ moose_libglu }}        # [linux]
    - {{ moose_mesalib }}       # [linux]
    - cmake
    - make
    - libtool
    - autoconf
    - automake 1.16.5
    - m4
    - zfp 0.5.5
    - bison 3.4
    - mpi 1.0 mpich
  # Python min/max constraints
  run_constrained:
    - python <{{3.11}}

test:
  commands:
    - test -f $PREFIX/etc/conda/activate.d/activate_moose-mpich.sh

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: 'A top-level package designed to control environment variables related to conda-forge provided MPICH'
  description: |
    MPICH is a high performance and widely portable implementation of the
    Message Passing Interface (MPI) standard.
  doc_url: http://www.mpich.org/documentation/guides
  dev_url: https://wiki.mpich.org/mpich/index.php/Main_Page

extra:
  recipe-maintainers:
    - milljm
    - cticenhour
