{% set build = 0 %}
{% set version = "2022.12.05" %}

package:
  name: moose-pyhit
  version: {{ version }}

source:
  git_url: https://github.com/milljm/moose-pyhit.git

build:
  number: {{ build }}  # [linux,osx]
  skip: true           # [win]
  pin_depends: record

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ moose_python }}
    - cython
    - setuptools

  host:
    - {{ compiler('cxx') }}
    - {{ moose_python }}
    - cython

  run:
    - setuptools
    - python

test:
  imports:
    - pyhit

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: 'HIT Parser'

extra:
  recipe-maintainers:
    - milljm
