{% set version = "2024.05.08" %}

package:
  name: moose-pyhit
  version: __VERSIONER_PYHIT_VERSION__

source:
  git_url: https://github.com/milljm/moose-pyhit.git

build:
  number: __VERSIONER_PYHIT_BUILD_NUMBER__
  string: build___VERSIONER_PYHIT_BUILD_NUMBER__
  skip: true           # [win]
  pin_depends: record

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ moose_python }}
    - {{ moose_wasp }}
    - cython
    - setuptools

  host:
    - {{ compiler('cxx') }}
    - {{ moose_python }}
    - make
    - cython

  run:
    - {{ moose_wasp }}
    - setuptools
    - python

test:
  imports:
    - pyhit

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: 'HIT Parser'

extra:
  recipe-maintainers:
    - milljm
