//* This file is part of the MOOSE framework
//* https://www.mooseframework.org
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#pragma once

#include "THMControl.h"

class Function;

/**
 * This block reads an input computed by the control logic system and sets a value in a specified
 * component
 */
class SetComponentRealValueControl : public THMControl
{
public:
  SetComponentRealValueControl(const InputParameters & parameters);

  virtual void execute();

protected:
  /// The name of the component that is controlled
  const std::string & _component_name;
  /// The parameter name in the component that is controlled
  const std::string & _param_name;
  /// Control parameter name used internally by MOOSE (the name is generated by THM)
  MooseObjectParameterName _ctrl_param_name;
  /// The value that is written into the component
  const Real & _value;

public:
  static InputParameters validParams();
};
