{% set version = "<VERSION>" %}

package:
  name: <PREFIX_PACKAGE_WITH><FORMATTED_APPLICATION>
  version: {{ version }}

build:
  number: 0
  string: build_0

about:
  home: https://inl.gov/ncrc
  license: NONE
  summary: 'MOOSE-based application <APPLICATION> shell for indexing available versions.'

extra:
  recipe-maintainers:
    - cticenhour
    - loganharbour
