//* This file is part of the MOOSE framework
//* https://mooseframework.inl.gov
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#include "gtest/gtest.h"

#include "CSGEngUnitTest.h"

#include "MooseUnitUtils.h"

namespace CSG
{

/// tests the CSGSurfaceEngUnit functionality as a CSGEngUnit and CSGSurface
TEST(CSGEngUnitTest, testSurfUnit)
{
  auto surf_unit_ptr = std::make_unique<FakeSurfEngUnit>("surf_unit");

  /* Test the Engineering Unit related functionality (pre-expansion) */
  ASSERT_EQ("surf_unit", surf_unit_ptr->getName());
  ASSERT_EQ("SURFACE", surf_unit_ptr->getBehavior());
  ASSERT_EQ("CSG::FakeSurfEngUnit", surf_unit_ptr->getUnitType());

  // attributes - should not cause any error (contents don't matter for this unit test)
  ASSERT_NO_THROW(surf_unit_ptr->getAttributes());

  // evaluateSurfaceEquationAtPoint - assert that it is callable without error
  Point p(0, 0, 0);
  ASSERT_NO_THROW(surf_unit_ptr->evaluateSurfaceEquationAtPoint(p));

  // calling getExpandedRegion() before expandUnit() should cause error
  Moose::UnitUtils::assertThrows([&surf_unit_ptr]() { surf_unit_ptr->getExpandedRegion(); },
                                 "getExpandedRegion() cannot be called on CSGSurfaceEngUnit");

  /* Test the CSGSurface-related functionality */

  // getSurfaceType() should return the same as getUnitType()
  ASSERT_EQ("CSG::FakeSurfEngUnit", surf_unit_ptr->getSurfaceType());

  // calling getCoeffs should raise error
  Moose::UnitUtils::assertThrows([&surf_unit_ptr]() { surf_unit_ptr->getCoeffs(); },
                                 "cannot getCoeffs(). Coefficients are only callable on "
                                 "CSGSurface(s) generated by expandUnit().");

  // getHalfspaceFromPoint() for CSGSurfaces should still be accessible and correct as if it were a
  // true CSGSurface object (always postive half-space for this testing class)
  ASSERT_EQ(CSGSurface::Halfspace::POSITIVE, surf_unit_ptr->getHalfspaceFromPoint(p));

  // setName() should be functioning through CSGSurface
  surf_unit_ptr->setName("new_name");
  ASSERT_EQ("new_name", surf_unit_ptr->getName());

  /* Test expandUnit() functionality */

  // expandUnit should create 2 surfaces and set _expanded_region, callable by getExpandedRegion
  auto csg_obj = std::make_unique<CSGBase>();
  // no surfaces on object before expansion
  ASSERT_EQ(0, csg_obj->getAllSurfaces().size());
  // expand unit
  surf_unit_ptr->expandUnit(*csg_obj);
  // two surfaces should have been created and added to base
  auto base_surfs = csg_obj->getAllSurfaces();
  ASSERT_EQ(2, base_surfs.size());
  // region surfaces should be the same objects as the ones in base and form intersection
  auto reg = surf_unit_ptr->getExpandedRegion();
  auto reg_surfs = reg.getSurfaces();
  ASSERT_EQ(2, reg_surfs.size());
  for (const auto & rs : reg_surfs)
  {
    bool found = false;
    for (const auto & bs : base_surfs)
      if (&rs.get() == &bs.get())
      {
        found = true;
        break;
      }
    ASSERT_TRUE(found);
  }
  ASSERT_EQ("INTERSECTION", reg.getRegionTypeString());
}

} // namespace CSG
