//* This file is part of the MOOSE framework
//* https://mooseframework.inl.gov
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#include "gtest/gtest.h"

#include "CSGEngUnitTest.h"
#include "CSGNPolygonUnit.h"
#include "CSGPlane.h"

#include "MooseUnitUtils.h"

namespace CSG
{

/**
 * Tests to make sure the basic functionality and inheritance mechanisms for each engineering unit
 * type is functioning properly. This uses some bare minimum fake engineering units defined in the
 * header file for these tests.
 */

/// tests the CSGSurfaceEngUnit functionality as a CSGEngUnit and CSGSurface
TEST(CSGEngUnitTest, testSurfUnit)
{
  FakeSurfEngUnit surf_unit("surf_unit");

  /* Test the Engineering Unit related functionality (pre-expansion) */
  ASSERT_EQ("surf_unit", surf_unit.getName());
  ASSERT_EQ("SURFACE", surf_unit.getBehavior());
  ASSERT_EQ("CSG::FakeSurfEngUnit", surf_unit.getUnitType());

  // attributes - should not cause any error (contents don't matter for this unit test)
  ASSERT_NO_THROW(surf_unit.getAttributes());

  // evaluateSurfaceEquationAtPoint - assert that it is callable without error
  Point p(0, 0, 0);
  ASSERT_NO_THROW(surf_unit.evaluateSurfaceEquationAtPoint(p));

  // calling getExpandedRegion() before expandUnit() should cause error
  Moose::UnitUtils::assertThrows([&surf_unit]() { surf_unit.getExpandedRegion(); },
                                 "getExpandedRegion() cannot be called on CSGSurfaceEngUnit");

  /* Test the CSGSurface-related functionality */

  // getSurfaceType() should return the same as getUnitType()
  ASSERT_EQ("CSG::FakeSurfEngUnit", surf_unit.getSurfaceType());

  // calling getCoeffs should raise error
  Moose::UnitUtils::assertThrows([&surf_unit]() { surf_unit.getCoeffs(); },
                                 "cannot getCoeffs(). Coefficients are only callable on "
                                 "CSGSurface(s) generated by expandUnit().");

  // getHalfspaceFromPoint() for CSGSurfaces should still be accessible and correct as if it were a
  // true CSGSurface object (always postive half-space for this testing class)
  ASSERT_EQ(CSGSurface::Halfspace::POSITIVE, surf_unit.getHalfspaceFromPoint(p));

  // setName() should be functioning through CSGSurface
  surf_unit.setName("new_name");
  ASSERT_EQ("new_name", surf_unit.getName());

  /* Test expandUnit() functionality */
  auto csg_obj = std::make_unique<CSGBase>();
  surf_unit.expandUnit(*csg_obj);
  // region surfaces should be the same objects as the ones in base
  auto reg = surf_unit.getExpandedRegion();
  auto reg_surfs = reg.getSurfaces();
  ASSERT_EQ(2, reg_surfs.size());
  for (const auto & rs : reg_surfs)
    ASSERT_EQ(&rs.get(), &csg_obj->getSurfaceByName(rs.get().getName()));
}

/// Test CSGCellEngUnit functionality as CSGEngUnit and CSGCell
TEST(CSGEngUnitTest, testCellUnit)
{
  std::string name = "cell_unit";
  FakeCellEngUnit cell_unit(name);

  /* Test the Engineering Unit related functionality (pre-expansion) */
  ASSERT_EQ(name, cell_unit.getName());
  ASSERT_EQ("CELL", cell_unit.getBehavior());
  ASSERT_EQ("CSG::FakeCellEngUnit", cell_unit.getUnitType());

  // attributes - should not cause any error (contents don't matter for this unit test)
  ASSERT_NO_THROW(cell_unit.getAttributes());

  // calling getExpandedCell() before expandUnit() should cause error
  Moose::UnitUtils::assertThrows([&cell_unit]() { cell_unit.getExpandedCell(); },
                                 "getExpandedCell() cannot be called on CSGCellEngUnit");

  /* Test the CSGCell-related functionality */
  // getFillType - should be "VOID"
  ASSERT_EQ("VOID", cell_unit.getFillType());
  // getRegion - should be empty
  ASSERT_EQ(CSGRegion(), cell_unit.getRegion());
  // setName() should be functioning through CSGCell
  std::string new_name = "new_name";
  cell_unit.setName(new_name);
  ASSERT_EQ(new_name, cell_unit.getName());

  /* Test the expandUnit() functionality */
  auto csg_obj = std::make_unique<CSGBase>();
  cell_unit.expandUnit(*csg_obj);
  // check getExpandedCell is same object as cell in csg_obj
  ASSERT_EQ(&cell_unit.getExpandedCell(), &csg_obj->getCellByName(new_name + "_real_cell"));
}

/// Test CSGUniverseEngUnit functionality as CSGEngUnit and CSGUniverse
TEST(CSGEngUnitTest, testUnivUnit)
{
  std::string name = "univ_unit";
  FakeUnivEngUnit univ_unit(name);

  /* Test the Engineering Unit related functionality (pre-expansion) */
  ASSERT_EQ(name, univ_unit.getName());
  ASSERT_EQ("UNIVERSE", univ_unit.getBehavior());
  ASSERT_EQ("CSG::FakeUnivEngUnit", univ_unit.getUnitType());

  // attributes - should not cause any error (contents don't matter for this unit test)
  ASSERT_NO_THROW(univ_unit.getAttributes());

  // calling getExpandedUniverse() before expandUnit() should cause error
  Moose::UnitUtils::assertThrows([&univ_unit]() { univ_unit.getExpandedUniverse(); },
                                 "getExpandedUniverse() cannot be called on CSGUniverseEngUnit");

  /* Test the CSGUniverse-related functionality */
  // no cells at all, calls to add or remove cells are disabled
  ASSERT_EQ(0, univ_unit.getAllCells().size());
  ASSERT_FALSE(univ_unit.isRoot());
  // setName() should be functioning through CSGCell
  std::string new_name = "new_name";
  univ_unit.setName(new_name);
  ASSERT_EQ(new_name, univ_unit.getName());

  /* Test the expandUnit() functionality */
  auto csg_obj = std::make_unique<CSGBase>();
  univ_unit.expandUnit(*csg_obj);
  // expanded universe should be same object as one in base
  ASSERT_EQ(&univ_unit.getExpandedUniverse(), &csg_obj->getUniverseByName(new_name + "_real_univ"));
}

/**
 * Tests for the correctness of the N-sided regular polygon engineering unit.
 * Using N = 4 (square) for tests.
 */

/// test the polygon unit properties
TEST(CSGEngUnitTest, testPolygonUnitProperties)
{
  // create unit
  int num_sides = 4;
  Real apothem = 5.0;
  CSGNPolygonUnit sq("test_square", num_sides, apothem);

  // attributes and properties
  std::unordered_map<std::string, AttributeVariant> exp_attrs = {{"apothem", apothem},
                                                                 {"num_sides", num_sides}};
  ASSERT_EQ(exp_attrs, sq.getAttributes());
  ASSERT_EQ("test_square", sq.getName());
  ASSERT_EQ("SURFACE", sq.getBehavior());
  ASSERT_EQ("CSG::CSGNPolygonUnit", sq.getUnitType());
  ASSERT_EQ(num_sides, sq.getNumSides());
  ASSERT_EQ(apothem, sq.getApothem());
  // side length = 2*apothem for square
  ASSERT_TRUE(MooseUtils::absoluteFuzzyEqual(2.0 * apothem, sq.getSideLength()));
  // expected circumradius formed by right triangle of apothems = sqrt(a^2 + a^2) = a*sqrt(2)
  Real exp_r = std::sqrt(2.0) * apothem;
  ASSERT_TRUE(MooseUtils::absoluteFuzzyEqual(exp_r, sq.getRadius()));
}

/// test evaluateSurfaceEquationAtPoint
TEST(CSGEngUnitTest, testPolygonUnitSurfaceEval)
{
  // create unit
  int num_sides = 4;
  Real apothem = 5.0;
  CSGNPolygonUnit sq("test_square", num_sides, apothem);

  // evaluate surface equation at point: test a point inside and 4 outside (one outside each face)
  // we only need to test that it correctly determines positive vs negative evaluation
  Point p_in(1.0, 1.0, 1.0);
  ASSERT_TRUE(0.0 > sq.evaluateSurfaceEquationAtPoint(p_in));
  std::vector<Point> p_out = {{6.0, 0.0, 0.0}, {0.0, 6.0, 0.0}, {-6.0, 0.0, 0.0}, {0.0, -6.0, 0.0}};
  for (auto p : p_out)
    ASSERT_TRUE(0.0 < sq.evaluateSurfaceEquationAtPoint(p));
}

/// test expandUnit
TEST(CSGEngUnitTest, testPolygonUnitExpansion)
{
  // create unit
  int num_sides = 4;
  Real apothem = 5.0;
  CSGNPolygonUnit sq("test_square", num_sides, apothem);

  // expand the unit
  auto csg_obj = std::make_unique<CSGBase>();
  sq.expandUnit(*csg_obj);
  auto region = sq.getExpandedRegion();

  // build expected identical surface coeffients to test equality. Maps expected surface name to the
  // expected coefficients
  std::unordered_map<std::string, std::unordered_map<std::string, Real>> exp_coeffs;
  std::vector<Real> a = {1.0, 0.0, -1.0, 0.0};
  std::vector<Real> b = {0.0, 1.0, 0.0, -1.0};
  for (int k = 0; k < num_sides; k++)
  {
    std::string name = "test_square_exp_" + std::to_string(k);
    std::unordered_map<std::string, Real> coeffs = {
        {"a", a[k]}, {"b", b[k]}, {"c", 0.0}, {"d", apothem}};
    exp_coeffs.emplace(name, coeffs);
  }

  // check region surfaces using a coefficient check that uses fuzzy equal because the coefficients
  // are calcualted using sin/cos in the implementation which may create non-zero "zero" values
  // of ~1e-17.
  auto reg_surfs = region.getSurfaces();
  ASSERT_EQ(num_sides, reg_surfs.size());
  for (const auto & rs : reg_surfs)
  {
    const CSGSurface & surf = rs.get();
    auto exp_c = exp_coeffs.find(surf.getName());
    for (const auto & [k, v] : surf.getCoeffs())
      ASSERT_TRUE(MooseUtils::absoluteFuzzyEqual(v, exp_c->second.at(k)));
  }
}

/// test the clone method
TEST(CSGEngUnitTest, testPolygonUnitClone)
{
  int num_sides = 4;
  Real apothem = 5.0;
  CSGNPolygonUnit sq("test_square", num_sides, apothem);
  auto clone_ptr = sq.clone();
  const CSGEngUnit & clone_eng = dynamic_cast<const CSGEngUnit &>(*clone_ptr);
  ASSERT_TRUE(static_cast<const CSGEngUnit &>(sq) == clone_eng);
}

/// error checks during construction
TEST(CSGEngUnitTest, testPolygonUnitErrors)
{
  // expect error if try to make polygon with less than 3 sides
  Moose::UnitUtils::assertThrows([]() { CSGNPolygonUnit p("name", 1, 1.0); },
                                 "must have 3 or more sides.");
  // expect error if apothem is less than 0.0
  Moose::UnitUtils::assertThrows([]() { CSGNPolygonUnit p("name", 3, -1.0); },
                                 "apothem must be positive.");
}

/// test equality operators
TEST(CSGEngUnitTest, testEngUnitEqual)
{
  // use polygon unit to check equality
  CSGNPolygonUnit u1("thelma", 4.0, 1.0);
  CSGNPolygonUnit u2("thelma", 4.0, 1.0); // identical

  // check == operator
  ASSERT_TRUE(u1 == u2);

  // make units that differ from u1 by different features
  // update u2 so it differs from u1 by transformation
  u2.addTransformation(TransformationType::TRANSLATION, std::make_tuple(1.0, -2.0, 3.0));
  FakeSurfEngUnit u3("thelma");           // differs from u1 by unit type (same name and behavior)
  FakeCellEngUnit u4("thelma");           // differs from u1 by behavior
  CSGNPolygonUnit u5("louise", 4.0, 1.0); // differs from u1 by name
  CSGNPolygonUnit u6("thelma", 3.0, 4.0); // differs from u1 by attributes

  // u5 and u6 should differ from u1 without having to cast
  ASSERT_TRUE(u1 != u5);
  ASSERT_TRUE(u1 != u6);

  // cast all to basic CSGEngUnit type to be able to compare across types (compilation error if
  // object types are different)
  const CSGEngUnit & eng_u1 = u1;
  ASSERT_TRUE(eng_u1 != static_cast<const CSGEngUnit &>(u2));
  ASSERT_TRUE(eng_u1 != static_cast<const CSGEngUnit &>(u3));
  ASSERT_TRUE(eng_u1 != static_cast<const CSGEngUnit &>(u4));
  ASSERT_TRUE(eng_u1 != static_cast<const CSGEngUnit &>(u5));
  ASSERT_TRUE(eng_u1 != static_cast<const CSGEngUnit &>(u6));
}

} // namespace CSG
