#!/bin/bash

# If $METHOD is not set, use opt
if [ -z $METHOD ]; then
  export METHOD=opt
fi

if [ -e ./unit/moose_unit-$METHOD ]
then
  ./unit/moose_unit-$METHOD
elif [ -e ./moose_unit-$METHOD ]
then
  ./moose_unit-$METHOD
else
  echo "Executable missing!"
  exit 1
fi
