#!/bin/bash
# This script runs mooseunit on systems where it can run (not Icestorm)
#

if [ "`hostname -s`" == "service0" ]
then
  echo "Did NOT run mooseunit because this is icestorm"
else
  echo "Running mooseunit because this is NOT icestorm"
  if [ -e ./moose_unit/moose_unit-opt ]
  then
    ./moose_unit/moose_unit-opt
  else
    echo "Executable missing!"
    exit 1
  fi
fi
