# Common pinnings shared across all moose-built conda packages
#
# Many of these should generally follow those
# from conda-forge-pinning when possible

#
# Python
#

python:
  - 3.14
  - 3.13
  - 3.12
  - 3.11
  - 3.10

moose_python_constrained:
  - python >=3.10,<3.15

#
# MPI
#

mpi:
  - mpich
  - openmpi                                                 # [linux or (osx and arm64)]

mpi_version:
  - 5.0.1
  - 5.0.10                                                  # [linux or (osx and arm64)]

mpi_friendly_name:
  - MPICH
  - OpenMPI                                                 # [linux or (osx and arm64)]

zip_keys:
  - mpi
  - mpi_version
  - mpi_friendly_name

# Should match the first zipped item in mpi_version above; used by the moose
# and app conda install that just builds with mpich
mpich_version:
  - 5.0.1

# libfabric 2.5.1 on linux has an undefined reference to
# getrandom@GLIBC_2.25 during builds due to the 2.25 sysroot
# bump in conda-forge/libfabric-feedstock#42
libfabric:
  - <2.5.1

#
# Compilers from conda-forge-pinning
#
# Should update regularly to keep pins in line with other
# conda-forge packages
#

c_compiler:
  - gcc                                                     # [linux]
  - clang                                                   # [osx]
c_compiler_version:
  - 14                                                      # [linux]
  - 19                                                      # [osx]

cxx_compiler:
  - gxx                                                     # [linux]
  - clangxx                                                 # [osx]
cxx_compiler_version:
  - 14                                                      # [linux]
  - 19                                                      # [osx]

fortran_compiler:
  - gfortran
fortran_compiler_version:
  - 14

#
# Packages from conda-forge-pinning that we use
#
# Should update regularly to keep pins in line with other
# conda-forge packages
#

bzip2:
  - 1
fmt:
  - '12.1'
hdf5:
  - 1.14.6
krb5:
  - '1.22'
libaec:
  - '1'
libcap:
  - '2.77'
libcurl:
  - 8
libffi:
  - '3.5'
libhwloc:
  - 2.13.0
libiconv:
  - 1
libssh2:
  - 1
libuuid:
  - 2
libxcb:
  - '1'
libxml2:
  - '2.14'
ncurses:
  - 6
openssl:
  - '3.5'
perl:
  - 5.32.1
readline:
  - "8"
ucc:
  - 1
ucx:
  - '1.20'
xz:
  - 5
zlib:
  - 1
zstd:
  - '1.5'

#
# System root
#

CONDA_BUILD_SYSROOT:                                        # [osx]
  - /opt/conda-sdks/MacOSX13.3.sdk                          # [osx]

c_stdlib:
  - sysroot                                                 # [linux]
  - macosx_deployment_target                                # [osx]

c_stdlib_version:
  - 2.17                                                    # [linux]
  - 13.3                                                    # [osx]
