package:
  name: moose-petsc
  version: __VERSIONER_PETSC_VERSION__

source:
  - path: ../../petsc
  - path: ../../scripts/configure_petsc.sh
  - path: ../functions/retry_build.sh
  - patches:
      - no-cppflags-in-pkgconfig-cflags.patch

build:
  number: __VERSIONER_PETSC_BUILD_NUMBER__
  string: {{ mpi }}___VERSIONER_PETSC_BUILD_NUMBER__
  skip: true  # [win]
  script_env:
    - MOOSE_JOBS
    - REQUESTS_CA_BUNDLE
    - SSL_CERT_FILE
    - CURL_CA_BUNDLE
  run_exports:
    - {{ pin_subpackage('moose-petsc', max_pin='x.x')}}

requirements:
  build:
    - {{ mpi }}
    - {{ moose_mpi }}
    - pkg-config
  run:
    - {{ mpi }}
    - {{ moose_mpi }}
    - pkg-config

test:
  requires:
    - pkg-config
    - {{ mpi }}
    - {{ moose_mpi }}
  files:
    - tests/ex1.c
    - tests/ex1f.F90
    - tests/makefile
  commands:
    - pkg-config --validate PETSc
    - pkg-config --cflags PETSc
    - pkg-config --libs PETSc

about:
  home: https://petsc.org
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD 2-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - milljm
    - cticenhour
