#!/bin/bash
#PBS -N <JOB_NAME>
#PBS -l select=<NCPUS_PER_CHUNK>
#PBS -l place=<PLACE>
#PBS -l walltime=<WALLTIME>
<PBS_PREREQ>
<PBS_PROJECT>
<SOFT_LINK1>
<COMBINE_STREAMS>
cd <PBS_O_WORKDIR>

JOB_NUM=${PBS_JOBID%\.*}
<SOFT_LINK2>

export MV2_ENABLE_AFFINITY=0

<COMMAND>

<SOFT_LINK3>
