#!/bin/bash
# This script moves the html and required resources for the test timing website
# and rsyncs them to hpcsc
#
# It assumes that ./moose/scripts/timingHTML/timing_utils has already been run
# to generate the json data

mkdir -p html  # this should have already been made for the json data

cp moose/scripts/timingHTML/index.html html/
cp -r moose/scripts/timingHTML/resources html/

# rsync everything but the svn files
find html -type d -name ".svn" -depth -exec rm -rf {} \;
rsync -ro html/* hpcsc:/srv/www/ssl/MOOSE/timing/
rsync -r html/* moosebuild.com:/var/documents/MOOSE/timing/
