//* This file is part of the MOOSE framework
//* https://www.mooseframework.org
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#include "CombineDisjoinedComponent.h"
#include "MooseApp.h"
#include "MooseMesh.h"
#include "ActionWarehouse.h"
#include "MeshGeneratorSystem.h"
#include "ComponentAction.h"

registerMooseAction("MooseApp", CombineDisjoinedComponent, "append_mesh_generator");

InputParameters
CombineDisjoinedComponent::validParams()
{
  InputParameters params = Action::validParams();
  params.addClassDescription("Combines meshes generated by disjoined components.");
  return params;
}

CombineDisjoinedComponent::CombineDisjoinedComponent(const InputParameters & params)
  : Action(params)
{
}

void
CombineDisjoinedComponent::act()
{
  // Create the mesh generator to combine them
  if (_current_task == "append_mesh_generator")
  {
    // Get the list of components
    std::vector<MeshGeneratorName> combined;
    std::vector<const ComponentAction *> components = _awh.getActions<ComponentAction>();
    for (const auto comp : components)
      combined.push_back(comp->meshName());

    // TODO once we have junctions
    // Get the list of disconnected components
    // Solve for disjoint groups

    // Add the main mesh from the Mesh block, might as well
    const auto final_mg = _app.getMeshGeneratorSystem().getFinalMeshGeneratorName();
    // but only if no component are already defined on it
    if (std::find(combined.begin(), combined.end(), final_mg) == combined.end())
      combined.push_back(final_mg);
    if (final_mg == "")
      mooseError("Final mesh generator should be set");

    // Combine everyone into a combiner
    InputParameters params = _factory.getValidParams("CombinerGenerator");
    params.set<std::vector<MeshGeneratorName>>("inputs") = combined;
    params.set<bool>("avoid_merging_subdomains") = true;
    params.set<bool>("avoid_merging_boundaries") = true;
    params.set<bool>("output") = true;

    _app.getMeshGeneratorSystem().appendMeshGenerator(
        "CombinerGenerator", "component_combiner", params);
  }
  else
    mooseError("Registered to a task but not doing anything on that task");
}
