//* This file is part of the MOOSE framework
//* https://www.mooseframework.org
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#include "CombineComponentsMeshes.h"
#include "MooseApp.h"
#include "MooseMesh.h"
#include "ActionWarehouse.h"
#include "MeshGeneratorSystem.h"
#include "ActionComponent.h"

registerMooseAction("MooseApp", CombineComponentsMeshes, "append_mesh_generator");

InputParameters
CombineComponentsMeshes::validParams()
{
  InputParameters params = Action::validParams();
  params.addClassDescription("Combines meshes generated by disjoined components.");
  return params;
}

CombineComponentsMeshes::CombineComponentsMeshes(const InputParameters & params) : Action(params) {}

void
CombineComponentsMeshes::act()
{
  // Create the mesh generator to combine them
  if (_current_task == "append_mesh_generator")
  {
    // Get the list of components
    std::vector<MeshGeneratorName> combined;
    std::vector<const ActionComponent *> components = _awh.getActions<ActionComponent>();
    for (const auto comp : components)
      combined.push_back(comp->meshGeneratorName());

    // TODO once we have junctions
    // Get the list of disconnected components
    // Solve for disjoint groups

    // Add the main mesh from the Mesh block
    bool all_mgs_from_components = true;
    const auto final_mg = _app.getMeshGeneratorSystem().getFinalMeshGeneratorName();
    if (_app.getMeshGeneratorSystem().getMeshGeneratorNames().size())
    {
      // Check that there are mesh generators that do not come from Components
      for (const auto & mg : _app.getMeshGeneratorSystem().getMeshGeneratorNames())
        if (std::find(combined.begin(), combined.end(), mg) == combined.end())
          all_mgs_from_components = false;
      // If a component is already defined on the final MG, no need to add it
      if (final_mg != "" && std::find(combined.begin(), combined.end(), final_mg) == combined.end())
        combined.push_back(final_mg);
      if (final_mg == "" && !all_mgs_from_components)
        mooseError("Final mesh generator should be set for Mesh+Components to work together");
    }

    // Combine everyone into a combiner
    InputParameters params = _factory.getValidParams("CombinerGenerator");
    params.set<std::vector<MeshGeneratorName>>("inputs") = combined;
    params.set<bool>("avoid_merging_subdomains") = true;
    params.set<bool>("avoid_merging_boundaries") = true;
    params.set<bool>("output") = true;

    // Single component case
    if (combined.size() == 1)
      params.set<std::vector<Point>>("positions") = {Point(0, 0, 0)};

    // Replace the current final MG if there are mesh generators
    if (!all_mgs_from_components)
      _app.getMeshGeneratorSystem().appendMeshGenerator(
          "CombinerGenerator", "component_combiner", params);
    else
    // No mesh generators somehow
    {
      _app.getMeshGeneratorSystem().addMeshGenerator(
          "CombinerGenerator", "component_combiner", params);
    }
  }
  else
    mooseError("Registered to a task but not doing anything on that task");
}
