//* This file is part of the MOOSE framework
//* https://www.mooseframework.org
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#include "CombineComponentsMeshes.h"
#include "MooseApp.h"
#include "MooseMesh.h"
#include "ActionWarehouse.h"
#include "MeshGeneratorSystem.h"
#include "ActionComponent.h"

registerMooseAction("MooseApp", CombineComponentsMeshes, "append_mesh_generator");

InputParameters
CombineComponentsMeshes::validParams()
{
  InputParameters params = Action::validParams();
  params.addClassDescription("Combines meshes generated by disjoined components.");
  return params;
}

CombineComponentsMeshes::CombineComponentsMeshes(const InputParameters & params) : Action(params) {}

void
CombineComponentsMeshes::act()
{
  // Create the mesh generator to combine them
  if (_current_task == "append_mesh_generator")
  {
    // Get the list of components meshes (from their last mesh generators)
    std::vector<MeshGeneratorName> all_components_mgs;
    std::vector<MeshGeneratorName> mgs_to_combine;
    std::vector<const ActionComponent *> components = _awh.getActions<ActionComponent>();
    for (const auto comp : components)
    {
      // Keep track of all mesh generators used in components
      for (const auto & mg_name : comp->meshGeneratorNames())
        all_components_mgs.push_back(mg_name);
      if (comp->meshGeneratorNames().size())
        mgs_to_combine.push_back(comp->meshGeneratorNames().back());
    }

    // TODO once we have junctions
    // - Get the list of disconnected components
    // - Find the disjoint groups
    // - Use a combiner generators on the vector of disjoint groups

    // Add the main mesh from the Mesh block, only if it was not already used in
    // making component meshes
    bool all_mgs_from_components = true;
    const auto final_mg = _app.getMeshGeneratorSystem().getFinalMeshGeneratorName();
    if (_app.getMeshGeneratorSystem().getMeshGeneratorNames().size())
    {
      // Check whether there are mesh generators that do not come from Components
      for (const auto & mg : _app.getMeshGeneratorSystem().getMeshGeneratorNames())
        if (std::find(all_components_mgs.begin(), all_components_mgs.end(), mg) ==
            all_components_mgs.end())
          all_mgs_from_components = false;

      // If a component is already defined on the final mesh MG, no need to add it
      if (final_mg != "" &&
          std::find(all_components_mgs.begin(), all_components_mgs.end(), final_mg) ==
              all_components_mgs.end())
        mgs_to_combine.push_back(final_mg);
      if (final_mg == "" && !all_mgs_from_components)
        mooseError("Final mesh generator should be set for [Mesh] and [ActionComponents] to work "
                   "together");
    }

    // Combine everyone into a combiner
    InputParameters params = _factory.getValidParams("CombinerGenerator");
    params.set<std::vector<MeshGeneratorName>>("inputs") = mgs_to_combine;
    params.set<bool>("avoid_merging_subdomains") = true;
    params.set<bool>("avoid_merging_boundaries") = true;
    params.set<bool>("output") = true;

    // Single component case
    if (mgs_to_combine.size() == 1)
      params.set<std::vector<Point>>("positions") = {Point(0, 0, 0)};

    // Replace the current final MG if there are mesh generators
    if (!all_mgs_from_components)
      _app.getMeshGeneratorSystem().appendMeshGenerator(
          "CombinerGenerator", "component_combiner", params);
    else
    // No mesh generators somehow
    {
      _app.getMeshGeneratorSystem().addMeshGenerator(
          "CombinerGenerator", "component_combiner", params);
    }
  }
  else
    mooseAssert(false, "Registered to a task but not doing anything on that task");
}
