mpi:
  - mpich
  - openmpi

mpi_version:
  # MPICH version
  - 4.3.2
  # OpenMPI version
  - 5.0.10

mpi_friendly_name:
  - MPICH
  - OpenMPI

mpi_website:
  - http://www.mpich.org/documentation/guides
  - https://www.open-mpi.org/doc/

mpi_dev_website:
  - https://github.com/pmodels/mpich
  - https://github.com/open-mpi/ompi

zip_keys:
  - mpi
  - mpi_version
  - mpi_friendly_name
  - mpi_website
  - mpi_dev_website
