Content:
    - framework/doc/content
    - modules/shallow_water/doc/content
Renderer:
    type: MooseDocs.base.MaterializeRenderer
Extensions:
    MooseDocs.extensions.navigation:
        name: shallow_water
        repo: https://github.com/idaholab/moose
        home: /modules/shallow_water
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/shallow_water
        remove: !include ${MOOSE_DIR}/framework/doc/remove.yml
        includes:
            - framework/include
            - modules/shallow_water/include
    MooseDocs.extensions.common:
        shortcuts: !include ${MOOSE_DIR}/framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
    MooseDocs.extensions.sqa:
        active: true
        reports: !include ${ROOT_DIR}/modules/shallow_water/doc/sqa_reports.yml
        categories:
            framework: !include ${MOOSE_DIR}/framework/doc/sqa_framework.yml
            shallow_water: !include ${ROOT_DIR}/modules/shallow_water/doc/sqa_shallow_water.yml
    MooseDocs.extensions.template:
        active: true
