# Gaussian Process surrogate with penalty constraints trained from CSV files.
#
# Required files generated by generate_gp_data.py:
#
#   train.csv : columns x,y
#   test.csv  : columns x,y_true
#
# Function:
#
#   f(x) = 1/(1+(10*x)^4) + 0.5*exp(-100*(x-0.5)^2)
#
# Domain:
#
#   x in [0,1]

[StochasticTools]
[]

[Samplers]
  # Training inputs.
  # This reads only the x column from train.csv.
  [train_sample]
    type = CSVSampler
    samples_file = 'train.csv'
    column_names = 'x'
    execute_on = initial
  []

  # Testing inputs.
  # This reads only the x column from test.csv.
  # Do not read y_true into this sampler, because the GP input is 1-D.
  [test_sample]
    type = CSVSampler
    samples_file = 'test.csv'
    column_names = 'x'
    execute_on = initial
  []
[]

[VectorPostprocessors]
  # Reads training x and y values from train.csv.
  #
  # DO NOT set execute_on here.
  # CSVReaderVectorPostprocessor suppresses execute_on internally.
  [train_data]
    type = CSVReaderVectorPostprocessor
    csv_file = 'train.csv'
    header = true
  []

  # Reads testing x and y_true values from test.csv.
  #
  # DO NOT set execute_on here.
  [test_data]
    type = CSVReaderVectorPostprocessor
    csv_file = 'test.csv'
    header = true
  []
[]

[Reporters]
  # GP prediction and standard deviation on the test points.
  [samp_avg]
    type = EvaluateSurrogate
    model = GP_avg
    sampler = test_sample
    evaluate_std = true
    parallel_type = ROOT
    execute_on = final
  []

  # Optional: GP prediction and standard deviation on the training points.
  # This is useful for checking interpolation/fit quality.
  [train_avg]
    type = EvaluateSurrogate
    model = GP_avg
    sampler = train_sample
    evaluate_std = true
    parallel_type = ROOT
    execute_on = final
  []
[]

[Trainers]
  [GP_avg_trainer]
    type = GaussianProcessTrainer
    execute_on = timestep_end

    covariance_function = 'covar'

    standardize_params = true
    standardize_data = true

    # Predictor data comes from train_sample, which reads train.csv column x.
    sampler = train_sample

    # Response data comes from train.csv column y through train_data.
    response = train_data/y

    # Official MOOSE syntax uses the covariance object prefix.
    tune_parameters = 'covar:signal_variance covar:noise_variance covar:length_factor'

    # If your local penalty-constraint branch expects bare names instead,
    # replace the line above with:
    #
    # tune_parameters = 'signal_variance noise_variance length_factor'

    tuning_min = '1e-8 1e-10 1e-3'
    tuning_max = '10   1e-2  10'

    num_iters = 500
    batch_size = 20
    learning_rate = 0.005

    # Penalty constraints for this positive analytic function.
    # Since f(x) >= 0 on [0,1], these are non-negativity constraints.
    penalty_constraint_points = '0.0
                                 0.25
                                 0.5
                                 0.75
                                 1.0'

    penalty_constraint_lower_bounds = '0.0 0.0 0.0 0.0 0.0'
    penalty_weight = 10.0
  []
[]

[Surrogates]
  [GP_avg]
    type = GaussianProcessSurrogate
    trainer = GP_avg_trainer
  []
[]

[Covariance]
  [covar]
    type = SquaredExponentialCovariance
    signal_variance = 1
    noise_variance = 1e-6
    length_factor = '0.2'
  []
[]

[Outputs]
  [out]
    type = CSV
    execute_on = final
  []
[]
