//* This file is part of the MOOSE framework
//* https://www.mooseframework.org
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#include "ImplicitStateful.h"

registerMooseObject("MooseTestApp", ImplicitStateful);

InputParameters
ImplicitStateful::validParams()
{
  InputParameters params = Material::validParams();
  params.addRequiredParam<std::string>("prop_name",
                                       "name of property to be generated by this material");
  params.addRequiredParam<std::string>(
      "coupled_prop_name",
      "name of a property for which Old/Older stateful values will be used as prop_name's value");
  params.addRequiredParam<bool>(
      "add_time", "true to add the current sim time to the value of the prop_name property");
  params.addRequiredParam<bool>("older",
                                "true to use couple_prop_name older values instead of old");
  return params;
}

ImplicitStateful::ImplicitStateful(const InputParameters & parameters)
  : Material(parameters),
    _add_time(getParam<bool>("add_time")),
    _use_older(getParam<bool>("older")),
    _prop(declareProperty<Real>(getParam<std::string>("prop_name"))),
    _coupled_old(getMaterialPropertyOld<Real>(getParam<std::string>("coupled_prop_name"))),
    _coupled_older(getMaterialPropertyOlder<Real>(getParam<std::string>("coupled_prop_name")))
{
}

void
ImplicitStateful::initQpStatefulProperties()
{
  _prop[_qp] = 0;
}

void
ImplicitStateful::computeQpProperties()
{
  if (_use_older)
    _prop[_qp] = _coupled_older[_qp];
  else
    _prop[_qp] = _coupled_old[_qp];

  if (_add_time)
    _prop[_qp] = _prop[_qp] + _fe_problem.timeStep();
}
