/****************************************************************/
/*               DO NOT MODIFY THIS HEADER                      */
/* MOOSE - Multiphysics Object Oriented Simulation Environment  */
/*                                                              */
/*           (c) 2010 Battelle Energy Alliance, LLC             */
/*                   ALL RIGHTS RESERVED                        */
/*                                                              */
/*          Prepared by Battelle Energy Alliance, LLC           */
/*            Under Contract No. DE-AC07-05ID14517              */
/*            With the U. S. Department of Energy               */
/*                                                              */
/*            See COPYRIGHT for full restrictions               */
/****************************************************************/
#include "ImplicitStateful.h"

template <>
InputParameters
validParams<ImplicitStateful>()
{
  InputParameters params = validParams<Material>();
  params.addRequiredParam<std::string>("prop_name",
                                       "name of property to be generated by this material");
  params.addRequiredParam<std::string>(
      "coupled_prop_name",
      "name of a property for which Old/Older stateful values will be used as prop_name's value");
  params.addRequiredParam<bool>(
      "add_time", "true to add the current sim time to the value of the prop_name property");
  params.addRequiredParam<bool>("older",
                                "true to use couple_prop_name older values instead of old");
  return params;
}

ImplicitStateful::ImplicitStateful(const InputParameters & parameters)
  : Material(parameters),
    _add_time(getParam<bool>("add_time")),
    _use_older(getParam<bool>("older")),
    _prop(declareProperty<Real>(getParam<std::string>("prop_name"))),
    _coupled_old(getMaterialPropertyOld<Real>(getParam<std::string>("coupled_prop_name"))),
    _coupled_older(getMaterialPropertyOlder<Real>(getParam<std::string>("coupled_prop_name")))
{
}

void
ImplicitStateful::initQpStatefulProperties()
{
  _prop[_qp] = 0;
}

void
ImplicitStateful::computeQpProperties()
{
  if (_use_older)
    _prop[_qp] = _coupled_older[_qp];
  else
    _prop[_qp] = _coupled_old[_qp];

  if (_add_time)
    _prop[_qp] = _prop[_qp] + _fe_problem.timeStep();
}
