//* This file is part of the MOOSE framework
//* https://mooseframework.inl.gov
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#pragma once

#include "Material.h"
#include "DerivativeMaterialInterface.h"
#include "MathUtils.h"

/**
 * Computes the cost sensitivity for SIMP optimization algorithms that consider a cost constraint,
 * in addition to a volume constraint.
 */
class CostSensitivity : public DerivativeMaterialInterface<Material>
{
public:
  static InputParameters validParams();

  CostSensitivity(const InputParameters & parameters);

  virtual void computeQpProperties() override;

protected:
  /// Base name of the material system
  const std::string _base_name;
  /// The cost sensitivity material generated by this object
  MaterialProperty<Real> & _sensitivity;
  /// Pseudo-density variable
  const VariableValue & _design_density;
  /// Pseudo-density variable name
  const MaterialPropertyName _design_density_name;
  /// Derivative of the cost with respect to the pseudo-density variable
  const MaterialProperty<Real> & _dcostdrho;
  /// Cost material property
  const MaterialProperty<Real> & _cost;
};
