//* This file is part of the MOOSE framework
//* https://www.mooseframework.org
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#include "GlobalDisplacementAux.h"

// MOOSE includes
#include "Assembly.h"
#include "SystemBase.h"
#include "RankTwoTensor.h"

registerMooseObject("TensorMechanicsApp", GlobalDisplacementAux);

template <>
InputParameters
validParams<GlobalDisplacementAux>()
{
  InputParameters params = validParams<AuxKernel>();
  params.addClassDescription(
      "AuxKernel to visualize the dispalcements generated by the global strain tensor");
  params.addCoupledVar("scalar_global_strain",
                       "Scalar variable providing global strain components");
  params.addCoupledVar("displacements", "The name of the displacement variables");
  params.addRequiredParam<unsigned int>("component",
                                        "The displacement component to consider for this kernel");
  params.addParam<bool>("output_total_displacement", true, "Option to output total displacement");

  return params;
}

GlobalDisplacementAux::GlobalDisplacementAux(const InputParameters & parameters)
  : AuxKernel(parameters),
    _scalar_global_strain(coupledScalarValue("scalar_global_strain")),
    _component(getParam<unsigned int>("component")),
    _output_total_disp(getParam<bool>("output_total_displacement")),
    _ndisp(getParam<bool>("output_total_displacement") ? coupledComponents("displacements") : 0),
    _disp(_ndisp)
{
  if (_component > _mesh.dimension())
    mooseError("The component ",
               _component,
               " does not exist for ",
               _mesh.dimension(),
               " dimensional problems");

  for (unsigned int i = 0; i < _ndisp; ++i)
    _disp[i] = &coupledValue("displacements", i);
}

Real
GlobalDisplacementAux::computeValue()
{
  RankTwoTensor strain;
  strain.fillFromScalarVariable(_scalar_global_strain);

  const RealVectorValue & global_disp = strain * (*_current_node);

  Real value = global_disp(_component);

  if (_output_total_disp)
    value += (*_disp[_component])[_qp];

  return value;
}
