//* This file is part of the MOOSE framework
//* https://www.mooseframework.org
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#include "GlobalDisplacementAux.h"

// MOOSE includes
#include "Assembly.h"
#include "SystemBase.h"
#include "RankTwoTensor.h"

registerMooseObject("TensorMechanicsApp", GlobalDisplacementAux);

template <>
InputParameters
validParams<GlobalDisplacementAux>()
{
  InputParameters params = validParams<AuxKernel>();
  params.addClassDescription(
      "AuxKernel to visualize the dispalcements generated by the global strain tensor");
  params.addParam<std::string>("base_name", "Base name for the material property");
  params.addParam<unsigned int>("component", 0, "The vector component to consider for this kernel");

  return params;
}

GlobalDisplacementAux::GlobalDisplacementAux(const InputParameters & parameters)
  : AuxKernel(parameters),
    _base_name(isParamValid("base_name") ? getParam<std::string>("base_name") + "_" : ""),
    _global_strain(getMaterialProperty<RankTwoTensor>(_base_name + "global_strain")),
    _component(getParam<unsigned int>("component")),
    _global_disp(_mesh.dimension())
{
  if (_component > _mesh.dimension())
    mooseError("The component ",
               _component,
               " does not exist for ",
               _mesh.dimension(),
               " dimensional problems");
}

Real
GlobalDisplacementAux::computeValue()
{
  _global_disp = _global_strain[_qp] * _q_point[_qp];

  return _global_disp(_component);
}
