//* This file is part of the MOOSE framework
//* https://www.mooseframework.org
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#include "GlobalDisplacementAux.h"
#include "GlobalStrainUserObject.h"

// MOOSE includes
#include "Assembly.h"
#include "SystemBase.h"
#include "RankTwoTensor.h"

registerMooseObject("TensorMechanicsApp", GlobalDisplacementAux);

template <>
InputParameters
validParams<GlobalDisplacementAux>()
{
  InputParameters params = validParams<AuxKernel>();
  params.addClassDescription(
      "AuxKernel to visualize the dispalcements generated by the global strain tensor");
  params.addCoupledVar("scalar_global_strain",
                       "Scalar variable providing global strain components");
  params.addCoupledVar("displacements", "The name of the displacement variables");
  params.addRequiredParam<unsigned int>("component",
                                        "The displacement component to consider for this kernel");
  params.addParam<bool>(
      "output_global_displacement", false, "Option to output global displacement only");
  params.addRequiredParam<UserObjectName>("global_strain_uo",
                                          "The name of the GlobalStrainUserObject");

  return params;
}

GlobalDisplacementAux::GlobalDisplacementAux(const InputParameters & parameters)
  : AuxKernel(parameters),
    _scalar_global_strain(coupledScalarValue("scalar_global_strain")),
    _component(getParam<unsigned int>("component")),
    _output_global_disp(getParam<bool>("output_global_displacement")),
    _pst(getUserObject<GlobalStrainUserObject>("global_strain_uo")),
    _periodic_dir(_pst.getPeriodicDirections()),
    _dim(_mesh.dimension()),
    _ndisp(coupledComponents("displacements")),
    _disp(_ndisp)
{
  if (_component >= _dim)
    paramError("The component ", _component, " does not exist for ", _dim, " dimensional problems");

  for (unsigned int i = 0; i < _ndisp; ++i)
    _disp[i] = &coupledValue("displacements", i);
}

Real
GlobalDisplacementAux::computeValue()
{
  RankTwoTensor strain;
  strain.fillFromScalarVariable(_scalar_global_strain);

  for (unsigned int dir = 0; dir < _dim; ++dir)
    if (!_periodic_dir(dir))
      for (unsigned int var = 0; var < _ndisp; ++var)
        strain(dir, var) = 0.0;

  const RealVectorValue & global_disp = strain * (*_current_node);

  if (_output_global_disp)
    return global_disp(_component);
  else
    return global_disp(_component) + (*_disp[_component])[_qp];
}
