//* This file is part of the MOOSE framework
//* https://www.mooseframework.org
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#include "TotalDisplacementAux.h"

// MOOSE includes
#include "Assembly.h"
#include "SystemBase.h"

registerMooseObject("TensorMechanicsApp", TotalDisplacementAux);

template <>
InputParameters
validParams<TotalDisplacementAux>()
{
  InputParameters params = validParams<AuxKernel>();
  params.addClassDescription("AuxKernel to visualize the total dispalcements, combination of "
                             "displacement generated by the global strain tensor and the ones "
                             "solved by stress divergence kernel");
  params.addCoupledVar("displacement_variables",
                       "The name of the displacement variables to combine");

  return params;
}

TotalDisplacementAux::TotalDisplacementAux(const InputParameters & parameters)
  : AuxKernel(parameters), _var_num(coupledComponents("displacement_variables")), _disp(_var_num)
{
  for (unsigned int i = 0; i < _var_num; ++i)
    _disp[i] = &coupledValue("displacement_variables", i);
}

Real
TotalDisplacementAux::computeValue()
{
  Real value = 0.0;
  for (unsigned int i = 0; i < _var_num; ++i)
    value += (*_disp[i])[_qp];

  return value;
}
