# Making a Change to this package?
# REMEMBER TO UPDATE the .yaml files for the following packages:
#   libmesh/
#   template/
#   moose/
{% set build = 0 %}
{% set vtk_version = "9.2.6" %}
{% set vtk_friendly_version = "9.2" %}
{% set sha256 = "06fc8d49c4e56f498c40fcb38a563ed8d4ec31358d0101e8988f0bb4d539dd12" %}

package:
  name: moose-libmesh-vtk
  version: {{ vtk_version }}

source:
  url: https://www.vtk.org/files/release/{{ vtk_friendly_version }}/VTK-{{ vtk_version }}.tar.gz
  vtk_friendly_version: {{ vtk_friendly_version }}
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true             # [win]
  script_env:
    - MOOSE_JOBS
    - vtk_friendly_version={{ vtk_friendly_version }}

requirements:
  build:
    - {{ moose_mpich }}
    - ninja
  run:
    - {{ moose_mpich }}

test:
  commands:
    - test -f $PREFIX/libmesh-vtk/lib/libvtkCommonCore-{{ vtk_friendly_version }}.dylib   # [osx]
    - test -f $PREFIX/libmesh-vtk/lib/libvtkCommonCore-{{ vtk_friendly_version }}.so      # [linux]

about:
  home: http://www.vtk.org/
  license: BSD 3-Clause
  license_file: Copyright.txt
  summary: >
    The Visualization Toolkit (VTK) is an open-source, freely available software
    system for 3D computer graphics, modeling, image processing, volume
    rendering, scientific visualization, and information visualization.

extra:
  recipe-maintainers:
    - milljm
