# Settings guide: https://docs.vtk.org/en/latest/build_instructions/build_settings.html
cmake .. -G "Ninja" \
    -Wno-dev \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_PREFIX_PATH:PATH=${VTK_PREFIX} \
    -DCMAKE_INSTALL_PREFIX:PATH=${VTK_PREFIX} \
    -DCMAKE_INSTALL_RPATH:PATH=${VTK_PREFIX}/lib \
    -DCMAKE_OSX_SYSROOT=${CONDA_BUILD_SYSROOT} \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DBUILD_SHARED_LIBS:BOOL=ON \
    -DVTK_INSTALL_SDK:BOOL=ON \
    -DVTK_ENABLE_REMOTE_MODULES:BOOL=OFF \
    -DVTK_FORBID_DOWNLOADS:BOOL=ON \
    -DVTK_BUILD_DOCUMENTATION:BOOL=OFF \
    -DVTK_BUILD_TESTING:BOOL=OFF \
    -DVTK_BUILD_EXAMPLES:BOOL=OFF \
    -DVTK_BUILD_ALL_MODULES:BOOL=OFF \
    -DVTK_GROUP_ENABLE_Rendering:STRING=DONT_WANT \
    -DVTK_GROUP_ENABLE_Qt:STRING=NO \
    -DVTK_GROUP_ENABLE_Views:STRING=NO \
    -DVTK_GROUP_ENABLE_Web:STRING=NO \
    -DVTK_GROUP_ENABLE_MPI:STRING=DONT_WANT \
    -DVTK_GROUP_ENABLE_Imaging:STRING=DONT_WANT \
    -DVTK_USE_MPI:BOOL=ON \
    -DVTK_MODULE_ENABLE_VTK_IOMPIParallel:STRING=YES \
    -DVTK_MODULE_ENABLE_VTK_IOParallelExodus:STRING=YES \
    -DVTK_MODULE_ENABLE_VTK_IOParallelNetCDF:STRING=YES \
    -DVTK_MODULE_ENABLE_VTK_IOXML:STRING=YES \
    -DVTK_MODULE_ENABLE_VTK_IOXMLParser:STRING=YES \
    -DVTK_MODULE_ENABLE_VTK_IOImage:STRING=YES

ninja install -v -j ${MOOSE_JOBS:-2}
