//* This file is part of the MOOSE framework
//* https://mooseframework.inl.gov
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details

#pragma once

#include "AuxKernel.h"
#include "RankTwoTensorForward.h"

#include <utility>
#include <vector>

class GlobalStrainPeriodicDirUserObject;

/**
 * Computes the affine displacement generated by the split global-strain
 * variables and optionally adds the periodic nonlinear displacement.
 */
class ADGlobalDisplacementAux : public AuxKernel
{
public:
  static InputParameters validParams();

  ADGlobalDisplacementAux(const InputParameters & parameters);

  Real computeValue() override;

protected:
  void assignComponentIndices();
  void validateScalarVariables() const;
  void fillGlobalStrainTensor(RankTwoTensor & strain) const;

  // AuxKernels do not assemble a Jacobian, so Real scalar values are sufficient.
  const VariableValue & _diagonal_global_strain;
  const VariableValue * const _off_diagonal_global_strain;

  const unsigned int _number_of_diagonal_components;
  const unsigned int _number_of_off_diagonal_components;

  const unsigned int _component;
  const bool _output_global_disp;

  const GlobalStrainPeriodicDirUserObject & _periodicity_uo;
  const VectorValue<bool> & _periodic_dir;

  std::vector<std::pair<unsigned int, unsigned int>> _diagonal_components;
  std::vector<std::pair<unsigned int, unsigned int>> _off_diagonal_components;

  const Point _ref_point;
  const unsigned int _dim;
  const unsigned int _ndisp;
  const std::vector<const VariableValue *> _disp;
};
