//* This file is part of the MOOSE framework
//* https://www.mooseframework.org
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#include "TestReactorGeometryMeshBuilderMeshGenerator.h"
#include "ReactorGeometryMeshBuilderBase.h"

registerMooseObject("ReactorTestApp", TestReactorGeometryMeshBuilderMeshGenerator);

InputParameters
TestReactorGeometryMeshBuilderMeshGenerator::validParams()
{
  InputParameters params = MeshGenerator::validParams();
  params.addRequiredParam<MeshGeneratorName>("input", "Input core mesh");
  return params;
}

TestReactorGeometryMeshBuilderMeshGenerator::TestReactorGeometryMeshBuilderMeshGenerator(const InputParameters & params)
  : MeshGenerator(params),
    _input(getParam<MeshGeneratorName>("input")),
    _input_mesh(&getMesh("input"))
{
  // Assumes input has been generated by CoreMeshGenerator and contains valid metadata for generation
  const auto reactor_params_name = getMeshProperty<std::string>(RGMB::reactor_params_name, _input);

  // Get assembly pitch from metadata and define a circular mesh that preserves volume of assembly structure
  const auto assembly_pitch = getMeshProperty<double>(RGMB::assembly_pitch, reactor_params_name);
  const auto mesh_geometry = getMeshProperty<std::string>(RGMB::mesh_geometry, reactor_params_name);
  double vol_multiplier = (mesh_geometry == "Square") ? 1.0 : std::sqrt(3) / 2;
  double equivalent_volume = vol_multiplier * assembly_pitch * assembly_pitch;
  double equivalent_radius = std::sqrt(equivalent_volume / M_PI);

  {
    auto mesh_params = _app.getFactory().getValidParams("AdvancedConcentricCircleGenerator");
    mesh_params.set<std::vector<double>>("ring_radii") = {equivalent_radius};
    mesh_params.set<std::vector<unsigned int>>("ring_intervals") = {1};
    mesh_params.set<unsigned int>("num_sectors") = 8;
    addMeshSubgenerator("AdvancedConcentricCircleGenerator", "eqv_core_circle", mesh_params);

    _build_mesh = &getMeshByName("eqv_core_circle");
  }
}

std::unique_ptr<MeshBase>
TestReactorGeometryMeshBuilderMeshGenerator::generate()
{
  // Input mesh is essentially a data store to build the equivalent core, so we reset it as it is no
  // longer needed. The mesh we care about is the one created by the subgenerator
  _input_mesh->reset();
  return std::move(*_build_mesh);
}
