#ifndef DISTRIBUTION_TYPE_H
#define DISTRIBUTION_TYPE_H

//enum distribution_type { UNIFORM_DISTRIBUTION=1, NORMAL_DISTRIBUTION=2,  LOG_NORMAL_DISTRIBUTION=3, WEIBULL_DISTRIBUTION=4, EXPONENTIAL_DISTRIBUTION=5, GAMMA_DISTRIBUTION=6, BETA_DISTRIBUTION=7, CUSTOM_DISTRIBUTION=8, TRIANGULAR_DISTRIBUTION=9 , DISTRIBUTION_ERROR=-1};

#endif /* DISTRIBUTION_TYPE_H */
