mpi:
  - mpich
  - openmpi

moose_libmesh:
  - moose-libmesh 2025.01.28 mpich_2
  - moose-libmesh 2025.01.28 openmpi_2

moose_wasp:
  - moose-wasp 2024.12.23

moose_tools:
  - moose-tools 2024.12.23

moose_peacock:
  - moose-peacock 2024.12.23

zip_keys:
  - mpi
  - moose_libmesh
