# Making a Change to this package?
# REMEMBER TO UPDATE the .yaml files for the following packages:
#   moose/conda_build_config.yaml
# As well as any directions pertaining to modifying those files.
{% set version = "2025.08.15" %}

package:
  name: moose-dev
  version: {{ version }}

source:
  path: ../moose-dev

build:
  number: 0
  string: {{ mpi }}
  skip: true  # [win]
  script_env:
    - REQUESTS_CA_BUNDLE
    - SSL_CERT_FILE
    - CURL_CA_BUNDLE
    - NODE_EXTRA_CA_CERTS
requirements:
  run:
    - {{ mpi }}
    - {{ moose_tools }}
    - {{ moose_libmesh }}
    - {{ moose_wasp }}

about:
  home: https://mooseframework.inl.gov/
  license: LGPL 2.1
  summary: >
    A simple package which installs all necessary Conda packages for MOOSE based development.

extra:
  recipe-maintainers:
    - milljm
    - cticenhour
    - loganharbour
