name: moose_hit

on: [pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} with ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]

    steps:
      - uses: actions/checkout@v5

      - name: Checkout WASP
        run: git submodule update --init --checkout --recursive framework/contrib/wasp/

      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.1.4

      - name: Build wheels
        run: python -m cibuildwheel framework/contrib/hit/ --output-dir wheelhouse
        env:
          MOOSE_DIR: ${{ github.workspace }}

      - name: List wheels
        run: ls ./wheelhouse/*.whl



