name: "Branch next: Docker"

on:
  pull_request:
    types: [labeled, synchronize, opened, reopened]
    branches: [next]
  push:
    branches: [next]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-slim
    outputs:
      # Base SHA for this event
      base_sha: ${{ steps.checkout.outputs.base_sha }}
      # Whether or not to build a given packages
      mpi_build: ${{ steps.package_context.outputs.mpi_build }}
      petsc_build: ${{ steps.package_context.outputs.petsc_build }}
      libmesh_build: ${{ steps.package_context.outputs.libmesh_build }}
      moose_dev_build: ${{ steps.package_context.outputs.moose_dev_build }}
      # Package tags for building and pulling
      mpi_tag: ${{ steps.package_context.outputs.mpi_tag }}
      petsc_tag: ${{ steps.package_context.outputs.petsc_tag }}
      libmesh_tag: ${{ steps.package_context.outputs.libmesh_tag }}
      moose_dev_tag: ${{ steps.package_context.outputs.moose_dev_tag }}
      # Package URIs for building and pulling
      mpi_uri: ${{ steps.package_context.outputs.mpi_uri }}
      petsc_uri: ${{ steps.package_context.outputs.petsc_uri }}
      libmesh_uri: ${{ steps.package_context.outputs.libmesh_uri }}
      moose_dev_uri: ${{ steps.package_context.outputs.moose_dev_uri }}
      # Submodule SHAs for building
      conduit_sha: ${{ steps.dependency_refs.outputs.conduit_sha }}
      libmesh_sha: ${{ steps.dependency_refs.outputs.libmesh_sha }}
      mfem_sha: ${{ steps.dependency_refs.outputs.mfem_sha }}
      neml2_sha: ${{ steps.dependency_refs.outputs.neml2_sha }}
      petsc_sha: ${{ steps.dependency_refs.outputs.petsc_sha }}
      wasp_sha: ${{ steps.dependency_refs.outputs.wasp_sha }}
      vtk_version: ${{ steps.dependency_refs.outputs.vtk_version }}

    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        id: checkout
      - name: Get package versions
        shell: bash
        id: package_context
        run: |
          echo "::group::Install versioner dependencies"
          pip install --no-cache --break-system-packages pyyaml jinja2
          echo "::endgroup::"

          echo "::group::Parse packages"
          outputs=()
          summary=()
          uri_prefix="ghcr.io/${{ github.repository }}"
          base_sha="${{ steps.checkout.outputs.base_sha }}"
          packages=("mpi" "petsc" "libmesh" "moose-dev")
          for package in "${packages[@]}"; do
            base_json="$(./scripts/versioner.py "$package" "$base_sha" --json)"
            head_json="$(./scripts/versioner.py "$package" --json)"
            base_version="$(echo "$base_json" | jq -r '.full_version')"
            head_version="$(echo "$head_json" | jq -r '.full_version')"

            package_container="$package"
            if [ "$package" != "moose-dev" ]; then
              package_container="moose-${package_container}"
            fi
            package_tag="$head_version"
            package_uri="${uri_prefix}/${package_container}"
            package_build=

            if [ "$base_version" != "$head_version" ]; then
              package_build=1

              if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
                package_tag="pr-${{ github.event.pull_request.number }}"
                package_uri="${uri_prefix}/pr-${package_container}"
              fi
            fi

            package_var="${package//-/_}"
            outputs+=("${package_var}_build=${package_build}")
            outputs+=("${package_var}_tag=${package_tag}")
            outputs+=("${package_var}_uri=${package_uri}")

            summary+=("\`${package}\` | \`${base_version}\` | \`${head_version}\` | \`${package_uri}\` | \`${package_tag}\`")
          done
          echo "::endgroup::"

          echo "::group::Output step change summary"
          echo "## Docker package summary" >> $GITHUB_STEP_SUMMARY
          echo "| Package | From version | To version | URI | Tag |" >> $GITHUB_STEP_SUMMARY
          echo "| ------- | ------------ | ---------- | --- | --- |" >> $GITHUB_STEP_SUMMARY
          for entry in "${summary[@]}"; do
            echo "$entry" >> $GITHUB_STEP_SUMMARY
          done
          echo "::endgroup::"

          echo "::group::Output packages"
          for entry in "${outputs[@]}"; do
            echo "$entry" >> $GITHUB_OUTPUT
            echo "$entry"
          done
          echo "::endgroup::"
      - name: Get dependency refs
        id: dependency_refs
        shell: bash
        run: |
          echo "::group::Build refs"
          outputs=()

          outputs+=("conduit_sha=$(git rev-parse HEAD:framework/contrib/conduit)")
          outputs+=("libmesh_sha=$(git rev-parse HEAD:libmesh)")
          outputs+=("mfem_sha=$(git rev-parse HEAD:framework/contrib/mfem)")
          outputs+=("neml2_sha=$(git rev-parse HEAD:framework/contrib/neml2)")
          outputs+=("petsc_sha=$(git rev-parse HEAD:petsc)")
          outputs+=("wasp_sha=$(git rev-parse HEAD:framework/contrib/wasp)")

          vtk_version="$(./scripts/versioner.py libmesh-vtk --json | jq -r '.version')"
          outputs+=("vtk_version=${vtk_version}")
          echo "::endgroup::"

          echo "::group::Output refs"
          for entry in "${outputs[@]}"; do
            echo "$entry" >> $GITHUB_OUTPUT
            echo "$entry"
          done
          echo "::endgroup::"

  # delete_images:
  #   name: "Delete images"
  #   if: github.event_name == 'pull_request'
  #   runs-on: ubuntu-slim
  #   permissions:
  #     packages: write
  #   env:
  #     FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  #   steps:
  #     - uses: actions/delete-package-versions@v5
  #       name: Delete pr-moose-mpi
  #       with:
  #         package-name: moose/pr-moose-mpi
  #         package-type: container
  #         min-versions-to-keep: 0
  #         ignore-versions: '^(?!pr-${{ github.event.pull_request.number }})'
  #     - uses: actions/delete-package-versions@v5
  #       name: Delete pr-moose-petsc-mpich
  #       with:
  #         owner: ${{ github.repository_owner }}
  #         package-name: pr-moose-petsc-mpich
  #         package-type: container
  #         min-versions-to-keep: 0
  #         ignore-versions: '^(?!pr-${{ github.event.pull_request.number }})'
  #     - uses: actions/delete-package-versions@v5
  #       name: Delete pr-moose-libmesh-mpich
  #       with:
  #         owner: ${{ github.repository_owner }}
  #         package-name: pr-moose-libmesh-mpich
  #         package-type: container
  #         min-versions-to-keep: 0
  #         ignore-versions: '^(?!pr-${{ github.event.pull_request.number }})'

  build_moose_mpi_clang:
    name: "Build moose-mpi-clang"
    needs: [prepare]
    if: >-
      !cancelled()
      && needs.prepare.outputs.mpi_build
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reusable-build-docker.yml
    with:
      base_sha: ${{ needs.prepare.outputs.base_sha }}
      from: ghcr.io/idaholab/moose-mpibase/rocky:8.10-clang20.1.8-mpich5.0.1_2026.04.14
      file: docker/moose-mpi/Dockerfile
      uri: "${{ needs.prepare.outputs.mpi_uri }}-clang:${{ needs.prepare.outputs.mpi_tag }}"

  build_moose_mpi_clang_min:
    name: "Build moose-mpi-clang_min"
    needs:
      - prepare
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.prepare.result)
      && needs.prepare.outputs.mpi_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: ghcr.io/idaholab/moose-mpibase/rocky:8.10-clang14.0.6-mpich5.0.1_2026.04.12
          file: docker/moose-mpi/Dockerfile
          variant: clang_min
          uri_prefix: ${{ needs.prepare.outputs.mpi_uri }}
          tag: ${{ needs.prepare.outputs.mpi_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_mpi_gcc_min:
    name: "Build moose-mpi-gcc_min"
    needs:
      - prepare
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.prepare.result)
      && needs.prepare.outputs.mpi_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: ghcr.io/idaholab/moose-mpibase/rocky:8.10-gcc9.2.1-mpich5.0.1_2026.04.12
          file: docker/moose-mpi/Dockerfile
          variant: gcc_min
          uri_prefix: ${{ needs.prepare.outputs.mpi_uri }}
          tag: ${{ needs.prepare.outputs.mpi_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_mpi_intel:
    name: "Build moose-mpi-intel"
    needs:
      - prepare
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.prepare.result)
      && needs.prepare.outputs.mpi_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: ghcr.io/idaholab/moose-mpibase/rocky:8.10-oneapi2025.3.3-mpich4.3.2_2026.04.12
          file: docker/moose-mpi/Dockerfile
          variant: intel
          uri_prefix: ${{ needs.prepare.outputs.mpi_uri }}
          tag: ${{ needs.prepare.outputs.mpi_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_mpi_rocky8:
    name: "Build moose-mpi-rocky8"
    needs:
      - prepare
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.prepare.result)
      && needs.prepare.outputs.mpi_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: ghcr.io/idaholab/moose-mpibase/rocky:8.10-gcc13.3.1-mpich5.0.1-openmpi5.0.10_2026.04.12
          file: docker/moose-mpi/Dockerfile
          variant: rocky8
          uri_prefix: ${{ needs.prepare.outputs.mpi_uri }}
          tag: ${{ needs.prepare.outputs.mpi_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_mpi_rocky9:
    name: "Build moose-mpi-rocky9"
    needs:
      - prepare
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.prepare.result)
      && needs.prepare.outputs.mpi_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: ghcr.io/idaholab/moose-mpibase/rocky:9.7-gcc13.3.1-mpich4.3.2-openmpi5.0.10_2026.04.12
          file: docker/moose-mpi/Dockerfile
          variant: rocky9
          uri_prefix: ${{ needs.prepare.outputs.mpi_uri }}
          tag: ${{ needs.prepare.outputs.mpi_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_petsc_clang_mpich:
    name: "Build moose-petsc-clang-mpich"
    needs:
      - prepare
      - build_moose_mpi_clang
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_mpi_clang.result)
      && needs.prepare.outputs.petsc_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: "${{ needs.prepare.outputs.mpi_uri }}-clang:${{ needs.prepare.outputs.mpi_tag }}"
          file: docker/moose-petsc/Dockerfile
          variant: clang-mpich
          build_args: |
            MPI_FLAVOUR=mpich
            PETSC_GIT_REF=${{ needs.prepare.outputs.petsc_sha }}
          uri_prefix: ${{ needs.prepare.outputs.petsc_uri }}
          tag: ${{ needs.prepare.outputs.petsc_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_petsc_clang_min_mpich:
    name: "Build moose-petsc-clang_min-mpich"
    needs:
      - prepare
      - build_moose_mpi_clang_min
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_mpi_clang_min.result)
      && needs.prepare.outputs.petsc_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: "${{ needs.prepare.outputs.mpi_uri }}-clang_min:${{ needs.prepare.outputs.mpi_tag }}"
          file: docker/moose-petsc/Dockerfile
          variant: clang_min-mpich
          build_args: |
            MPI_FLAVOUR=mpich
            PETSC_GIT_REF=${{ needs.prepare.outputs.petsc_sha }}
          uri_prefix: ${{ needs.prepare.outputs.petsc_uri }}
          tag: ${{ needs.prepare.outputs.petsc_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_petsc_gcc_min_mpich:
    name: "Build moose-petsc-gcc_min-mpich"
    needs:
      - prepare
      - build_moose_mpi_gcc_min
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_mpi_gcc_min.result)
      && needs.prepare.outputs.petsc_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: "${{ needs.prepare.outputs.mpi_uri }}-gcc_min:${{ needs.prepare.outputs.mpi_tag }}"
          file: docker/moose-petsc/Dockerfile
          variant: gcc_min-mpich
          build_args: |
            MPI_FLAVOUR=mpich
            PETSC_GIT_REF=${{ needs.prepare.outputs.petsc_sha }}
          uri_prefix: ${{ needs.prepare.outputs.petsc_uri }}
          tag: ${{ needs.prepare.outputs.petsc_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_petsc_intel_mpich:
    name: "Build moose-petsc-intel-mpich"
    needs:
      - prepare
      - build_moose_mpi_intel
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_mpi_intel.result)
      && needs.prepare.outputs.petsc_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: "${{ needs.prepare.outputs.mpi_uri }}-intel:${{ needs.prepare.outputs.mpi_tag }}"
          file: docker/moose-petsc/Dockerfile
          variant: intel-mpich
          build_args: |
            MPI_FLAVOUR=mpich
            PETSC_GIT_REF=${{ needs.prepare.outputs.petsc_sha }}
          uri_prefix: ${{ needs.prepare.outputs.petsc_uri }}
          tag: ${{ needs.prepare.outputs.petsc_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_petsc_rocky8_mpich:
    name: "Build moose-petsc-rocky8-mpich"
    needs:
      - prepare
      - build_moose_mpi_rocky8
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_mpi_rocky8.result)
      && needs.prepare.outputs.petsc_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: "${{ needs.prepare.outputs.mpi_uri }}-rocky8:${{ needs.prepare.outputs.mpi_tag }}"
          file: docker/moose-petsc/Dockerfile
          variant: rocky8-mpich
          build_args: |
            MPI_FLAVOUR=mpich
            PETSC_GIT_REF=${{ needs.prepare.outputs.petsc_sha }}
          uri_prefix: ${{ needs.prepare.outputs.petsc_uri }}
          tag: ${{ needs.prepare.outputs.petsc_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_petsc_rocky8_openmpi:
    name: "Build moose-petsc-rocky8-openmpi"
    needs:
      - prepare
      - build_moose_mpi_rocky8
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_mpi_rocky8.result)
      && needs.prepare.outputs.petsc_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: "${{ needs.prepare.outputs.mpi_uri }}-rocky8:${{ needs.prepare.outputs.mpi_tag }}"
          file: docker/moose-petsc/Dockerfile
          variant: rocky8-openmpi
          build_args: |
            MPI_FLAVOUR=openmpi
            PETSC_GIT_REF=${{ needs.prepare.outputs.petsc_sha }}
          uri_prefix: ${{ needs.prepare.outputs.petsc_uri }}
          tag: ${{ needs.prepare.outputs.petsc_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_petsc_rocky9_mpich:
    name: "Build moose-petsc-rocky9-mpich"
    needs:
      - prepare
      - build_moose_mpi_rocky9
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_mpi_rocky9.result)
      && needs.prepare.outputs.petsc_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: "${{ needs.prepare.outputs.mpi_uri }}-rocky9:${{ needs.prepare.outputs.mpi_tag }}"
          file: docker/moose-petsc/Dockerfile
          variant: rocky9-mpich
          build_args: |
            MPI_FLAVOUR=mpich
            PETSC_GIT_REF=${{ needs.prepare.outputs.petsc_sha }}
          uri_prefix: ${{ needs.prepare.outputs.petsc_uri }}
          tag: ${{ needs.prepare.outputs.petsc_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_libmesh_clang_mpich:
    name: "Build moose-libmesh-clang-mpich"
    needs:
      - prepare
      - build_moose_petsc_clang_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_petsc_clang_mpich.result)
      && needs.prepare.outputs.libmesh_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: "${{ needs.prepare.outputs.petsc_uri }}-clang-mpich:${{ needs.prepare.outputs.petsc_tag }}"
          file: docker/moose-libmesh/Dockerfile
          variant: clang-mpich
          build_args: |
            LIBMESH_GIT_REF=${{ needs.prepare.outputs.libmesh_sha }}
            VTK_VERSION=${{ needs.prepare.outputs.vtk_version }}
          uri_prefix: ${{ needs.prepare.outputs.libmesh_uri }}
          tag: ${{ needs.prepare.outputs.libmesh_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_libmesh_clang_min_mpich:
    name: "Build moose-libmesh-clang_min-mpich"
    needs:
      - prepare
      - build_moose_petsc_clang_min_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_petsc_clang_min_mpich.result)
      && needs.prepare.outputs.libmesh_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: "${{ needs.prepare.outputs.petsc_uri }}-clang_min-mpich:${{ needs.prepare.outputs.petsc_tag }}"
          file: docker/moose-libmesh/Dockerfile
          variant: clang_min-mpich
          build_args: |
            LIBMESH_GIT_REF=${{ needs.prepare.outputs.libmesh_sha }}
            VTK_VERSION=${{ needs.prepare.outputs.vtk_version }}
          uri_prefix: ${{ needs.prepare.outputs.libmesh_uri }}
          tag: ${{ needs.prepare.outputs.libmesh_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_libmesh_gcc_min_mpich:
    name: "Build moose-libmesh-gcc_min-mpich"
    needs:
      - prepare
      - build_moose_petsc_gcc_min_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_petsc_gcc_min_mpich.result)
      && needs.prepare.outputs.libmesh_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: "${{ needs.prepare.outputs.petsc_uri }}-gcc_min-mpich:${{ needs.prepare.outputs.petsc_tag }}"
          file: docker/moose-libmesh/Dockerfile
          variant: gcc_min-mpich
          build_args: |
            LIBMESH_GIT_REF=${{ needs.prepare.outputs.libmesh_sha }}
            VTK_VERSION=${{ needs.prepare.outputs.vtk_version }}
          uri_prefix: ${{ needs.prepare.outputs.libmesh_uri }}
          tag: ${{ needs.prepare.outputs.libmesh_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_libmesh_intel_mpich:
    name: "Build moose-libmesh-intel-mpich"
    needs:
      - prepare
      - build_moose_petsc_intel_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_petsc_intel_mpich.result)
      && needs.prepare.outputs.libmesh_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: "${{ needs.prepare.outputs.petsc_uri }}-intel-mpich:${{ needs.prepare.outputs.petsc_tag }}"
          file: docker/moose-libmesh/Dockerfile
          variant: intel-mpich
          build_args: |
            LIBMESH_GIT_REF=${{ needs.prepare.outputs.libmesh_sha }}
            VTK_VERSION=${{ needs.prepare.outputs.vtk_version }}
          uri_prefix: ${{ needs.prepare.outputs.libmesh_uri }}
          tag: ${{ needs.prepare.outputs.libmesh_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_libmesh_rocky8_mpich:
    name: "Build moose-libmesh-rocky8-mpich"
    needs:
      - prepare
      - build_moose_petsc_rocky8_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_petsc_rocky8_mpich.result)
      && needs.prepare.outputs.libmesh_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: "${{ needs.prepare.outputs.petsc_uri }}-rocky8-mpich:${{ needs.prepare.outputs.petsc_tag }}"
          file: docker/moose-libmesh/Dockerfile
          variant: rocky8-mpich
          build_args: |
            LIBMESH_GIT_REF=${{ needs.prepare.outputs.libmesh_sha }}
            VTK_VERSION=${{ needs.prepare.outputs.vtk_version }}
          uri_prefix: ${{ needs.prepare.outputs.libmesh_uri }}
          tag: ${{ needs.prepare.outputs.libmesh_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_libmesh_rocky8_openmpi:
    name: "Build moose-libmesh-rocky8-openmpi"
    needs:
      - prepare
      - build_moose_petsc_rocky8_openmpi
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_petsc_rocky8_openmpi.result)
      && needs.prepare.outputs.libmesh_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: "${{ needs.prepare.outputs.petsc_uri }}-rocky8-openmpi:${{ needs.prepare.outputs.petsc_tag }}"
          file: docker/moose-libmesh/Dockerfile
          variant: rocky8-openmpi
          build_args: |
            LIBMESH_GIT_REF=${{ needs.prepare.outputs.libmesh_sha }}
            VTK_VERSION=${{ needs.prepare.outputs.vtk_version }}
          uri_prefix: ${{ needs.prepare.outputs.libmesh_uri }}
          tag: ${{ needs.prepare.outputs.libmesh_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_libmesh_rocky9_mpich:
    name: "Build moose-libmesh-rocky9-mpich"
    needs:
      - prepare
      - build_moose_petsc_rocky9_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_petsc_rocky9_mpich.result)
      && needs.prepare.outputs.libmesh_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: "${{ needs.prepare.outputs.petsc_uri }}-rocky9-mpich:${{ needs.prepare.outputs.petsc_tag }}"
          file: docker/moose-libmesh/Dockerfile
          variant: rocky9-mpich
          build_args: |
            LIBMESH_GIT_REF=${{ needs.prepare.outputs.libmesh_sha }}
            VTK_VERSION=${{ needs.prepare.outputs.vtk_version }}
          uri_prefix: ${{ needs.prepare.outputs.libmesh_uri }}
          tag: ${{ needs.prepare.outputs.libmesh_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_dev_clang_mpich:
    name: "Build moose-dev-clang-mpich"
    needs:
      - prepare
      - build_moose_libmesh_clang_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_libmesh_clang_mpich.result)
      && needs.prepare.outputs.moose_dev_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: "${{ needs.prepare.outputs.libmesh_uri }}-clang-mpich:${{ needs.prepare.outputs.libmesh_tag }}"
          file: docker/moose-dev/Dockerfile
          variant: clang-mpich
          build_args: |
            CONDUIT_GIT_REF=${{ needs.prepare.outputs.conduit_sha }}
            MFEM_GIT_REF=${{ needs.prepare.outputs.mfem_sha }}
            NEML2_GIT_REF=${{ needs.prepare.outputs.neml2_sha }}
            WASP_GIT_REF=${{ needs.prepare.outputs.wasp_sha }}
          uri_prefix: ${{ needs.prepare.outputs.moose_dev_uri }}
          tag: ${{ needs.prepare.outputs.moose_dev_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_dev_clang_min_mpich:
    name: "Build moose-dev-clang_min-mpich"
    needs:
      - prepare
      - build_moose_libmesh_clang_min_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_libmesh_clang_min_mpich.result)
      && needs.prepare.outputs.moose_dev_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: "${{ needs.prepare.outputs.libmesh_uri }}-clang_min-mpich:${{ needs.prepare.outputs.libmesh_tag }}"
          file: docker/moose-dev/Dockerfile
          variant: clang_min-mpich
          build_args: |
            CONDUIT_GIT_REF=${{ needs.prepare.outputs.conduit_sha }}
            MFEM_GIT_REF=${{ needs.prepare.outputs.mfem_sha }}
            WASP_GIT_REF=${{ needs.prepare.outputs.wasp_sha }}
            LIBTORCH_SKIP=1
            NEML2_SKIP=1
          uri_prefix: ${{ needs.prepare.outputs.moose_dev_uri }}
          tag: ${{ needs.prepare.outputs.moose_dev_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_dev_gcc_min_mpich:
    name: "Build moose-dev-gcc_min-mpich"
    needs:
      - prepare
      - build_moose_libmesh_gcc_min_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_libmesh_gcc_min_mpich.result)
      && needs.prepare.outputs.moose_dev_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: "${{ needs.prepare.outputs.libmesh_uri }}-gcc_min-mpich:${{ needs.prepare.outputs.libmesh_tag }}"
          file: docker/moose-dev/Dockerfile
          variant: gcc_min-mpich
          build_args: |
            CONDUIT_GIT_REF=${{ needs.prepare.outputs.conduit_sha }}
            MFEM_GIT_REF=${{ needs.prepare.outputs.mfem_sha }}
            WASP_GIT_REF=${{ needs.prepare.outputs.wasp_sha }}
            NEML2_SKIP=1
            LIBTORCH_SKIP=1
          uri_prefix: ${{ needs.prepare.outputs.moose_dev_uri }}
          tag: ${{ needs.prepare.outputs.moose_dev_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_dev_intel_mpich:
    name: "Build moose-dev-intel-mpich"
    needs:
      - prepare
      - build_moose_libmesh_intel_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_libmesh_intel_mpich.result)
      && needs.prepare.outputs.moose_dev_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: "${{ needs.prepare.outputs.libmesh_uri }}-intel-mpich:${{ needs.prepare.outputs.libmesh_tag }}"
          file: docker/moose-dev/Dockerfile
          variant: intel-mpich
          build_args: |
            CONDUIT_GIT_REF=${{ needs.prepare.outputs.conduit_sha }}
            MFEM_GIT_REF=${{ needs.prepare.outputs.mfem_sha }}
            NEML2_GIT_REF=${{ needs.prepare.outputs.neml2_sha }}
            WASP_GIT_REF=${{ needs.prepare.outputs.wasp_sha }}
            LIBTORCH_SKIP=1
          uri_prefix: ${{ needs.prepare.outputs.moose_dev_uri }}
          tag: ${{ needs.prepare.outputs.moose_dev_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_dev_rocky8_mpich:
    name: "Build moose-dev-rocky8-mpich"
    needs:
      - prepare
      - build_moose_libmesh_rocky8_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_libmesh_rocky8_mpich.result)
      && needs.prepare.outputs.moose_dev_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: "${{ needs.prepare.outputs.libmesh_uri }}-rocky8-mpich:${{ needs.prepare.outputs.libmesh_tag }}"
          file: docker/moose-dev/Dockerfile
          variant: rocky8-mpich
          build_args: |
            CONDUIT_GIT_REF=${{ needs.prepare.outputs.conduit_sha }}
            MFEM_GIT_REF=${{ needs.prepare.outputs.mfem_sha }}
            NEML2_GIT_REF=${{ needs.prepare.outputs.neml2_sha }}
            WASP_GIT_REF=${{ needs.prepare.outputs.wasp_sha }}
          uri_prefix: ${{ needs.prepare.outputs.moose_dev_uri }}
          tag: ${{ needs.prepare.outputs.moose_dev_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_dev_rocky8_openmpi:
    name: "Build moose-dev-rocky8-openmpi"
    needs:
      - prepare
      - build_moose_libmesh_rocky8_openmpi
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_libmesh_rocky8_openmpi.result)
      && needs.prepare.outputs.moose_dev_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: "${{ needs.prepare.outputs.libmesh_uri }}-rocky8-openmpi:${{ needs.prepare.outputs.libmesh_tag }}"
          file: docker/moose-dev/Dockerfile
          variant: rocky8-openmpi
          build_args: |
            CONDUIT_GIT_REF=${{ needs.prepare.outputs.conduit_sha }}
            MFEM_GIT_REF=${{ needs.prepare.outputs.mfem_sha }}
            NEML2_GIT_REF=${{ needs.prepare.outputs.neml2_sha }}
            WASP_GIT_REF=${{ needs.prepare.outputs.wasp_sha }}
          uri_prefix: ${{ needs.prepare.outputs.moose_dev_uri }}
          tag: ${{ needs.prepare.outputs.moose_dev_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  build_moose_dev_rocky9_mpich:
    name: "Build moose-dev-rocky9-mpich"
    needs:
      - prepare
      - build_moose_libmesh_rocky9_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_libmesh_rocky9_mpich.result)
      && needs.prepare.outputs.moose_dev_build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build-docker@actions
        name: Build and push
        with:
          from: "${{ needs.prepare.outputs.libmesh_uri }}-rocky9-mpich:${{ needs.prepare.outputs.libmesh_tag }}"
          file: docker/moose-dev/Dockerfile
          variant: rocky9-mpich
          build_args: |
            CONDUIT_GIT_REF=${{ needs.prepare.outputs.conduit_sha }}
            MFEM_GIT_REF=${{ needs.prepare.outputs.mfem_sha }}
            NEML2_GIT_REF=${{ needs.prepare.outputs.neml2_sha }}
            WASP_GIT_REF=${{ needs.prepare.outputs.wasp_sha }}
          uri_prefix: ${{ needs.prepare.outputs.moose_dev_uri }}
          tag: ${{ needs.prepare.outputs.moose_dev_tag }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}

  #
  # Modules, with moose-dev-rocky8-mpich
  #

  modules:
    name: "Modules"
    needs:
      - prepare
      - build_moose_dev_rocky8_mpich
    if: >-
      !cancelled()
      && !always()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_dev_rocky8_mpich.result)
    runs-on: ubuntu-slim
    steps:
      - name: Test
        shell: bash
        run: |
          echo "testing"

  modules_debug:
    name: "Modules debug"
    needs:
      - prepare
      - build_moose_dev_rocky8_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_dev_rocky8_mpich.result)
    runs-on: ubuntu-24.04
    container:
      image: "${{ needs.prepare.outputs.moose_dev_uri }}-rocky8-mpich:${{ needs.prepare.outputs.moose_dev_tag }}"
      options: --shm-size=1gb
    env:
      METHOD: dbg
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/configure-moose@actions
        name: Configure with kokkos, libtorch, neml2, mfem
        with:
          args: --with-kokkos=cpu --with-libtorch --with-neml2 --with-mfem
      - uses: idaholab/moose/build@actions
        name: Build
        with:
          dir: modules
          args: all builds
      - uses: idaholab/moose/tests@actions
        name: Test
        with:
          dir: modules
          args: --use-subdir-exe

  modules_parallel:
    name: "Modules parallel"
    needs:
      - prepare
      - build_moose_dev_rocky8_mpich
    if: >-
      !cancelled()
      && !always()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_dev_rocky8_mpich.result)
    runs-on: ubuntu-slim
    steps:
      - name: Test
        shell: bash
        run: |
          echo "testing"

  modules_recover:
    name: "Modules recover"
    needs:
      - prepare
      - build_moose_dev_rocky8_mpich
    if: >-
      !cancelled()
      && !always()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_dev_rocky8_mpich.result)
    runs-on: ubuntu-slim
    steps:
      - name: Test
        shell: bash
        run: |
          echo "testing"

  modules_restep:
    name: "Modules restep"
    needs:
      - prepare
      - build_moose_dev_rocky8_mpich
    if: >-
      !cancelled()
      && !always()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_dev_rocky8_mpich.result)
    runs-on: ubuntu-slim
    steps:
      - name: Test
        shell: bash
        run: |
          echo "testing"

  fluid_properties_apps:
    name: "Fluid properties apps"
    needs:
      - prepare
      - build_moose_dev_rocky8_mpich
    if: >-
      !cancelled()
      && !always()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_dev_rocky8_mpich.result)
    runs-on: ubuntu-slim
    steps:
      - name: Test
        shell: bash
        run: |
          echo "testing"

  #
  # Sweeps, with moose-dev-rocky8-mpich
  # On: push, PR with "CI: sweeps" label
  #

  sweeps:
    name: "Sweeps"
    needs:
      - prepare
      - build_moose_dev_rocky8_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_dev_rocky8_mpich.result)
      && (github.event_name == 'push' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'CI\u003A sweeps')))
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        type:
          - -p
          - --recover -p
          - --distributed-mesh -p
          - --distributed-mesh --recover -p
        number:
          - odd
          - even
    container:
      image: "${{ needs.prepare.outputs.moose_dev_uri }}-rocky8-mpich:${{ needs.prepare.outputs.moose_dev_tag }}"
      options: --shm-size=1gb
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/configure-moose@actions
        name: Configure with kokkos
        with:
          args: --with-kokkos
      - uses: idaholab/moose/build@actions
        name: Build
        with:
          dir: test
      - uses: idaholab/moose/tests@actions
        name: Test ${{ matrix.type }} ${{ matrix.number == 'odd' && '3' || '4' }}
        with:
          dir: test
          args: ${{ matrix.type }} ${{ matrix.number == 'odd' && '3' || '4' }}
      - uses: idaholab/moose/tests@actions
        name: Test ${{ matrix.type }} ${{ matrix.number == 'odd' && '5' || '6' }}
        with:
          dir: test
          args: ${{ matrix.type }} ${{ matrix.number == 'odd' && '5' || '6' }}
      - uses: idaholab/moose/tests@actions
        name: Test ${{ matrix.type }} ${{ matrix.number == 'odd' && '7' || '8' }}
        with:
          dir: test
          args: ${{ matrix.type }} ${{ matrix.number == 'odd'&& '7' || '8' }}
      - uses: idaholab/moose/tests@actions
        name: Test ${{ matrix.type }} ${{ matrix.number == 'odd' && '15' || '16' }}
        with:
          dir: test
          args: ${{ matrix.type }} ${{ matrix.number == 'odd' && '15' || '16' }}

  #
  # Clang, with moose-dev-clang-mpich
  #

  clang:
    name: "Clang"
    needs:
      - prepare
      - build_moose_dev_clang_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_dev_clang_mpich.result)
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        method:
          - opt
          - dbg
    env:
      METHOD: ${{ matrix.method }}
    container:
      image: "${{ needs.prepare.outputs.moose_dev_uri }}-clang-mpich:${{ needs.prepare.outputs.moose_dev_tag }}"
      options: --shm-size=1gb
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/configure-moose@actions
        name: Configure with kokkos
        with:
          args: --with-kokkos
      - uses: idaholab/moose/build@actions
        name: Build test
        with:
          dir: test
      - uses: idaholab/moose/tests@actions
        name: Test moose test
        with:
          dir: test
      - uses: idaholab/moose/build@actions
        name: Build modules
        with:
          dir: modules
          args: all builds
      - uses: idaholab/moose/tests@actions
        name: Test modules
        with:
          dir: modules
          args: --use-subdir-exe
      - uses: idaholab/moose/build@actions
        name: Build unit
        with:
          dir: unit
      - uses: idaholab/moose/tests@actions
        name: Test unit
        with:
          dir: unit

  #
  # Clang min, with moose-dev-clang_min-mpich
  #

  clang_min:
    name: "Clang min"
    needs:
      - prepare
      - build_moose_dev_clang_min_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_dev_clang_min_mpich.result)
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        method:
          - opt
          - dbg
    env:
      METHOD: ${{ matrix.method }}
    container:
      image: "${{ needs.prepare.outputs.moose_dev_uri }}-clang_min-mpich:${{ needs.prepare.outputs.moose_dev_tag }}"
      options: --shm-size=1gb
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/configure-moose@actions
        name: Configure with kokkos, mfem
        with:
          args: --with-kokkos --with-mfem
      - uses: idaholab/moose/build@actions
        name: Build test
        with:
          dir: test
      - uses: idaholab/moose/tests@actions
        name: Test moose test
        with:
          dir: test
      - uses: idaholab/moose/build@actions
        name: Build modules
        with:
          dir: modules
          args: all builds
      - uses: idaholab/moose/tests@actions
        name: Test modules
        with:
          dir: modules
          args: --use-subdir-exe
      - uses: idaholab/moose/build@actions
        name: Build unit
        with:
          dir: unit
      - uses: idaholab/moose/tests@actions
        name: Test unit
        with:
          dir: unit

  #
  # GCC min, with moose-dev-gcc_min-mpich
  #

  gcc_min:
    name: "GCC min"
    needs:
      - prepare
      - build_moose_dev_gcc_min_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_dev_gcc_min_mpich.result)
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        method:
          - opt
          - dbg
    env:
      METHOD: ${{ matrix.method }}
    container:
      image: "${{ needs.prepare.outputs.moose_dev_uri }}-gcc_min-mpich:${{ needs.prepare.outputs.moose_dev_tag }}"
      options: --shm-size=1gb
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/configure-moose@actions
        name: Configure with kokkos, mfem
        with:
          args: --with-kokkos --with-mfem
      - uses: idaholab/moose/build@actions
        name: Build test
        with:
          dir: test
      - uses: idaholab/moose/tests@actions
        name: Test moose test
        with:
          dir: test
      - uses: idaholab/moose/build@actions
        name: Build modules
        with:
          dir: modules
          args: all builds
      - uses: idaholab/moose/tests@actions
        name: Test modules
        with:
          dir: modules
          args: --use-subdir-exe
      - uses: idaholab/moose/build@actions
        name: Build unit
        with:
          dir: unit
      - uses: idaholab/moose/tests@actions
        name: Test unit
        with:
          dir: unit

  #
  # Intel, with moose-dev-intel-mpich
  #

  intel:
    name: "Intel"
    needs:
      - prepare
      - build_moose_dev_intel_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_dev_intel_mpich.result)
    runs-on: ubuntu-24.04
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/configure-moose@actions
        name: Configure with kokkos, mfem
        with:
          args: --with-kokkos --with-mfem
      - uses: idaholab/moose/build@actions
        name: Build test
        with:
          dir: test
      - uses: idaholab/moose/build@actions
        name: Build unit
        with:
          dir: unit
      - uses: idaholab/moose/tests@actions
        name: Test unit
        with:
          dir: unit

  #
  # Heavy, with moose-dev-rocky8-mpich
  #

  heavy:
    name: "Heavy"
    needs:
      - prepare
      - build_moose_dev_rocky8_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_dev_rocky8_mpich.result)
    runs-on: ubuntu-24.04
    container:
      image: "${{ needs.prepare.outputs.moose_dev_uri }}-rocky8-mpich:${{ needs.prepare.outputs.moose_dev_tag }}"
      options: --shm-size=1gb
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/configure-moose@actions
        name: Configure with kokkos, libtorch, neml2, mfem
        with:
          args: --with-kokkos=cpu --with-libtorch --with-neml2 --with-mfem
      - uses: idaholab/moose/build@actions
        name: Build test
        with:
          dir: test
      - uses: idaholab/moose/tests@actions
        name: Test test --heavy
        with:
          dir: test
          args: --heavy
      - uses: idaholab/moose/build@actions
        name: Build modules
        with:
          dir: modules
      - uses: idaholab/moose/tests@actions
        name: Test modules --heavy
        with:
          dir: modules
          args: --heavy

  #
  # No optional, with moose-dev-rocky8-mpich
  #

  no_optional:
    name: "No optional"
    needs:
      - prepare
      - build_moose_dev_rocky8_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_dev_rocky8_mpich.result)
    runs-on: ubuntu-24.04
    container:
      image: "${{ needs.prepare.outputs.moose_dev_uri }}-rocky8-mpich:${{ needs.prepare.outputs.moose_dev_tag }}"
      options: --shm-size=1gb
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build@actions
        name: Build test
        with:
          dir: test
      - uses: idaholab/moose/tests@actions
        name: Test test
        with:
          dir: test
      - uses: idaholab/moose/build@actions
        name: Build unit
        with:
          dir: unit
      - uses: idaholab/moose/tests@actions
        name: Test unit
        with:
          dir: unit
      - uses: idaholab/moose/build@actions
        name: Build modules
        with:
          dir: modules
          args: all builds
      - uses: idaholab/moose/tests@actions
        name: Test modules
        with:
          dir: modules
          args: --use-subdir-exe

  #
  # No unity, with moose-dev-rocky8-mpich
  #

  no_unity:
    name: "No unity"
    needs:
      - prepare
      - build_moose_dev_rocky8_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_dev_rocky8_mpich.result)
    runs-on: ubuntu-24.04
    container:
      image: "${{ needs.prepare.outputs.moose_dev_uri }}-rocky8-mpich:${{ needs.prepare.outputs.moose_dev_tag }}"
      options: --shm-size=1gb
    env:
      MOOSE_UNITY: false
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build@actions
        name: Build test
        with:
          dir: test
      - uses: idaholab/moose/build@actions
        name: Build modules
        with:
          dir: modules

  #
  # Python, with moose-dev-rocky8-mpich
  #

  python:
    name: "Python"
    needs:
      - prepare
      - build_moose_dev_rocky8_mpich
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.build_moose_dev_rocky8_mpich.result)
    runs-on: ubuntu-24.04
    container:
      image: "${{ needs.prepare.outputs.moose_dev_uri }}-rocky8-mpich:${{ needs.prepare.outputs.moose_dev_tag }}"
      options: --shm-size=1gb
    steps:
      - uses: idaholab/moose/checkout@actions
        name: Checkout
        with:
          pr_base_sha: ${{ needs.prepare.outputs.base_sha }}
      - uses: idaholab/moose/build@actions
        name: Build test
        with:
          dir: test
      - uses: idaholab/moose/tests@actions
        name: Test python
        with:
          dir: python
      - uses: idaholab/moose/tests@actions
        name: Test scripts
        with:
          dir: scripts
