name: "Scheduled: Merge devel"

on:
  # Daily at 8 PM
  schedule:
    - cron: "0 20 * * *"
      timezone: "America/Denver"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  merge-staged-to-devel:
    name: Merge staged to devel
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'workflow_dispatch' && 'scheduled-merges' || '' }}
    env:
      SOURCE_BRANCH: staged
      TARGET_BRANCH: devel
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ env.TARGET_BRANCH }}
          fetch-depth: 0
          token: ${{ secrets.MOOSEBUILD_GIT_WRITE }}
      - name: Merge
        run: |
          git fetch origin "$SOURCE_BRANCH"
          git merge --ff-only "origin/${SOURCE_BRANCH}"
          git push origin "$TARGET_BRANCH"
